### ISSUE TITLE
Errors when shutting down node

### ISSUE THREAD

**Issue by travnewmatic** [democratic-csi/democratic-csi#103]
is this normal?
![image](https://user-images.githubusercontent.com/11083305/123625957-e072e780-d842-11eb-849f-a0cafe2e7b4a.png)

**Comment by travisghansen** [comment]
Are you properly draining the node or just issuing the reboot command?

**Comment by travnewmatic** [comment]
nope!  i definitely do not do that properly.  i guess i figured the OS would stop things safely on shutdown, but that appears to be an incorrect assumption.

thank you for pointing this out!

**Comment by travisghansen** [comment]
Yeah, a couple links that may be helpful:

- https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/
- https://github.com/weaveworks/kured

**Comment by travnewmatic** [comment]
yes!  was reading those pages just a few moments ago.  thanks for the tip!

**Comment by travnewmatic** [comment]
closing this, if i still have problems after draining the node properly, i'll ask later.  thanks again!
