### ISSUE TITLE
[Question] Installation Instructions without helm Chart

### ISSUE THREAD

**Issue by ppvolto** [democratic-csi/democratic-csi#104]
My Question is there Information on how to Setup this Controller without the Helm Chart.

Since the IP-Adresses between clusters can differ and i like to have the configuration only in IP-Adresses dynamic.
I define a cluster in version Control and its configured with ansible currently the exception are Helm Charts.

**Comment by travisghansen** [comment]
@infra-monkey has been working on some ansible roles I think which may help.

Do you want static yaml? Or after something else?

**Comment by ppvolto** [comment]
Static yaml with notations for todos is i think the best option.

**Comment by travisghansen** [comment]
Would using helm template suffice for your use case? The deployment of csi drivers (generally, not specific to this project) is pretty involved/intricate. Trying to maintain that could get messy.

**Comment by ppvolto** [comment]
I think thats can help yes.

**Comment by travisghansen** [comment]
Give it a try and let me know. I’m not doing anything funny with pre/post hooks in helm so that shouldn’t be a problem.

**Comment by infra-monkey** [comment]
Hi,
I've been working on an ansible role indeed (but busy lately so I had planned to get back to it next week).
It would be a wrapper around the helm chart but it may help. I hope I can provide a usable first version in a couple weeks.

Which drivers are you using?
