### ISSUE TITLE
[QUESTION] Raspberrypi/ARM64 support on Kubernetes or guide for installation

### ISSUE THREAD

**Issue by OO00dougal00OO** [democratic-csi/democratic-csi#108]
Hello, sorry if this is not the right place to put this but I understand that ARM64 is supported using custom images. How do I go about doing this are they any writeups or guides ( i have tried googling but did not get very far)?

Thanks!!!!

**Comment by travisghansen** [comment]
No custom images needed any more. I run everything in an arm64 cluster using the current version of the chart.

Let me know if you have issues and we'll get them sorted out!

**Comment by travisghansen** [comment]
Ok armv7 should work out of the box as well.
