### ISSUE TITLE
Passwordless sudo cannot be set when sudo=false

### ISSUE THREAD

**Issue by mcflis** [democratic-csi/democratic-csi#118]
Hey there, I've found that the README lacks a crucial note.

## What's happening
when you create a new user (for sudo-based csi driver usage) using the TrueNas UI and you leave the checkbox "Permit Sudo" unticked, the setup described in the README.md won't work.

Specifically `account user update id=<id> sudo_nopasswd=true` will have no effect. The sudoers file in `/usr/local/etc/sudoers` won't list your new user.

## Steps
1. Create a new user in the TrueNas Web UI without the "Permit Sudo" checkbox ticked
2. Run truenas `cli`
3. Find your new user's id as described in the docs
4. run `account user update id=<id> sudo_nopasswd=true`
5. Hit `ctrl-d` to exit the cli
6. run `cat /usr/local/etc/sudoers`
7. Notice your new user is not listed in the file

## Expected behaviour
A `<user> ALL=(ALL) NOPASSWD: ALL` line exists in `/usr/local/etc/sudoers`

## Actual behaviour
Line does not exist

## Workaround / Fix
- Tick the checkbox "Permit Sudo" when creating the user
- Or add `sudo=true` to `account user update id=<id> sudo_nopasswd=true` -> `account user update id=<id> sudo=true sudo_nopasswd=true`

## Environment
TrueNas Version: TrueNAS-12.0-U5.1

**Comment by travisghansen** [comment]
Welcome!

Thanks for the tip in the name of completeness. I sort of assumed folks would check permit sudo implicitly in the scenario but I'll add the notes to the `README.md`. Thanks!

How has your experience been with the driver thus far?

**Comment by mcflis** [comment]
Thanks!

If you start from scratch, you'll probably tick the checkbox, but if you're like me and have limited spare time for fun stuff like this, you'll set up everything in chunks. I've created my `csi` user way ahead of actually trying to get this driver to work. Most probably, I wasn't paying attention while creating the user.

Anyways, I'm glad your work exists. I've just created a `HelmChart` manifest and copied it to the directory where [`k3s`'s helm controller would just pick it up automatically](https://rancher.com/docs/k3s/latest/en/helm). And it worked, so kudos to you :)
I'm in the middle of figuring out how to get rid of my isolated docker containers running on RPis in my home lab and port everything to k3s (for now, running on my dev machine in 4 distinct ubuntu VMs).\
BUT, one step at a time and now I'm at evaluating my storage options. Your driver enabled my Truenas box to provide storage space using `nfs` to my k3s cluster after reading the docs and a few issues in this repo. With `iscsi` there seems to be an issue where the `open-iscsi` service won't come up because of some failed conditions, but I don't think I'll need `iscsi` in the end.

However, the more important question to me is how would it be possible to restore pvs/pvcs in a (mostly) automated way if I need to recreate the cluster.
My cluster is set up by using the ansible role [PyratLabs/ansible-role-k3s](https://github.com/PyratLabs/ansible-role-k3s) and my custom playbook. Ideally, I would just run this playbook (to recreate the cluster) and everything is back in place.
I've seen #20 but I'll need to dig deeper and play with it for a while to find an answer to my question. Or maybe you might have some input? 

Thanks, anyways!

**Comment by travisghansen** [comment]
OK, doc has been committed and merged.

`iscsi` in ubuntu seems to have some funny defaults (you may need to create some dirs manually, etc). You need to make sure the iscsid daemon is running such that `iscsiadm -m session` functions directly on the node. Once that is done you should be good to go.

Regarding restore it's not really possible (in the fashion you describe). The proper approach is to backup your cluster as a whole (etcd data) and then restore that. That will get you back into the exact same state as before.

**Comment by mcflis** [comment]
Thanks, this can be closed now
