### ISSUE TITLE
Timeouts and invalid CSI drivers?

### ISSUE THREAD

**Issue by drewfurgiuele** [democratic-csi/democratic-csi#12]
Cool project! I can get the helm chart deployed, and I can create test volumes, however, I am hitting an error when attempting to bind some volumes:

"rpc error: code = Unknown desc = hit timeout waiting for device node to appear" is what I'm seeing in my pods. I'm assuming that's a configuration error on my part, but I'm struggling to understand where.

I'm also seeing errors like: "csi driver not valid too"

This is for an iscsi implementation. I'd use the NFS provider, but I'm having trouble with permission chaning (I want the containers to own everything). Any advice would be appreciated. Happy to supply any logs you need.

**Comment by drewfurgiuele** [comment]
Also maybe related: when cleaning up failed deployments from my applications, I'm seeing a lot of errors in the controller logs "RPC error: rpc error: code = Unknown desc = received error deleting iscsi target - extent: 7 code: 400 body: {"__all__":["Warning: Target is in use"]}" (even though the pod and PVC are deleted).

**Comment by travisghansen** [comment]
@drewfurgiuele thanks for the interest! Based on the error it appears you're using iscsi? You may need to crank the log level up to `debug` and you will be able to see the exact commands that are getting executed etc to see where it's at in the process.

Where did the "csi driver not valid too" log message come from?

Regarding nfs there are configuration options which let you set the permissions on the dir server-side. I think the example does a chmod 777 so the pod should be able to write to the shares as whatever user the pod is running as.

The fact the target is in use is strange if nodes are not able to connect in the first place...are some of them working/attaching and others not? Did by some crazy chance you already have a target with the autogenerated name that's in use by something else entirely?

Generally if you could send over the details of your setup it will help. k8s disto, linux distro, helm values.yaml files (with secrets removed), and debug logs that are appropriate.

Thanks! I'm confident we can get you going cleanly.

**Comment by drewfurgiuele** [comment]
Thanks for the speedy reply.

I was able to dig a little deeper, and, now here's the error that seems to be random when I'm deploying applications:

MountVolume.MountDevice failed for volume "pvc-60cf43f5-03f7-4eb3-b862-f202cd283b60" : rpc error: code = Internal desc = {"code":19,"stdout":"Logging in to [iface: default, target: iqn.2005-10.org.freenas.ctl:csi-pvc-60cf43f5-03f7-4eb3-b862-f202cd283b60-clustera, portal: 192.168.2.13,3260] (multiple)\n","stderr":"iscsiadm: Could not login to [iface: default, target: iqn.2005-10.org.freenas.ctl:csi-pvc-60cf43f5-03f7-4eb3-b862-f202cd283b60-clustera, portal: 192.168.2.13,3260].\niscsiadm: initiator reported error (19 - encountered non-retryable iSCSI login failure)\niscsiadm: Could not log into all portals\n"}

But it's very strange because it can create other PV and PVCs just fine. Seems to be something I can't quite run down.

Here's my values file, for reference. passwords replaced with "password":

`csiDriver:
  name: "org.democratic-csi.iscsi"

storageClasses:
- name: freenas-iscsi-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4

    # if true, volumes created from other snapshots will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromSnapshots: "false"

    # if true, volumes created from other volumes will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromVolumes: "false"

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: freenas-iscsi-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

driver:
  config:
    driver: freenas-iscsi
    instance_id:
    httpConnection:
      protocol: http
      host: 192.168.2.13
      port: 80
      username: root
      password: password
      allowInsecure: true
    sshConnection:
      host: 192.168.2.13
      port: 22
      username: root
      password: password
    zfs:
      # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
      # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
      # standard volume naming overhead is 46 chars
      # datasetParentName should therefore be 17 chars or less
      datasetParentName: DataPool1
      detachedSnapshotsDatasetParentName: DataPool1
      # "" (inherit), lz4, gzip-9, etc
      zvolCompression: off
      # "" (inherit), on, off, verify
      zvolDedup: off
      zvolEnableReservation: true
      # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
      zvolBlocksize:
    iscsi:
      targetPortal: "192.168.2.13:3260"
      targetPortals: []
      # leave empty to omit usage of -I with iscsiadm
      interface:
      namePrefix: csi-
      nameSuffix: "-clustera"
      # add as many as needed
      targetGroups:
        # get the correct ID from the "portal" section in the UI
        - targetGroupPortalGroup: 1
          # get the correct ID from the "initiators" section in the UI
          targetGroupInitiatorGroup: 1
          # None, CHAP, or CHAP Mutual
          targetGroupAuthType: None
          # get the correct ID from the "Authorized Access" section of the UI
          # only required if using Chap
          targetGroupAuthGroup:

      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      # 512, 1024, 2048, or 4096,
      extentBlocksize: 512
      # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
      extentRpm: "5400"
      # 0-100 (0 == ignore)
      extentAvailThreshold: 0`

**Comment by travisghansen** [comment]
Ok config looks relatively sane (I’ll give suggestions after we resolve the core issue here).

So if I’m understanding all the assets are created properly on the server/freenas side and just when a node is trying to attach you’re getting the failures above? But for most pvcs it works fine?

Is it a specific node that’s producing the error? Is is that random as well?

You can turn on debug logging and then find the respective ‘node’ csi pod for the node where the pod is that’s trying to mount the pvc. You should see a pretty detailed picture of what the driver is doing/executing behind the scenes on the node itself. Ultimately you should see the login command attempt. You should he able to copy/paste the command from the debug output directly on the console of the node and observe what happens there. From there check the dmesg/iscsi daemon logs etc and see if anything useful shows up.

Lastly, do you happen to be running rke/rancher and also are you running any other storage classes that leverage iscsi? Depending on the combination of the above some weird stuff could be going on.

**Comment by drewfurgiuele** [comment]
A couple questions and I'm hoping we can put this to bed:

1.  It appears that the 2nd password should NOT have quotes around, it correct? That was just for a placeholder?
2. Where do I set the logging level? I don't see a setting for that in my values file

**Comment by travisghansen** [comment]
What 2nd password are you referring to? In the sshConnection block? If it is that it’s not a problem or you wouldn’t be getting where you’re at in the process.

The seconds is in the main values.yaml in the chart repo.

https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L71

And more importantly for you in this case:

https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L112

**Comment by drewfurgiuele** [comment]
Okay, so: What I'm noticing in the logs is something like this, from the different nodes:

This seems to happen randomly; sometimes when I try to just create one PV/PVC and sometimes after I create 10. There doesn't appear to be any common factors here. It is happening on any of my 3 nodes.

To level-set: I set up the nodes per the node-prep instructions.

What is also interesting is that when it fails, I'm seeing something interesting in my kubelet folder. The screen shot below shows this behavior mid-fail. One minute the directory is there, the next moment, it's gone. I did not delete anything manually.

<img width="1010" alt="Screen Shot 2020-09-22 at 9 01 16 AM" src="https://user-images.githubusercontent.com/2636722/93886294-3d89ad80-fcb3-11ea-8f5e-3f03014a816e.png">

Any advice as to what's happening here would be most beneficial

**Comment by travisghansen** [comment]
Have you been able to gather the logs from the ‘driver’ container of the daemonset with debug logging? Find the pod corresponding to the node giving problems and you should see extensive detail into what it’s doing (including possibly deleting that directory).

I think by looking at the path it’s the staging directory which means the driver may be getting unstage requests for some reason (which means it will umount and remove the staging dir).

**Comment by drewfurgiuele** [comment]
I tore down my cluster and started free on a new set of VMs and created a new cluster. I'm still getting this error. And what's driving me crazy is that it's sporadic.

Same error as before, on the node's dedicated pod:

```
error: handler error - driver: FreeNASDriver method: NodeStageVolume error: {"name":"GrpcError","code":2,"message":"hit timeout waiting for device node to appear: /dev/disk/by-path/ip-192.168.2.13:3260-iscsi-iqn.2005-10.org.freenas.ctl:csi-pvc-ea849a54-8569-45bc-b3a1-bf9d01249328-clustera-lun-0"}
```

In addition, seeing this command failing from the logging (again, on the same pod where the failed pod binding occurs):

```
info: new response - driver: FreeNASDriver method: NodeGetVolumeStats response: {"usage":[{"available":9910247424,"total":10501771264,"used":37875712,"unit":"BYTES"}]}
executing fileystem command: stat /dev/disk/by-path/ip-192.168.2.13:3260-iscsi-iqn.2005-10.org.freenas.ctl:csi-pvc-ea849a54-8569-45bc-b3a1-bf9d01249328-clustera-lun-0
failed to execute filesystem command: stat /dev/disk/by-path/ip-192.168.2.13:3260-iscsi-iqn.2005-10.org.freenas.ctl:csi-pvc-ea849a54-8569-45bc-b3a1-bf9d01249328-clustera-lun-0, response: {"code":1,"stdout":"","stderr":"stat: cannot stat '/dev/disk/by-path/ip-192.168.2.13:3260-iscsi-iqn.2005-10.org.freenas.ctl:csi-pvc-ea849a54-8569-45bc-b3a1-bf9d01249328-clustera-lun-0': No such file or directory\n"}
```

Again, I provisioned each node with the requirements. And some pods work fine, but I get some failures on different nodes at different times.

**Comment by travisghansen** [comment]
Pretty odd it works in some scenarios and not in others. You should see some iscsiadm commands getting executed just before. If you go directly to the node and rerun them do you get anything?

Does an appropriate session ever show up? `iscsiadm -m session`
Do you see a device node (`/dev/sd<foo>`) associated with it here? `iscsiadm -m session -P3`
Does `dmesg` show it actually creating the respective device node?
Are *all* the assets created appropriately in freenas? you should have a target, extent, and proper lun mapped and visible in the UI?

**Comment by drewfurgiuele** [comment]
Yes, I am seeing all the requirements in FreeNas; I can see the appropriately named volumes. For whatever reason, the VMs can't attach the mounts.

For what it's worth, this is on Ubuntu 18.04. The only thing I have not tried yet is rebuilding this on Centos 7, which I am going to do next to rule that out.

**Comment by travisghansen** [comment]
Yeah pretty strange stuff :( if you can get to the bottom of it and you’re comfortable maybe you can get me ssh access into the node when it’s in a bad state and we’ll see what we can find jointly.

**Comment by drewfurgiuele** [comment]
FWIW, a little more context while I continue to troubleshoot: the application I'm deploying needs about a dozen or s PVs. What I'm seeing is that sometimes the provisioner gets to 10, sometimes it gets to 2. It looks like it's doing what it needs to do, but the nodes are having a hard time mounting the paths. From a FreeNAS perspective, I've got a really basic setup: 1 portal, 1 initiator. I won't claim to be the world's biggest iSCSI genius, but should I create additional initiators to help solve this? Are there changes on the storage side I should confirm?

**Comment by travisghansen** [comment]
Shouldn’t need to afaik either (also don’t claim to an iscsi expert). When testing I'm pretty sure I did a hundred or so on a single node. More spread across 5 nodes. But maybe there’s something environment specific going on.

Does the server have other load/connections going on? Do you see anything on the logs/dmesg server side?

I have seen some weird stuff where connections would be queued or similar due to general resource exhaustion on the server..

**Comment by drewfurgiuele** [comment]
Update: I've rebuilt (and expanded) my cluster to a four node Centos7-based Kubernetes cluster. Still getting the same issue, but I'm seeing different errors now:

```
MountVolume.MountDevice failed for volume "pvc-15746323-b5f1-4c39-bf6b-d5eb723dfac7" : rpc error: code = Internal desc = {"code":19,"stdout":"Logging in to [iface: default, target: iqn.2005-10.org.freenas.ctl:csi-pvc-15746323-b5f1-4c39-bf6b-d5eb723dfac7-clustera, portal: 192.168.2.13,3260] (multiple)\n","stderr":"iscsiadm: Could not login to [iface: default, target: iqn.2005-10.org.freenas.ctl:csi-pvc-15746323-b5f1-4c39-bf6b-d5eb723dfac7-clustera, portal: 192.168.2.13,3260].\niscsiadm: initiator reported error (19 - encountered non-retryable iSCSI login failure)\niscsiadm: Could not log into all portals\n"}
```

I am still seeing errors that state (on the local pod, in this case node 02):

```
error: handler error - driver: FreeNASDriver method: NodeStageVolume error: {"name":"GrpcError","code":2,"message":"hit timeout waiting for device node to appear: /dev/disk/by-path/ip-192.168.2.13:3260-iscsi-iqn.2005-10.org.freenas.ctl:csi-pvc-3143de34-579d-4e48-8c17-f36d9b4ab827-clustera-lun-0"}
```

And now, also seeing:

```
MountVolume.MountDevice failed for volume "pvc-8080ef45-122e-4107-8510-8aa969b8af7f" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

... at the pod level of the requesting application.

I'm really at a loss here. The system seems to have no problem requesting one or two PVCs and it all works, but when the system is being asked to provision a dozen or so at a time, this falls down. I'm unsure if this is a Kubernetes or FreeNAS configuration.

I'd love to compare your FreeNAS configuration and look at mine (portal, initiators, etc).

**Comment by drewfurgiuele** [comment]
Furthermore, in the node logs:

```
xecuting iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-20224594-e39f-4d52-aa71-01ae59cd7fc2-clustera -p 192.168.2.13:3260 -o new
executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-20224594-e39f-4d52-aa71-01ae59cd7fc2-clustera -p 192.168.2.13:3260 -o update --name node.startup --value manual
executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-20224594-e39f-4d52-aa71-01ae59cd7fc2-clustera -p 192.168.2.13:3260 -l
executing fileystem command: stat /dev/disk/by-path/ip-192.168.2.13:3260-iscsi-iqn.2005-10.org.freenas.ctl:csi-pvc-20224594-e39f-4d52-aa71-01ae59cd7fc2-clustera-lun-0
failed to execute filesystem command: stat /dev/disk/by-path/ip-192.168.2.13:3260-iscsi-iqn.2005-10.org.freenas.ctl:csi-pvc-20224594-e39f-4d52-aa71-01ae59cd7fc2-clustera-lun-0, response: {"code":1,"stdout":"","stderr":"stat: cannot stat '/dev/disk/by-path/ip-192.168.2.13:3260-iscsi-iqn.2005-10.org.freenas.ctl:csi-pvc-20224594-e39f-4d52-aa71-01ae59cd7fc2-clustera-lun-0': No such file or directory\n"}
```

The FreeNAS part looks correct; it creates the volume, target, and extent just fine... but the nodes never get the target disk.

**Comment by travisghansen** [comment]
What do you get when running the iscsiadm commands directly?

I’m a bit at a loss as well here, I’m guessing it’s something extraneous to all of the above at this point. I’ve tested at much higher levels than 12 or whatever and the only bottleneck I hit was the performance of the freenas api. In that case I would slam it with a bunch of pvcs simultaneously and observe. Freenas can’t keep up everything is pretty robust and keeps trying so it all works itself out eventually. These are server side limits anyhow and not related to iscsi attachments which never seemed to choke really.

Are these bare metal or running in some kind of hypervisor?

I’m confident we can get to the bottom of it. Thanks for the patience working it out!

**Comment by drewfurgiuele** [comment]
When I run the commands directly on the nodes, nothing happens.

Machines are VMs. Target FreeNAS server is a separate, physical machine.

**Comment by drewfurgiuele** [comment]
Also, I'm willing to take this issue offline, as I was able to get a (much) older ISCSI provisioner working (but I eliminated FreeNAS from the equation too). Just let me know the best way to get in touch with you.

**Comment by travisghansen** [comment]
I’m on the truenas and k8s slacks or freenode irc. If you’ve got the patience I would like to work through it with you and get to the bottom of it :)

**Comment by drewfurgiuele** [comment]
Okay. I'll hop on there later tonight and send you a message. In the meantime, if you have any sample config files for "vanilla" ISCSI connections to a server running target-cli and targetd (a la like the old provisioners out there) that'd be helpful. I can get the ancient ones working just fine against a stock CentOS7 box.

**Comment by travisghansen** [comment]
OK, from the client perspective the few lines you included above should be all you need:

```
executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-28c821c6-7770-442e-80fa-0bea029f72f8-clustera -p 192.168.2.13:3260 -o new
executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-28c821c6-7770-442e-80fa-0bea029f72f8-clustera -p 192.168.2.13:3260 -o update --name node.startup --value manual
executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-28c821c6-7770-442e-80fa-0bea029f72f8-clustera -p 192.168.2.13:3260 -l
```

Replace the target and portal as appropriate.

Also note, I have a 'driver' in this project that works with ZoL servers using target-cli for example. So you could setup an ubuntu server with zfs and test this project against that to rule out any freenas specific issues. The node/attach process is 100% decoupled from the backend implementation so the exact same code-paths are used regardless of which backend/server you are using.

**Comment by travisghansen** [comment]
I think I may have run into this myself...on a node it was the 10th iscsi session, the first 9 went through fine. Is that what you saw?

It's pretty weird because the iscsi commands all execute properly, but the device/lun never shows up in the kernel. I'm not sure if there's some kind of limit there or not?

**Comment by drewfurgiuele** [comment]
Hey, sorry for the late reply. But yes, this is about what I'm seeing too. It's like... if you have a deployment that requests a large number of PVs, you hit this issue.

**Comment by travisghansen** [comment]
@drewfurgiuele I've been furiously coding trying to get a '1.0' of this project out the door and have found many many issues with the FreeNAS API unfortunately and any number of which could lead to this. However, the end result is I *believe* an invalid iscsi configuration file is being generated due to badly managed concurrency scenarios when using the API (ie: 10 http api requests coming in very rapidly).

I *think* what's happening has nothing to do with # of connections etc but rather the config file becomes invalid and we hit this issue. Further, I'm guessing if you were to detach one of the existing sessions and try to reconnect it would fail as well. In other words, once the configuration is 'bad', any connections will fail.

The config file is `/etc/ctl.conf` and you can test this by attempting:

```
/etc/rc.d/ctld restart
ctld not running? (check /var/run/ctld.pid).
Starting ctld.
ctld: error in configuration file at line 6 near '{': syntax error
ctld: configuration error; exiting
/etc/rc.d/ctld: WARNING: failed to start ctld
```

If I analyze the structure of the conf file it's pretty clear it's in a very messed up state.

**Comment by travisghansen** [comment]
example:

```
cat /etc/ctl.conf
portal-group "default" {
}
target "iqn.2011-03.lan.bitness.istgt:onegear.pvc-4a80757e-5e87-475d-826f-44fcc4719348" {
	alias "onegear.pvc-4a80757e-5e87-475d-826f-44fcc4719348"
portal-group "pg1" {
	tag "0x0001"
	discovery-filter "portal-name"
	discovery-auth-group "no-authentication"
	listen "0.0.0.0:3260"
	option "ha_shared" "on"
}
portal-group "pg2" {
	tag "0x0002"
	discovery-filter "portal-name"
	discovery-auth-group "no-authentication"
	listen "0.0.0.0:3261"
	option "ha_shared" "on"
}
	portal-group "pg1" "no-authentication"
	lun "0" "onegear.pvc-4a80757e-5e87-475d-826f-44fcc4719348"
}
```

Notice how the `portal-group` blocks are *inside* the `target` block.

**Comment by travisghansen** [comment]
Another potential cause of this is the API *not* properly adding the groups to the target. I have resolved it for v2 of the api but haven't looked into v1 yet. What version of FreeNAS/api have you been using?

**Comment by travisghansen** [comment]
I've just committed a massive update to the project bullet-proofing much of the strangeness with the API. I've also added some crude scripts here: https://github.com/democratic-csi/democratic-csi/tree/master/contrib

Which attempt to mitigate the issue but running them on the server as 'daemons' and continually cleaning stuff up if it gets messy.

I'd wait for the new `latest` images to finish building and then redeploy with the latest version of the chart (0.6.0) and see if things behave any better for you (also install/run one of the scripts above). With all the new code and scripts above I have been able to create many new volumes etc and everything ends up reaching the desired state.

**Comment by travisghansen** [comment]
- https://jira.ixsystems.com/browse/NAS-108520
- https://jira.ixsystems.com/browse/NAS-108521
- https://jira.ixsystems.com/browse/NAS-108522

Any/all of the above could have resulted in the failure scenario. I've got work-arounds for all of them now.
