### ISSUE TITLE
freenas-api-nfs limited to nfsv3 on SCALE

### ISSUE THREAD

**Issue by ishioni** [democratic-csi/democratic-csi#123]
Because of the way SCALE creates NFS shares as of now, the default PseudoFS path of a share is not /$FULLPATH but /$DIRNAME where $DIRNAME is the name of the directory being shared. When trying to pass in mount options for vers=4, the client silently fails and downgrades to v3. 

This can be remedied for now by setting the alias to the full path of the share, which directly translated to the Pseudo= directive inside of ganesha.conf

More info on this in [NAS-112558](https://jira.ixsystems.com/browse/NAS-112558)

**Comment by travisghansen** [comment]
Interesting, we'll need to look into this. This could be quite detrimental to folks migrating from CORE.

**Comment by ishioni** [comment]
@travisghansen A quick fix would be to add
```
"aliases": [properties.mountpoint.value],
```

here https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/freenas/api.js#L242

**Comment by travisghansen** [comment]
Right. Can you send over what the mount commands must be with ganesha nfs4 vs what they were with core for the same share? ie: an example of what used to work and what doesn’t work now.

**Comment by ishioni** [comment]
I can't say anything for Core - I've never used it, and have no way to run it atm

**Comment by travisghansen** [comment]
Yeah thanks for looking into it! I'll bring this up with ix and see if we can blanket solve the issue without delving into `aliases` usage to make it behave more like CORE by default.

**Comment by travisghansen** [comment]
Ok. Most folks I know have very little good to say about v4. In any case, can you try with the latest scale nightly? I think a fix should be in place there.

**Comment by ishioni** [comment]
I only have the one machine to test this on, and I'm hesitant to boot up nightly code on it. I'll wait for the next point release which should drop soon? I saw the bugfix on github and it should be good from what I saw

**Comment by travisghansen** [comment]
With the rc out can you give this a try again?

**Comment by ishioni** [comment]
Yeah, it works now. However ganesha immediately decided to error out because it isn't as flexible in reloading as iX would like it. A restart helped, and the share mounted nicely with vers=4.2

Too bad the performance isn't nearly as I'd like it, and with ganesha being a very volatile component for now, I'll stick to iscsi
