### ISSUE TITLE
iSCSI Login

### ISSUE THREAD

**Issue by gregod-com** [democratic-csi/democratic-csi#13]
This project is awesome!
I just got the provisioner up and running and all looks good. I now wanted to test if ISCSI with authentication also works but I don't get where in the helm values I should put the credentials.
So overall the provisioner can talk to freenas, creates a pvc but at the final step when mounting the disk to a pod I get the following error:

`
FailedMount | MountVolume.MountDevice failed for volume [...] Could not login to [iface: default, target: iqn.2005-10.org.freenas.ctl:csi-pvc-111c66af-9fb0-4ad8-b9a5-2efbb4bda2f2-clustera, portal: [...]].\niscsiadm: initiator reported error (24 - iSCSI login failed due to authorization failure)\niscsiadm: Could not log into all portals\n"}
`
Should this already be implemented?
If not, a reference to a k8s secret would we awesome.

Thanks for the great work, I've been searching for this solution for months!

**Comment by gregod-com** [comment]
nevermind, I just figured out that I have to set the authentication on the node in /etc/iscsi/iscsid.conf

**Comment by travisghansen** [comment]
Hey! Thanks for the good vibes :)

It actually should be a secret and I would love if you could test it out and let me know if this works as designed.

Basically in the chart look for the `node-stage-secret:` block and add the below as keys as appropriate.
```
node-db.node.session.auth.authmethod: CHAP
node-db.node.session.auth.username: foo
node-db.node.session.auth.password: bar

# if doing mutual CHAP
node-db.node.session.auth.username_in: baz
node-db.node.session.auth.password_in: bar
```

The way `democratic-csi` is implemented is you can add whatever arbitrary 'DB' values you want to the iscsi entry if you put the respective key name in the `node-stage-secret:` with the `node-db.` prefix in there.

So for testing, I'd love if you could revert the global settings you made to the iscsi config files and try out the above :) It hasn't received much testing unfortunately and it's not documented :(

**Comment by gregod-com** [comment]
hey @travisghansen, 
thanks for the super fast reply! I just tested the intended way as you described and it just worked right away. Awesome!

Since you might be keeping track of supported environments here are my specs:

running everything on one bare metal server:
hypervisor `esxi 7.0` runs `FreeNAS` and 3 `K3OS` VMs
k8s distribution is `k3s v1.17.5+k3s1`

Again, thanks for this project! It just eliminates a whole bunch of problems for my setups.
Next I'll check out the snapshot implementation and open another issue if I get into trouble.

**Comment by travisghansen** [comment]
Yeah awesome! Thanks for the info. If you don’t mind send over your scrubbed config so I can review as well. I’ve bumped into situations where things haven’t been configured in an ideal manner because I haven’t documented deeply enough so I like to see what people are doing with the configs.
