### ISSUE TITLE
Set default value for httpConnection.protocol

### ISSUE THREAD

**Issue by Boltovnya** [democratic-csi/democratic-csi#132]
Currently httpConnectoin.protocol does not have a default value and if not set, results in a malformed URI:

`rpc error: code = Internal desc = Error: Invalid URI "//[host]:[port]/api/v2.0/iscsi/global"`

https://github.com/democratic-csi/democratic-csi/blob/f364d970f3a7eb3db17e6b631d135aa67f5eaff4/src/driver/freenas/http/index.js#L18

I suggest perhaps either omitting this value in favour of a `httpConnection.https` boolean, or setting a default value of `http`.

**Comment by travisghansen** [comment]
Made it more robust via this commit here: https://github.com/democratic-csi/democratic-csi/commit/9f690e7daf69c884ea31a7dc2cfd46604066e2df

I'll make a new snapshot in the next day or so and close this down.

Thanks!

**Comment by travisghansen** [comment]
Released in `v1.4.3`.
