### ISSUE TITLE
ssh keys and nfs-democratic-csi-node pods stuck at container creation

### ISSUE THREAD

**Issue by simonlock** [democratic-csi/democratic-csi#133]
I was excited to find this excellent project and would really like to get it working.
I'm running a single node cluster using minikube running on Ubuntu 21.10 with TrueNAS-12.0-U6.1. for storage. I'm currently struggling to get this going. I'm focussing initial only on nfs storage but hope to move also onto iscsi later.

My initial problem was trying to include an ssh private key within the freenas-nfs.yaml file. No combinations of yaml formatting or key types I generated appeared to work. When attempting to use ssh keys, instead of username and password, the zfs-nfs-democratic-csi-controller pods would always error and fail and then enter a stuck in a container recreating loop.

However, (for now) I've allowed root ssh login using password and the zfs-nfs-democratic-csi-controller pods start successfully (4/4).

Is there a supported ssh key-type e.g ed25519 that is supported? I even tried generating an RSA key but that also failed and was reported as being unsupported.

Now I'm facing another problem and this time with the zfs-nfs-democratic-csi-node pods which are stuck at a ContainerCreating stage (0/3). The only log data I can obtain from these pods is: 
"csi-driver" in pod "zfs-nfs-democratic-csi-node-xxxx" is waiting to start: ContainerCreating"

Is there a way for me to obtain logs to help diagnose my problem with the zfs-nfs-democratic-csi-node(s)? I'd really like to get this working. Any help you might provide would be very much appreciated.

Thanks in advance.

**Comment by simonlock** [comment]
kubectl get all -n democratic-csi

NAME                                                   READY   STATUS              RESTARTS   AGE
pod/zfs-nfs-democratic-csi-controller-b48565cc-jsk44   4/4     Running             0          61m
pod/zfs-nfs-democratic-csi-node-ghltx                  0/3     ContainerCreating   0          60m

NAME                                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/zfs-nfs-democratic-csi-node   1         1         0       1            0           <none>          62m

NAME                                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/zfs-nfs-democratic-csi-controller   1/1     1            1           62m

NAME                                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/zfs-nfs-democratic-csi-controller-57b8546c78   0         0         0       62m
replicaset.apps/zfs-nfs-democratic-csi-controller-b48565cc     1         1         1       61m

**Comment by jakeschurch** [comment]
> My initial problem was trying to include an ssh private key within the freenas-nfs.yaml file. No combinations of yaml formatting or key types I generated appeared to work.

for Truenas yaml I was able to use:
```yaml
driver:
  config:
     sshConnection: |
       ${privateKey}
```

---

> When attempting to use ssh keys, instead of username and password, the zfs-nfs-democratic-csi-controller pods would always error and fail and then enter a stuck in a container recreating loop.

hmmm. are you able to get into your truenas box manually with the provided ssh key? Are you able to verify that the ssh key is an authorized key? You may also want to check your sshd service config + service status.

**Comment by travisghansen** [comment]
The syntax mentioned above should work for the private key yes. Regarding the pods I think I'll need you to send over the `kubectl describe` output and we'll see what's holding it up.

**Comment by simonlock** [comment]
Thank you both for such a prompt reply.

@jakeschurch  I can log in to TrueNAS from a terminal using all the key combinations I've tried.

I had also tried using the environment variable method.

export privatekey=$(cat ./id_ed25519)
echo $privatekey

then in freenas-nfs.yaml

    sshConnection:
      host: 172.16.28.15
      port: 22
      username: root
      # use either password or key
      #password: xxx
      privateKey: |
        ${privatekey}

Each attempt to use a private key has failed me so far.

Do you know if all key types are supported?

@travisghansen thanks for your suggestion to describe the pods' output. This really helped and showed that the issue was related to the HostPath.

It appears that Minikube must use a standard HostPath after all.

Removing the setting "--set node.kubeletHostPath" and simply using

helm upgrade \
--install \
--create-namespace \
--values freenas-nfs.yaml \
--namespace democratic-csi \
zfs-nfs democratic-csi/democratic-csi

and both pods then started up.

kubectl -n democratic-csi get all

 NAME                                                   READY   STATUS    RESTARTS   AGE
pod/zfs-nfs-democratic-csi-controller-b48565cc-hsb8z   4/4     Running   0          12m
pod/zfs-nfs-democratic-csi-node-hvlpc                  3/3     Running   0          12m

NAME                                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/zfs-nfs-democratic-csi-node   1         1         1       1            1           <none>          64m

NAME                                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/zfs-nfs-democratic-csi-controller   1/1     1            1           64m

NAME                                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/zfs-nfs-democratic-csi-controller-6c849c9b7f   0         0         0       20m
replicaset.apps/zfs-nfs-democratic-csi-controller-755c6879dc   0         0         0       16m
replicaset.apps/zfs-nfs-democratic-csi-controller-7fc95ff568   0         0         0       31m
replicaset.apps/zfs-nfs-democratic-csi-controller-98995c446    0         0         0       26m
replicaset.apps/zfs-nfs-democratic-csi-controller-b48565cc     1         1         1       64m

My pod describe files using both a private key (which fails to start) and a password are attached.


Kind Regards

Simon

[with_key.txt](https://github.com/democratic-csi/democratic-csi/files/7575599/with_key.txt)
[with_password.txt](https://github.com/democratic-csi/democratic-csi/files/7575600/with_password.txt)

**Comment by travisghansen** [comment]
So am I understanding correctly that the node pods are currently working and the controller is effectively in a crash loop backoff?

Also if you use password the controller works so only the ssh key configuration is failing?

**Comment by simonlock** [comment]
Hi @travisghansen yes that's correct using a key for the ssh connection causes the controller to enter a CrashLoopBackOff loop and continually try to restart. But when using a password for the ssh connection the pods start up correctly (having removed --set node.kubeletHostPath) from the helm upgrade command.

**Comment by travisghansen** [comment]
Can you send over an example of the values file you use when attempting with a key? I want to check the syntax pretty closely so cleanse the file but try to leave the key header/footer or something so I can get a pretty close representation of what the actual values file is formatted like.

**Comment by simonlock** [comment]
Sure I will do that.  Thanks. I'm actually using the environment variable approach currently, ${privatekey}, but I can generate a similar (throw away private key) and enter it into the file I send.

**Comment by simonlock** [comment]
Hi @travisghansen

Please find a values file attached containing an example private key formatted in yaml.

[freenas-nfs-key-example.yml.txt](https://github.com/democratic-csi/democratic-csi/files/7576539/freenas-nfs-key-example.yml.txt)

**Comment by travisghansen** [comment]
Ok I’ll take a look. Make note that env vars don’t actually work nativity in helm values files so if you’re literally trying to use an env var in the file it’s not doing what think it’s doing.

**Comment by travisghansen** [comment]
Yeah the syntax of the file (without the env var) seems legit to me. Do you see any logs of the driver or the ssh daemon on the nas that show what the exact failure is?

**Comment by simonlock** [comment]
Strangely enough, I just tried again using an ssh key in the same format as I sent to you and it worked. I can't explain what might have changed. Thank you for creating such a great project and for your excellent support.

**Comment by travisghansen** [comment]
Awesome glad it’s working now!
