### ISSUE TITLE
Possible for templated naming conventions for NFS shares?

### ISSUE THREAD

**Issue by jakeschurch** [democratic-csi/democratic-csi#134]
First - thank you so much for your work - love using your drivers to create PVC/PVs on my SAN / NAS.

I did a quick grep through the repo and AFAICT it seemed like there is only code to allow ISCSI / SMB name templating. If so, is there any reason why this is not allowed for NFS shares?

**Comment by jakeschurch** [comment]
not sure if this is what i'm looking for... https://github.com/democratic-csi/democratic-csi/blob/f364d970f3a7eb3db17e6b631d135aa67f5eaff4/examples/zfs-generic-nfs.yaml#L55

**Comment by travisghansen** [comment]
Thanks! Yeah for iscsi/smb the template is not directly correlated to the associated `zvol` or `dataset` (ie: I still have complete control over the naming of the underlying `zfs` asset). With nfs there's a 1:1 mapping between the share name and the `zfs` asset leaving the driver in a less controlling state (and killing some assumptions that are made by the driver internally).

Which driver are you using and maybe I can guide you to setting a comment or something of that nature?

**Comment by travisghansen** [comment]
> not sure if this is what i'm looking for...
> 
> https://github.com/democratic-csi/democratic-csi/blob/f364d970f3a7eb3db17e6b631d135aa67f5eaff4/examples/zfs-generic-nfs.yaml#L55

Not really what you're after. Some OSes use that property to turn on nfs sharing (ie: nexenta or opensolaris or something).

**Comment by jakeschurch** [comment]
currently using the zfs-generic-{iscsi,nfs} drivers

- i think if i could control the zvol / dataset name that would really be all i need

**Comment by travisghansen** [comment]
There are assumptions built-in to the driver that make this not feasible (at least as currently designed). In short it was a deliberate/conscious decision to not allow that :(

**Comment by jakeschurch** [comment]
ah I understand. Would it be fair to expect issues with data persistence if k8s or csi driver/s goes down, but data still exists in dataset / zvol? A new share would be created / picked up, yes? (Perhaps not with iscsi?)

**Comment by travisghansen** [comment]
I'm not sure I understand the question? Can you help me understand the hypothetical a bit better?

**Comment by jakeschurch** [comment]
Absolutely.

assumptions:

- NFS pvc is created by csi nfs driver - dataset name is `pvc-709323423489` mounted at `/mnt/pvc-709323423489`
- this dataset is used to store end-user personal data (for example) and is connected to data dir pod running google drive clone (i.e. nextcloud)
- end-user stores personal data over a week period
- k8s cluster is restarted, meaning driver loses connectivity to backing store, but dataset still exists after restart (since on seperate device from k8s cluster node/s).

Unknowns:

- when driver comes back online, would it be able to re-mount the same dataset with pvc name `pvc-709323423489` back into a nextcloud instance for the same end-user? 

^ My assumption is not based off of what you mentioned above.

**Comment by jakeschurch** [comment]
this problem (IIUC) applies to iscsi since targetcli maps block storage to luns

**Comment by jakeschurch** [comment]
I am unfamiliar with driver lifecycle model which is why I'm asking

**Comment by travisghansen** [comment]
If I understand the scenario correctly everything should recover nicely. Some notes:

- the share itself would never get removed/deleted at any time
- the dataset also would (perhaps obviously) not get deleted
- the 'driver' itself can be restarted/killed at any time without impacting running workloads (ie: upgrades of the driver are fine and will have no impact on running pods where storage is in use)
- if the 'driver' is stopped/malfunctioning only newly created/deleted PVCs will fail and/or mount/unmount operations for **newly** created/deleted pods
- when a k8s node is restarted/drained the workload(s) / pod(s) should hypothetically migrate to other nodes and things should just start where they left off
- if nodes die uncleanly (ie: aren't drained/cordoned) then (assuming k8s is behaving correctly etc) eventually to brain dead pod will be removed and the workload should shuffle to another node and come up cleanly
- with iscsi it all is a bit more complicated as you need to ensure a lun isn't mounted by multiple nodes simultaneously (or at least actively being written to anyway), and this logic is managed/enforced by k8s itself (vs the drivers) so you should be covered on that front as well

The above applies generally to any/all csi drivers unless something really abnormal is going on.

**Comment by jakeschurch** [comment]
notes make sense - so in my hypothetical - the driver can persist / know what PVCs were mapped to what workload?

**Comment by jakeschurch** [comment]
I also can't seem to find where / how PVCs get named in the codebase

**Comment by travisghansen** [comment]
I'm not sure what you mean by shut down. If the cluster is destroyed entirely (ie: etcd dead etc) then critical data would be lost. However, if you simply shut down all cluster nodes simultaneously and then bring them back up all will be well (assuming the cluster is in a generally healthy state). The relevant data is stored in the `PV` objects essentially.

So yes, the driver and k8s will know what PVCs/PVs are associated to what workloads/pods and should recover nicely.

- https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs-ssh/index.js#L598

**Comment by jakeschurch** [comment]
shut down as in power off - I tested this with nfs (have both org.democratic-csi.iscsi / nfs provisioners deployed):

output from `zfs list` contains 3 PVs that were created by NFS driver 
![image](https://user-images.githubusercontent.com/12192670/142743946-34228c59-ccda-4a85-9c02-b7790322d95b.png)

-- but none of these are shown in `kubectl get pv` output.

The volumes "persist" on shutdown but deployed PVs are not able to be remapped to new (non-driver) pod (for NFS) since there is no persistent mapping and there is no ability for static naming conventions. Seeming that they're not truly persistent volumes since they can't be remapped if anything goes wrong with cluster (like power-off).

You get this for free with ISCSI because targetcli provides persistent mappings of ISCSI luns to block backstores which is great.

Is there any reason why this would be a bad idea? Why not have "truly" persistent NFS volumes as you would with ISCSI?

**Comment by travisghansen** [comment]
I'm sorry, I'm still not following the example. NFS volumes will for sure be persistent across reboots of either cluster nodes and/or the NAS.

**Comment by jakeschurch** [comment]
Data persisted in nfs volumes that are connected to external storage  will not be accessible/usable after cluster outage, you state that PVs are torn down if anything goes awry but that does not seem to entirely be the case via screenshot. 

It seems like I can mount externally created paths via nfs in default k8s volume specs, which solves my use case. I'll just use the driver for dynamic Vols.

Thanks for your help 🙂

**Comment by travisghansen** [comment]
Yeah sorry having a hard time following the scenario :(

The driver can be deployed in such a fashion as to work with manually provisioned (preexisting) shares for nfs, iscsi, smb, etc
