### ISSUE TITLE
Error on controller pod. 

### ISSUE THREAD

**Issue by Tony-The-Developer** [democratic-csi/democratic-csi#135]
csi-provisioner.go:193] CSI driver probe failed: rpc error: code = Internal desc = Error: Timed out while waiting for handshake

**Comment by travisghansen** [comment]
Looks like an issue with the ssh connection to the NAS?

**Comment by Tony-The-Developer** [comment]
I can ssh on my pc. Also, It works with my old one. Just installed a new install of truenas. Anything I can try.

**Comment by Tony-The-Developer** [comment]
NFS, SSH they are all on and configured.

**Comment by travisghansen** [comment]
Are you using password or key? Are you using root?

**Comment by Tony-The-Developer** [comment]
Root and password. Set the ssh type to sh.

**Comment by travisghansen** [comment]
I sometimes forget to set the `Log in as Root with Password` in the ssh service settings..

**Comment by Tony-The-Developer** [comment]
Its set to on.

**Comment by Tony-The-Developer** [comment]
Does truenas have a log. If there are any attempts.

**Comment by travisghansen** [comment]
`tail -f /var/log/auth.log`

**Comment by Tony-The-Developer** [comment]
![image](https://user-images.githubusercontent.com/68414482/142974772-fda29239-d900-43a1-9821-e45c0bd58d26.png)
Strange

Can we create a different root user and try.

**Comment by travisghansen** [comment]
Given the nature of the error message I'm guessing at this point there's something lower-level going on. I would ssh to the node running the controller pod and see if you can access the NAS ssh port using telnet or similar from there as a baseline.

**Comment by Tony-The-Developer** [comment]
I can ping the only nas but not the new one. 
![image](https://user-images.githubusercontent.com/68414482/142975190-92b92c01-b3c6-426c-85ac-cb016ee38ee6.png)

**Comment by Tony-The-Developer** [comment]
Randomly started working. Thanks
