### ISSUE TITLE
behavior of freenas-iscsi with a pool name greater than 15 characters

### ISSUE THREAD

**Issue by prometheanfire** [democratic-csi/democratic-csi#142]
Hi, I'd just like to confirm that if I have a pool name of `longish-pool-name` that will mean that no datasets can be created, even single character ones.

length counted by `echo -n 'a-long-pool-name' | wc -c` = `16`.
this will have a dataset character length total of 18
`echo -n 'a-long-pool-name/d' | wc -c` = `18`

This violates the `datasetParentName should therefore be 17 chars or less` comment

Does this mean the `freenas-iscsi` driver cannot be used with that pool?

**Comment by travisghansen** [comment]
Hello my friend of gentoo days of yore! Welcome :)

Are you using scale or core (the limit only really applies to core, and should be resolved when core 13 becomes available).

The limit is a bsd <= 12 issue and it’s that the total zvol path cannot be greater than 63 chars as I recall (including `zvol/`)

Are you intending to use this with k8s or something else? That’s really the crux of it. k8s will not use the pvc name but rather the autogenerated pv name with uuid (ie: there is no such thing as a single character volume in practical terms). You *can* however get around this limitation in k8s by tweaking one of the args to some k8s bits that will limit the size of the guids used.

- https://github.com/democratic-csi/democratic-csi/issues/54
- https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs-ssh/index.js#L689
- https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs-ssh/index.js#L398

**Comment by prometheanfire** [comment]
* using core right now (12.x)
* playing with k8s (k3s)

thanks for the link about uuid length, I tried searching but couldn't find it.

**Comment by travisghansen** [comment]
I think the info in #54 will be your friend. I would highly recommend not setting the value of `datasetParentName` to just the name of the pool. Add something to keep the namespacing sane like `<pool>/k8s/v`

**Comment by prometheanfire** [comment]
Ya, that's my preference as well.  Do you think it's worth documenting the `--volume-name-uuid-length` workaround?

**Comment by travisghansen** [comment]
I should probably put the link to that issue in the example yaml yes. I can get it added.

**Comment by travisghansen** [comment]
This will be documented in the next released version.
