### ISSUE TITLE
shareHost value for nfs should allow an array

### ISSUE THREAD

**Issue by prometheanfire** [democratic-csi/democratic-csi#143]
At least, from what I can tell it only allows a single IP.  I noticed this when I used my primary storage network and my secondary network connections timed out (I have nfs listening on more than one IP).

**Comment by travisghansen** [comment]
Is it possible to provide multiple targets in a single mount command?

**Comment by prometheanfire** [comment]
Don't think so.

Maybe the value is used for both the mount command and setting up the nfs server on the truenas side.  the mount command as it exists now is fine, the problem is that the nfs service on truenas was reset to that same single mount IP (from more than one IP).

**Comment by travisghansen** [comment]
I’d have a look more closely to see what’s allowed on the TrueNAS side. The behavior right now is doing what server side?

On the client side are you wanting it to just pick an ip at random as a sort of load balancing effort?

**Comment by travisghansen** [comment]
That value currently is only used on the client/mount side of the equation FYI.

**Comment by prometheanfire** [comment]
From what I can tell, shareHost is passed in 
https://github.com/democratic-csi/democratic-csi/blob/8913dfb58ef6c52967f9535a0fd423d12e7dcee4/src/driver/freenas/api.js#L353
to this I think.
https://github.com/democratic-csi/democratic-csi/blob/8913dfb58ef6c52967f9535a0fd423d12e7dcee4/src/driver/freenas/api.js#L2733

though, I really don't know javascript...

it's also mentioned here in the ssh driver
https://github.com/democratic-csi/democratic-csi/blob/911541fd06574a91747b5a7744ae5df408b25fba/src/driver/freenas/ssh.js#L349

**Comment by travisghansen** [comment]
Yeah that impacts strictly client side behavior in essence.

**Comment by prometheanfire** [comment]
gonna close this for now, assuming it's my fault (always a safe assumption)
