### ISSUE TITLE
csi-controller crashing

### ISSUE THREAD

**Issue by ashisha2307** [democratic-csi/democratic-csi#145]
I am trying to get iscsi to work with openshift version 4.9.11 and truenas version is 12.2-RELEASE-p11. In my case, the controller pod is crashing with an error message

I0127 18:13:45.499913       1 connection.go:187] GRPC error: rpc error: code = Internal desc = TypeError: Cannot read property 'datasetParentName' of undefined
E0127 18:13:45.500134       1 csi-provisioner.go:196] CSI driver probe failed: rpc error: code = Internal desc = TypeError: Cannot read property 'datasetParentName' of undefined

I can SSH to the truenas from the pod running inside the OCP

It would be great if you can help me

**Comment by ashisha2307** [comment]
![Screenshot 2022-01-27 at 1 11 51 PM](https://user-images.githubusercontent.com/14177819/151425672-104e4e07-75f0-4509-a70d-75d7ddff5003.png)

**Comment by ashisha2307** [comment]
[freenas-iscsi.txt](https://github.com/democratic-csi/democratic-csi/files/7953130/freenas-iscsi.txt)

**Comment by ashisha2307** [comment]
Found out the issue it was spacing and overlapping name.
Closing this issue

**Comment by travisghansen** [comment]
Enjoy!
