### ISSUE TITLE
When snapshotting don't assume pvs are from democratic-csi

### ISSUE THREAD

**Issue by anthr76** [democratic-csi/democratic-csi#150]
I'm trying to get a snapshot like so:

```yaml
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: hass-test
  namespace: home
spec:
  volumeSnapshotClassName: zfs-nfs
  source:
    persistentVolumeClaimName: home-assistant-config-v1
```

The PVC and PV are provisioned by another CSI (rook-ceph)

Thought I'm trying to create a snapshot with the democratic-csi for durable storage backups.

Logs show:

```
"handler error - driver: ControllerZfsGenericDriver method: CreateSnapshot error: {\"name\":\"GrpcError\",\"code\":9,\"message\":\"snapshot source_volume_id 0001-0009-rook-ceph-0000000000000001-506e42e1-2f70-11ec-bcfa-d628f94091cc does not exist\"}"
I0213 16:46:48.641316       1 snapshot_controller.go:325] createSnapshotWrapper: CreateSnapshot for content snapcontent-7218ccf1-66c6-4dff-8e70-2496272a0002 returned error: rpc error: code = FailedPrecondition desc = snapshot source_volume_id 0001-0009-rook-ceph-0000000000000001-506e42e1-2f70-11ec-bcfa-d628f94091cc does not exist
Failed to check and update snapshot content: failed to take snapshot of the volume 0001-0009-rook-ceph-0000000000000001-506e42e1-2f70-11ec-bcfa-d628f94091cc: "rpc error: code = FailedPrecondition desc = snapshot source_volume_id 0001-0009-rook-ceph-0000000000000001-506e42e1-2f70-11ec-bcfa-d628f94091cc does not exist"
```

This sounds like to me democratic-csi is making the assumption it owns the PV to the PVC. Is it possible to do something like this? I'd like to use rook-ceph as my PV provider but use democratic-csi for my snapshot provider

**Comment by travisghansen** [comment]
The assumption is indeed that snapshotting belongs not only to democratic csi but a corresponding deployment of democratic csi (similar assumptions are made by most of the other csi drivers). The way snapshots are made is tied very deeply into the storage system so it not feasible with the current drivers to achieve what you are after.

I think kasten or valero are probably better options for your scenario/constraints atm.

**Comment by anthr76** [comment]
That is interesting. I was under the assumption a csi driver should be able to take snapshots of any csi driver. As ... it *should*? be abstracted at that point. Velero with csi-snapshots is essentially a snapshot taker on a cron which does nothing more different then fairwinds-ops/gemini. Kasten seems to be doing what I'm trying to achieve but with an opensource FOSS project. :)

They take snapshots from existing csi-drivers into their csidrivers and move it to durable storage. Rook on it's own can take snapshots but can't leave the rook cluster.

**Comment by travisghansen** [comment]
`velero` can manage snapshots but will also take backups of volumes using the 'restic' feature as well. The general idea is to send the data to some blob storage location (external to the cluster/storage system). I'm suggesting for your use-case to use the restic feature vs the snapshot/csi integration/feature.
