### ISSUE TITLE
Retain vs Delete confusion

### ISSUE THREAD

**Issue by bjornbouetsmith** [democratic-csi/democratic-csi#154]
Hi,

When I set up my values.yml like this:

~~~yaml
storageClasses:
- name: truenas-nfs
  defaultClass: true
  reclaimPolicy: Delete
~~~

Then when I remove a PVC, then both the PV and the actual dataset inside truenas gets deleted - as expected.

But if I set up my values.yml like this:

~~~yaml
storageClasses:
- name: truenas-nfs
  defaultClass: true
  reclaimPolicy: Retain
~~~

Then obviously when I remove a PVC- the PV stays behind, since that is what the reclaim policy should do I guess.

If I then manually delete the PV, then the dataset stays on the truenas server - and I would have expected that if I delete a PV created by the driver that it then would do a `zfs destroy` on that that dataset.

Is that fully expected that when using retain, that you also have to manually delete the dataset on the zfs server?

For brevity I am using the `freenas-nfs`driver.

Thanks

**Comment by travisghansen** [comment]
I think it should get deleted yes, but I'll ask. In either case, it's not the driver that makes this decision, it's the container orchestrator (ie: k8s) which handles this aspect...the driver just does what it's told.

You may exec into the controller container and use this: https://github.com/democratic-csi/democratic-csi/blob/master/bin/k8s-csi-cleaner to force the issue should it ever be needed.

**Comment by travisghansen** [comment]
Per k8s team:

```
[thansen](https://app.slack.com/team/UBLE7E9N1)  [10:31 AM](https://kubernetes.slack.com/archives/C8EJ01Z46/p1645637464178179)
if reclaim policy is Retain and PV is deleted should that invoke DeleteVolume?

[msau42](https://app.slack.com/team/U3CB0SFMF)  [11:05 AM](https://kubernetes.slack.com/archives/C8EJ01Z46/p1645639503920749)
nope
```

**Comment by bjornbouetsmith** [comment]
> Per k8s team:
> 
> ```
> [thansen](https://app.slack.com/team/UBLE7E9N1)  [10:31 AM](https://kubernetes.slack.com/archives/C8EJ01Z46/p1645637464178179)
> if reclaim policy is Retain and PV is deleted should that invoke DeleteVolume?
> 
> [msau42](https://app.slack.com/team/U3CB0SFMF)  [11:05 AM](https://kubernetes.slack.com/archives/C8EJ01Z46/p1645639503920749)
> nope
> ```
Well that answers the question then :-) Thanks
