### ISSUE TITLE
Consolidate and improve Nomad-related documentation

### ISSUE THREAD

**Issue by scaleoutsean** [democratic-csi/democratic-csi#168]
It looks like Nomad-related information is almost correct, so I propose to improve some details after Nomad v1.3.0 comes out (by then things should largely settle).

### General points:

Nomad info in the Wiki and repo (examples) are inconsistent. It may be better to have content info in just one location (repo) to save people time from trying examples that can't work.

There are also some inaccuracies in both the Wiki and repo examples for Nomad, but looking at the progress being made in other Nomad-related issues, it's likely there will be known good configs that can be used to update repo examples.

### Some specific issues with the repo examples:

[This](https://github.com/democratic-csi/democratic-csi/blob/6f26022680435ea4bbce18d93c71b0dcf0b035b8/docs/Nomad/examples/democratic-csi-iscsi-controller.hcl#L26) syntax is confusing. If `config` is the exact string that should be there, then that's fine, but it looks like `# config...` (i.e. insert your config) is what we're supposed to add in there.

[Here](https://github.com/democratic-csi/democratic-csi/blob/6f26022680435ea4bbce18d93c71b0dcf0b035b8/docs/Nomad/examples/job-mysql.hcl#L15) it looks like file system access is suggested instead of block device ([Nomad docs](https://www.nomadproject.io/docs/job-specification/volume#attachment_mode)).

For D-CSI users who want to use `node-manual` (such as myself), repo's main README.md is short on details for K8s and Nomad examples don't show how [K8s PVs](https://github.com/democratic-csi/democratic-csi/blob/6f26022680435ea4bbce18d93c71b0dcf0b035b8/examples/node-manual-iscsi-pv.yaml) translate into Nomad-style configuration and volume claims. As an example, I got to the point where controller & node are running (`node-manual`  mode) and an iSCSI volume is visible to the Nomad client, but even though I "volume register"-ed this existing volume in Nomad as `dcsi-267` it's not clear to me how Nomad or Democratic-CSI can link that volume to an iSCSI Target visible to the client/server (I use singleton Nomad cluster) with `node-manual` setup. I figure I need this iSCSI target info inserted to either controller or node (Nomad) job file, but I'm not sure where and how.

I may submit a PR with some examples if I figure this out, but I'm new to this CSI driver.

**Comment by travisghansen** [comment]
Any help with Nomad docs is extremely appreciated! There are definitely some items that need improvement.

**Comment by scaleoutsean** [comment]
Unfortunately,  `volume-manual` and `local-hostpath` are two least documented modes, so it's a steep learning curve for now. `local-hostpath` seems easier as device discovery, mount and format can be done manually, but there are no examples.

[node-manual](https://github.com/democratic-csi/democratic-csi/blob/6f26022680435ea4bbce18d93c71b0dcf0b035b8/examples/node-manual.yaml) is basically empty and that makes sense considering it doesn't do much. But `node-common.yaml` has something in it, presumably because mount/format may apply to both NFS and iSCSI devices. Should the latter be concatenated to the former to form a single config file?

And do this "final" config file need to be identical on both node and controller?

Next, for `volume-manual` (iSCSI), what goes into this `config` part?

```raw
      template {
        destination = "${NOMAD_TASK_DIR}/driver-config-file.yaml"

        data = <<EOH
config
EOH
      }
```

I tried to infer that from other examples, and it seems at minimum we would also need an iscsi section with portal IP so that Node host knows where to discover devices?

```yaml
iscsi:
  targetPortal: "server[:port]"
```

And maybe also CHAP credentials, but here it gets hard because related config entries differ between each back-end (FreeNAS, ZFS, Synology), so I temporarily opened access to all volumes hoping to skip that.

In this `node-volume` scenario, how does a Nomad client (Node container) know which iSCSI disk is which? 

In my example Nomad client can access the volume I created, I can also use it (mount, write). But it's visible as `/dev/sde` - there's no way for Nomad node to know which of several volumes is `dcsi` (my Nomad volume name on storage and in Nomad), so I imagine that some config entries (such as `baseiqn` + `NomadVolName`) would be used to form a complete IQN Target Name. 
I saw this (below) in node-manual-iscsi-pv.yaml, but I don't know if this should be added to Nomad Controller or Node (or both) job definition what would be the correct generic (`iscsiadm`) syntax required?

```
  iscsi:
    baseiqn: ""
    targetPortals: [""]
    interface: eth1
    shareStrategyTargetCli:
      basename: ""
```

Or is `baseiqn` perhaps one per back-end, while `basename` calls out each iSCSI device exposed to clients using this back-end? In that case I would have to name Nomad disks the same as they're named on storage, so that IQN becomes valid, but I'm not sure if that's how ID-to-IQN mapping works with `node-manual`.

I spent some time trying several different combinations, but `node-manual` is hard to troubleshoot because in Nomad all devices are always shown "healthy".

**Comment by travisghansen** [comment]
I think I understand where you're coming from. `node-manual` is not likely to be the answer you're looking for. If (csi) volumes can be manually created with `Nomad` then `node-manual` may be helpful. The approach would likely be slightly different than what you've described though...instead an independent process (neither `Nomad` nor `democratic-csi`) could be run which would scan your storage system (using whatever criteria/wildcards/etc that make sense for you) and then create the volumes inside `Nomad` with csi data created which follows these datapoints exactly in name: https://github.com/democratic-csi/democratic-csi/blob/master/examples/node-manual-iscsi-pv.yaml#L34-L40

I'm not sure if such a thing is even possible with `Nomad` however. If so, currently it would likely be of limited use as the `iscsi` node process has the following assumptions:

- the target has a single lun
- `democratic-csi` will entirely manage the entry for the target in the node iscsi `DB`

Of particular issue would be, upon detach `democratic-csi` logs out of the target entirely. If you run other luns on the nodes using the same target this could be extremely detrimental as `democratic-csi` is effectively removing access to all the other luns on the node as well. I've considered adding a parameter to control this behavior but as yet it has not been needed and so I haven't bothered.

Your understanding of the pros/cons of `local` storage seem correct.

Thanks for the help sorting this out, it's really appreciated and I'm excited to see better documentation around `Nomad`.

**Comment by scaleoutsean** [comment]
Got it! 
I didn't know that per-target logout (`iscsiadm --mode node --targetname iqn.2010-01.com.vendor:array-id.uniqVolName2 -u`) isn't available. All right, we're making progress... Back to drawing board...

**Comment by travisghansen** [comment]
Per-`target` is available, per-`lun` is not. So if you have luns on the target that are otherwise used it's problematic.

**Comment by scaleoutsean** [comment]
They [support](https://www.nomadproject.io/docs/internals/plugins/csi) all-in-one, I'll give it a try.

> Monolith Plugins are plugins that perform both the controller and node roles in the same instance. Not every plugin provider has or needs a controller; that's specific to the provider implementation.
