### ISSUE TITLE
increased memory consumption

### ISSUE THREAD

**Issue by djbobyd** [democratic-csi/democratic-csi#174]
Hi Travis,
Recently, I am observing increased memory consumption on my Kubernetes cluster. I started digging into it and to my surprise the biggest consumer of memory was the csi driver. On one of the nodes it uses ~7 GB of memory, see the picture:
![image](https://user-images.githubusercontent.com/478612/162912810-75da4b69-fd28-4898-be53-0c812cd04f58.png)
This is very surprising to me as I was expecting that the storage driver is just managing the metadata and does not need too much memory to do that. I have ~ 100 persistent volumes across my 4 nodes k8s cluster (each with 24 GB of RAM currently) which I consider not to be a lot, which is additionally puzzling me on the memory usage. 
Can you please comment, is this normal or not? If it's not, what can I do to improve the situation. I remember that older versions used far less memory, even when the cluster was only 4x16GB.

Thanks a lot for your cooperation.

Best Regards,
Borislav

**Comment by travisghansen** [comment]
Thanks for bringing it up! It is not normal and I actually discovered this a little over a week ago. It was introduced with the ‘proxy’ image and should be fixed here: https://github.com/democratic-csi/csi-grpc-proxy/commit/70ba96767462a72b91bd986309942d6cfb72166d

Can you confirm you are indeed running the proxy image and that it is version < 0.4.2?

**Comment by djbobyd** [comment]
Yes it seems the version is lower 
`docker.io/democraticcsi/csi-grpc-proxy:v0.4.1`
Do you happen to have a new helm release which I can deploy and test?

Thanks again for your fast and adequate reaction :)

**Comment by travisghansen** [comment]
Yeah, it should be the default in `v0.11.2`. We'll also track this: https://github.com/democratic-csi/charts/issues/25 to allow for setting limits via the chart as well.

**Comment by travisghansen** [comment]
After running that version for about a week myself things appear back to normal as an FYI. I really dug into node memory consumption when I found the issue thinking some leak had been introduced into the core project and 1 of my finding is that the 'rss' memory as used by node will continue to creep up (when memory is unbounded by the kernel). So while the numbers are back to normal the usage as reported by `kubectl -n democratic-csi top pods` for example is still higher than what it *really* is (in my case after a week of running the pods show usage between 70-150MB). In reality the code is using probably 60-70 across the board. The behavior stems from the kernel's 'if memory isn't being used it's being wasted' approach. My belief is that if we put a limit on the pods then the memory usage would start to stress more frequently and the `rss` values would drop as you approach the limit...at least that's my belief anyway.

**Comment by djbobyd** [comment]
So far I am observing the same, between 80 and 160 MB of usage. As soon as you have a version with limits configuration for testing I am glad to help.

**Comment by travisghansen** [comment]
As an FYI you can deploy with env var `LOG_MEMORY_USAGE=1` and the logs will spew out the actual memory usage. It would be interesting to see what those levels show for you over time..

**Comment by djbobyd** [comment]
So far what's in the table:
[Fri Apr 15 2022 09:25:58 GMT+0000 (Coordinated Universal Time)] Memory Usage: rss 76.27 MB
[Fri Apr 15 2022 09:25:58 GMT+0000 (Coordinated Universal Time)] Memory Usage: heapTotal 27.94 MB
[Fri Apr 15 2022 09:25:58 GMT+0000 (Coordinated Universal Time)] Memory Usage: heapUsed 24.14 MB
[Fri Apr 15 2022 09:25:58 GMT+0000 (Coordinated Universal Time)] Memory Usage: external 17.4 MB
[Fri Apr 15 2022 09:25:58 GMT+0000 (Coordinated Universal Time)] Memory Usage: arrayBuffers 0.2 MB

is the same as on the dashboard:

![image](https://user-images.githubusercontent.com/478612/163554042-e8d73521-c7f6-480c-b73f-cb4e850f61be.png)

**Comment by djbobyd** [comment]
Well Ithought that I shoul sum up rss + heap total +external + arrayBuffers. Then it sums up :)

**Comment by djbobyd** [comment]
Reading a bit more about the memory management in nodejs I realized I was wrong. Rss is the whole memory space used. Thus it really doesn't look OK :) BTW, I guess you already know about all of it but while looking for more info I stumbled upon several articles explaining the specifics on running nodejs in a container with memory limits, looks like it needs some special adjustments.

**Comment by travisghansen** [comment]
Right, `rss` should be everything currently used by the kernel (even stuff that hasn't been freed due to the lack of memory pressure). If you found some good articles send them over and I can review to make sure we're covered.

In general I'm confident (after the proxy fix) that memory isn't doing anything crazy speaking generally, but further tuning is always welcome :)

**Comment by djbobyd** [comment]
Well I am not sure if they are good articles. I am not an expert in JS, but these two seemed quite nice for the container case:
https://loadteststories.com/nodejs-kubernetes-an-oom-serial-killer-story/
https://developer.ibm.com/articles/nodejs-memory-management-in-container-environments/

**Comment by travisghansen** [comment]
New versions of `csi-grpc-proxy` have been released to resolve this issue and charts have been updated to support putting limits on resources as well.
