### ISSUE TITLE
Cannot Create Snapshots on Synology

### ISSUE THREAD

**Issue by codello** [democratic-csi/democratic-csi#176]
Hello, I am currently testing the `synology-iscsi` driver and I noticed that snapshots weren't created. During debugging I found that the reason for this issue is that the `SYNO.Core.Storage.iSCSILUN/load_snapshot` API does not exist (returns code 103, documented [here](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/SurveillanceStation/All/enu/Surveillance_Station_Web_API.pdf) on page 25). Instead the API `SYNO.Core.ISCSI.LUN/list_snapshot` could be used. I have successfully tested this and can make a PR (possibly together with a PR for #175) but before doing so I have two questions:

- Did the `load_snapshot` API exist previously and do we need to be keep compatibility for this API? `list_snapshot` uses the UUID instead of the ID of the LUN. The driver gets this value from the snapshot ID which means that any existing snapshots will be using the LUN ID and would need to convert it to a UUID when the snapshot is deleted. New Snapshots should probably store the LUN UUID directly. If this is a bug and the `load_snapshot` API did not exist (or backwards compatibility is not required) we could just refactor the snapshots to use UUIDs instead.
- I noticed that a lot of API calls use `JSON.stringify` on values resulting in *double quoting*. As an example:
  https://github.com/democratic-csi/democratic-csi/blob/19197f9515da57f569c670d14fefb1bfd4e43460/src/driver/controller-synology/http/index.js#L487
  The logs show the corresponding request parameters as `"src_lun_uuid":"\"952f031c-c0d1-455e-8b96-68ce5d4d174d\""`. Is there any particular reason for this? From my testing it seems that it isn't required (but it doesn't seem to do any harm either).

**Comment by travisghansen** [comment]
Yeah the double quotes are required. That was actually a pain in the ass to figure out without any documentation. As I recall it was uuids and arrays that need it.

The existing stuff does work and is tested in my ci. I am running 6.3 or something and have no ability to run 7 (I’m guessing that’s what you’re running). I don’t have the actual hardware and an testing entirely with kvm/proxmox and last I recall 7 didn’t work with kvm.

PRs are welcome. I will likely implement the other in the next week…been super busy adding windows support and after I wrap that up then I can revisit the template request.

**Comment by codello** [comment]
Thank you a lot for your feedback!

> That was actually a pain in the ass to figure out without any documentation. As I recall it was uuids and arrays that need it.

Ooh that's nasty. From my testing it seems that this is no longer the case for DSM 7 (at least not for UUIDs). But DSM actually doesn't seem to care if the extra quotes are there or not so it's easy to leave them in for backwards compatibility.

> I’m guessing that’s what you’re running

Yes, that's correct. I am running DSM 7.0.1-42218 Update 3 on a DS1520+. Sorry I didn't mention that before. It seems the API has changed a litte which caused this issue. Maybe I can get a VirtualDSM 6.2 instance running to be able to test against that.

> The existing stuff does work and is tested in my ci.

Good to know. Then I'll try to keep everything backwards compatible. I'm probably gonna move everything to the `list_snapshot` API because it's present in both DSM versions. I'll open a PR shortly.

**Comment by travisghansen** [comment]
Pretty sure this has all be updated to work and is released in `v1.7.0`
