### ISSUE TITLE
Issue creating PVC using truenas SSH provsioner. 

### ISSUE THREAD

**Issue by Tony-The-Developer** [democratic-csi/democratic-csi#182]
<html>
<body>

failed to provision volume with StorageClass "freenas-nfs-csi": rpc error: code = Unknown desc = received error creating nfs share - code: 422 body: {"networks":[{"message":"null not allowed","errno":22}]}
--

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by travisghansen** [comment]
Turn on debug logging to observe the raw commands being executed to see where it blows up...

```
controller:
  driver:
    logLevel: debug
````

**Comment by Tony-The-Developer** [comment]
@travisghansen Where do I add that? The helm release.

**Comment by Tony-The-Developer** [comment]
type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "freenas-nfs-csi": rpc error: code = Internal desc = Error: "401: Unauthorized" Error: "401: Unauthorized

**Comment by travisghansen** [comment]
That example snippet above is the helm value that needs to be set to enable debug logging. After enabling that get the logs from the controller pod (`csi-driver` container) and send them over here.

**Comment by Tony-The-Developer** [comment]
<html>
<body>


failed to provision volume with StorageClass "freenas-nfs-csi": rpc error: code = Internal desc = Error: {"create_ancestors":[{"message":"Field was not expected","errno":22}]} Error: {"create_ancestors":[{"message":"Field was not expected","errno":22}]} at Api.DatasetCreate (/home/csi/app/src/driver/freenas/http/api.js:392:11) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async FreeNASApiDriver.CreateVolume (/home/csi/app/src/driver/freenas/api.js:2623:7) at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:177:18)
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by Tony-The-Developer** [comment]
{"host":"zfs-nfs-democratic-csi-controller-79b6676d8f-vrv6b","level":"debug","message":"FREENAS HTTP ERROR: null","service":"democratic-csi","timestamp":"2022-05-03T02:57:59.232Z"}
{"host":"zfs-nfs-democratic-csi-controller-79b6676d8f-vrv6b","level":"debug","message":"FREENAS HTTP STATUS: 422","service":"democratic-csi","timestamp":"2022-05-03T02:57:59.232Z"}
{"host":"zfs-nfs-democratic-csi-controller-79b6676d8f-vrv6b","level":"debug","message":"FREENAS HTTP HEADERS: {\"server\":\"nginx\",\"date\":\"Tue, 03 May 2022 02:57:59 GMT\",\"content-type\":\"text/plain; charset=utf-8\",\"content-length\":\"92\",\"connection\":\"keep-alive\",\"strict-transport-security\":\"max-age=0; includeSubDomains; preload\",\"x-content-type-options\":\"nosniff\",\"x-xss-protection\":\"1; mode=block\",\"permissions-policy\":\"geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()\",\"referrer-policy\":\"strict-origin\",\"x-frame-options\":\"SAMEORIGIN\"}","service":"democratic-csi","timestamp":"2022-05-03T02:57:59.232Z"}
{"host":"zfs-nfs-democratic-csi-controller-79b6676d8f-vrv6b","level":"debug","message":"FREENAS HTTP BODY: {\"create_ancestors\":[{\"message\":\"Field was not expected\",\"errno\":22}]}","service":"democratic-csi","timestamp":"2022-05-03T02:57:59.232Z"}
{"host":"zfs-nfs-democratic-csi-controller-79b6676d8f-vrv6b","level":"error","message":"handler error - driver: FreeNASApiDriver method: CreateVolume error: Error: {\"create_ancestors\":[{\"message\":\"Field was not expected\",\"errno\":22}]} Error: {\"create_ancestors\":[{\"message\":\"Field was not expected\",\"errno\":22}]}\n at Api.DatasetCreate (/home/csi/app/src/driver/freenas/http/api.js:392:11)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at async FreeNASApiDriver.CreateVolume (/home/csi/app/src/driver/freenas/api.js:2623:7)\n at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:177:18)","service":"democratic-csi","timestamp":"2022-05-03T02:57:59.232Z"}
{"host":"zfs-nfs-democratic-csi-controller-79b6676d8f-vrv6b","level":"info","message":"new request - driver: FreeNASApiDriver method: CreateVolume call: {\"_events\":{},\"_eventsCount\":0,\"call\":{\"_events\":{},\"_eventsCount\":5,\"stream\":{\"_readableState\":{\"objectMode\":false,\"highWaterMark\":16384,\"buffer\":{\"head\":null,\"tail\":null,\"length\":0},\"length\":0,\"pipes\":[],\"flowing\":true,\"ended\":true,\"endEmitted\":true,\"reading\":false,\"constructed\":true,\"sync\":false,\"needReadable\":false,\"emittedReadable\":false,\"readableListening\":false,\"resumeScheduled\":false,\"errorEmitted\":false,\"emitClose\":true,\"autoDestroy\":false,\"destroyed\":false,\"errored\":null,\"closed\":false,\"closeEmitted\":false,\"defaultEncoding\":\"utf8\",\"awaitDrainWriters\":null,\"multiAwaitDrain\":false,\"readingMore\":false,\"dataEmitted\":true,\"decoder\":null,\"encoding\":null},\"_events\":{},\"_eventsCount\":8,\"_writableState\":{\"objectMode\":false,\"highWaterMark\":16384,\"finalCalled\":false,\"needDrain\":false,\"ending\":false,\"ended\":false,\"finished\":false,\"destroyed\":false,\"decodeStrings\":false,\"defaultEncoding\":\"utf8\",\"length\":0,\"writing\":false,\"corked\":0,\"sync\":true,\"bufferProcessing\":false,\"writecb\":null,\"writelen\":0,\"afterWriteTickInfo\":null,\"buffered\":

**Comment by travisghansen** [comment]
What version of TrueNAS are you running? Can you send over the full config (cleanse sensitive data please)?

**Comment by Tony-The-Developer** [comment]
Hey, I am using Truenas core. I did some research and found out that it is not supported with the API driver yet so i switched to the old driver using ssh and it worked.

**Comment by travisghansen** [comment]
OK great!

**Comment by yidaqiang** [comment]
Although it is the same error When creating PVC, I made another mistake.

```
failed to provision volume with StorageClass "freenas-nfs-csi": rpc error: code = Unknown desc = received error creating nfs share - code: 422 body: {"networks":[{"message":"null not allowed","errno":22}]}
```

I use `rancher` install democratic-csi. if upgrade this helm release, the `shareAllowedHosts` will be set to `null` not expect `[ ]`.
<img width="364" alt="image" src="https://user-images.githubusercontent.com/18599857/206309634-d3d3f91a-d263-408a-9e4e-377bf140b034.png">

So I add `shareAllowedHosts`

```yaml
    nfs:
      shareAlldirs: true
      shareAllowedHosts: ["10.0.0.2", "10.0.0.3"]
      shareAllowedNetworks:
        - 10.0.0.0/24
      shareHost: 10.0.0.1
      shareMapallGroup: ''
      shareMapallUser: ''
      shareMaprootGroup: wheel
      shareMaprootUser: root
```

**Comment by travisghansen** [comment]
Does it also fail with `[]` as the value?

**Comment by yidaqiang** [comment]
Thanks your reply，`shareAllowedHosts: []` is OK.
I think this a is bug of rancher.
