### ISSUE TITLE
freenas-api-iscsi: Missing HTTP content-type

### ISSUE THREAD

**Issue by tbrtje** [democratic-csi/democratic-csi#184]
Hello,
I can't create PVCs with the `freenas-api-iscsi`-driver running TrueNAS-SCALE-22.02.0.1.
I tried connecting via http and https and used a known working API-Key that I tested using curl.

The log show the following issue: `Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"iot", Name:"mosquitto-configinc", UID:"dd80c885-8b48-4753-9e2d-16679f65deb2", APIVersion:"v1", ResourceVersion:"1157939", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "freenas-iscsi-csi": rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); malformed header: missing HTTP content-type`.

Any idea what could cause this and how to fix it?

Best regards
Thies

**Comment by travisghansen** [comment]
What version of TrueNAS are you running?

**Comment by tbrtje** [comment]
I am running TrueNAS-SCALE-22.02.0.1

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/freenas/http/index.js#L83

Can you turn on debug logging? You will be able to see full requests/responses logged. Specifically set the debug log level on the controller.

**Comment by tbrtje** [comment]
Hi there, I managed to get it to work. It turned out to be a networking issue. The cluster nodes weren't able to connect to my truenas instance. The debug logs showed an EHOSTUNREACH error message that made it clear, so there wasn't really a bug.

**Comment by lknite** [comment]
similar issue, after redeploying a cluster and associated apps via gitops, turned out the cluster dns wasn't searching using a domain, so specifying an fqdn fixed the issue... or of course, could have added the domain to the /etc/resolv file.
