### ISSUE TITLE
Latest version fails in csi-driver

### ISSUE THREAD

**Issue by davisglenn** [democratic-csi/democratic-csi#186]
Hi,
I know this isn't going to be a lot of help so I apologize.
The latest version in dockerhub is failing.  Its failing on the csi-driver container with the error message:
**/usr/bin/env: only ${VARNAME} expansion is supported, error at: ${NO**

Apparently this is what was causing my other issue with dockerhub failing on Toomanyrequests.

When I go back to v1.4.4 everything works perfectly.  I'm fine with using 1.4.4 for now so I'm good, but I wanted to at least alert you to the issue.

**Comment by travisghansen** [comment]
Details here: https://github.com/democratic-csi/democratic-csi/issues/171

**Comment by davisglenn** [comment]
thanks!
