### ISSUE TITLE
Upgrading from v1.6.0 broke driver

### ISSUE THREAD

**Issue by mhellsten** [democratic-csi/democratic-csi#187]
FYI, my cluster went down due to a power failure while it was using democratic-csi with iscsi on version v1.6.0 using Helm. When it came up, it pulled a new version of the csi-driver image, because it's specified as docker.io/democraticcsi/democratic-csi:latest in the chart. That made my iscsi csi-driver crash with this error:
`/usr/bin/env: only ${VARNAME} expansion is supported, error at: ${NO`

Overriding the image tag in the helm chart with v1.6.0 fixed the problem.

**Comment by travisghansen** [comment]
See here: https://github.com/democratic-csi/democratic-csi/issues/171

**Comment by travisghansen** [comment]
I'm working on a massive `v1.7.0` release with support for windows which will have the changes in there to fix the issue you are likely experiencing.

**Comment by mhellsten** [comment]
Thanks!
