### ISSUE TITLE
Helm Installation, Ignore aarch64/arm64 nodes?

### ISSUE THREAD

**Issue by shawnallen85** [democratic-csi/democratic-csi#19]
Is there a way to have the chart installation ignore deploying to arm64 nodes? Or is there a plan to have the docker image support arm64 as well?

The cluster in my homelab is a mixture of arm64 (web workers) and amd64 (database workers).

Thanks!!

**Comment by travisghansen** [comment]
Not yet! We can look into it.

To give some context this project actually does support arm, it’s (oddly enough) the kubernetes bits that aren’t multiarch yet. For example others have deployed successfully with arm by setting custom images for some of the pieces.

None of that works so well for multiarch clusters though :(

Probably add a nodeselector block? How do other charts deal with this generally?

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/charts/pull/13

**Comment by travisghansen** [comment]
Merged.

**Comment by travisghansen** [comment]
0.5.0

**Comment by mechinn** [comment]
admittedly while the nodeselector of the new chart helps at least run this only on specific nodes that are known to work with the image, making the docker image into a multiarch image would actually be the right way to solve this probably

**Comment by travisghansen** [comment]
@mechinn yeah, this project builds multi arch already. It’s all the other projects that still don’t unfortunately. There are several bugs for each of the various components that just seem to sit and sit :(

**Comment by travisghansen** [comment]
https://github.com/kubernetes-csi/csi-release-tools/issues/86

**Comment by mechinn** [comment]
ohhhhhh gotcha that's unfortunate :(

**Comment by travisghansen** [comment]
Update, it appears many of the components have been migrated. The minimum requirement on many of them appears to be k8s 1.17. It's probably safe to force that as a requirement at this point. The only real problem is if any of the args changed on the most recent versions that make the chart not backwards compatible with older image versions (as image versions can be tweaked via values).

In the next week or so I'll probably update the chart to use the most recent versions.

https://kubernetes-csi.github.io/docs/sidecar-containers.html

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/charts/issues/14

**Comment by travisghansen** [comment]
All, fresh new images are building with a *ton* of enhancements and bullet-proofing of the sometimes crazy FreeNAS API. I've also snapped a `v0.6.0` release of the chart which updates all the sidecars which I'm told should all have multiarch support now. If someone gets a chance try out the new chart and let me know how it goes!
