### ISSUE TITLE
Detached Snapshots - Pro and Con?

### ISSUE THREAD

**Issue by inzanez** [democratic-csi/democratic-csi#190]
Hi

are there any specific downsides using detached snapshots? I have seen the configuration of the detached snapshot volumes that can be created in TrueNAS. I just tested doing snapshots and realized that they are not being used; because I haven't explicitly activated detached snapshots (I assume). So normally the snapshots are attached to the said volume, and I assume that using detached snapshots would break that connection between snapshot and actual volume on the ZFS layer?...

The interesting part would be: are there any upsides / downsides to either of these approaches? I am planning to use snapshots in conjunction with K10 to have a decent backup / restore / migration solution.

**Comment by travisghansen** [comment]
Detached snapshots do zfs send/receive, otherwise zfs snapshot is employed. Predominately that becomes a space vs data safety question but there are other ramifications.

See here: https://github.com/democratic-csi/democratic-csi/issues/129#issuecomment-961489810

**Comment by inzanez** [comment]
@travisghansen wow, thanks for that! I guess I must read up on ZFS,...first time touching that. But from what I read in your linked post I tend to say that zfs send/receive (so using detached snapshots) is generally the safer but more resource intensive option?

Will there ever be an option to do a zfs send/receive off-storage btw.? That sounds quite interesting.

**Comment by travisghansen** [comment]
Yeah it’s primarily a space/speed/data safety consideration. Using the cow features (zfs snapshots) requires 0 additional space (initially) and is instantaneously created. If you create a new dataset from the snapshot then as the new dataset diverges then additional space is consumed. You will find lots of really good articles about all this written by people smarter than me so probably a bit of research will lead you to the correct decision for your needs. There are weird edge cases for example if you have lots of volumes that use the same snapshot as a source then over time it can actually be less efficient and use more space than if each was detached. It’s fairly complex stuff.

Some contest this theory that a snapshot is not a backup (similar to the raid is not a backup conversation). There are other tools that can make actual backups to s3 and the like would may serve that need for you.

Regarding off-storage send/receive I don’t know honestly. I would consider it for sure but there would definitely be some things to work through to ensure proper behavior.

**Comment by inzanez** [comment]
Yes, I would agree that I do not count a snapshot as a backup, at least not if it resides on the same system. I am looking at different tools right now to overcome that issue, like K10, Velero and PX-Backup. Not quite happy with any of them so far though...:-)

**Comment by travisghansen** [comment]
Yeah, they all have their place I suppose.

What are your desired outcomes and what are you not happy about with those options?

https://github.com/FairwindsOps/gemini (this also only manages the snapshot lifecycle, so again not really a backup)

**Comment by inzanez** [comment]
@travisghansen Well, basically I would want something that is capable of backing up any storage-class to something like S3 or NFS, with retention times and options of restoring the backup to another cluster for verification of that backup.

K10 should do this I think, but in my opinion it's too complex for what I actually need and I did have some issues where created backups did restore well but the job never finished in the UI / tool. Restarting certain containers magically cleared up that 'still running' job. So all in all it just didn't feel that solid.

Px-Backup does make quite a good impression so far, but it's the only one that's not free and I need to get a price tag on the software first.

Velero doesn't yet support a datamover for snapshots created but would support any underlying storage class using Restic. But then they write it should be considered a beta software. Apart from that there's no multi-cluster setup as far as I can see, so I need to set it up on every cluster (although that's not really an issue as the setup is really simple).
