### ISSUE TITLE
Snapshot - Restore Test with Kubestr and iSCSI XFS

### ISSUE THREAD

**Issue by inzanez** [democratic-csi/democratic-csi#191]
Hi

I just tested snapshots and restoring using `kubestr`. The command looks like this:
`kubestr csicheck -s truenas-iscsi -v truenas-iscsi`

I did test that with `ext4` as `fsType` at first, which works wonderfully. But changing the `fsType` to `xfs` will lead to:
` XFS (sde): Filesystem has duplicate UUID 552a897a-5492-4fd4-96c9-059535e737a6 - can't mount`.

I am not sure if it is always the case that the 'restore' happens on the same worker node with how `kubestr` tests the snapshot & restore. There is certainly the option of using `nouuid` as a mount option for `xfs` filesystem to resolve that issue, but I am not sure if that has other consequences.

**Comment by travisghansen** [comment]
Oh very interesting! I’ll take a look and see what can/should be done. You’re getting deep into the features!

**Comment by travisghansen** [comment]
Looks like maybe I could detect that error at mount time and update the uuid..

**Comment by travisghansen** [comment]
https://github.com/ceph/ceph-csi/pull/1009

**Comment by inzanez** [comment]
Yes, I have seen that one. But I thought this would have to be implemented into the driver,…or is there acway to specify nouuid generally for all XFS filesystems?

**Comment by travisghansen** [comment]
No, I'll add it to the driver..it's quite easy to put this in there.

**Comment by inzanez** [comment]
Great, many thanks! Shall I close this issue or do you want to leave it open for reference?

**Comment by travisghansen** [comment]
I usually leave them open until the fix is in a released version.

**Comment by travisghansen** [comment]
Fixed in this commit: https://github.com/democratic-csi/democratic-csi/commit/81a42d789f9b2c8cdf5fd93e40d740b8a2ae3699

Released in `v1.7.0`
