### ISSUE TITLE
Multi_node_multi_Writer Error with iscsi claim

### ISSUE THREAD

**Issue by Shifter2600** [democratic-csi/democratic-csi#2]
Normal   ExternalProvisioning  10s (x4 over 38s)  persistentvolume-controller                                                                                         waiting for a volume to be created, either by external provisioner "org.democratic-csi.iscsi" or manually created by system administrator
  Normal   Provisioning          7s (x6 over 38s)   org.democratic-csi.iscsi_freeiscsi-democratic-csi-controller-679549956f-xslrz_40f1fb5a-0606-4b28-919e-c7780651474a  External provisioner is provisioning volume for claim "default/freenas-test-iscsi-pvc"
  Warning  ProvisioningFailed    7s (x6 over 38s)   org.democratic-csi.iscsi_freeiscsi-democratic-csi-controller-679549956f-xslrz_40f1fb5a-0606-4b28-919e-c7780651474a  failed to provision volume with StorageClass "freenas-iscsi-csi": rpc error: code = InvalidArgument desc = invalid access_mode, MULTI_NODE_MULTI_WRITER

Here is my claim

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: freenas-test-iscsi-pvc
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

**Comment by travisghansen** [comment]
I’m guessing you created the pvc as `ReadWriteMany` which at a fundamental level is not supported by iscsi. The other modes should work however.

**Comment by Shifter2600** [comment]
Yep that was it. Both NFS and iscsi are working. Thx for all your help.
