### ISSUE TITLE
Can't make snapshot

### ISSUE THREAD

**Issue by MGlants** [democratic-csi/democratic-csi#204]
`I0610 09:03:25.870393       1 connection.go:183] GRPC call: /csi.v1.Identity/GetPluginInfo
I0610 09:03:25.870407       1 connection.go:184] GRPC request: {}
I0610 09:03:25.874456       1 connection.go:186] GRPC response: {"name":"org.democratic-csi.nfs","vendor_version":"1.7.0"}
I0610 09:03:25.874562       1 connection.go:187] GRPC error: <nil>
I0610 09:03:25.874584       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I0610 09:03:25.874599       1 connection.go:184] GRPC request: {"name":"snapshot-f63d67fd-3e3c-41b9-9a27-a56e650b35a2","parameters":{"detachedSnapshots":"false"},"source_volume_id":"pvc-07550fe2-c6e2-4d96-a591-1071a51aa151"}
I0610 09:03:25.885896       1 connection.go:186] GRPC response: {}
I0610 09:03:25.885984       1 connection.go:187] GRPC error: rpc error: code = Internal desc = TypeError: response.body.children is not iterable TypeError: response.body.children is not iterable
    at FreeNASApiDriver.CreateSnapshot (/home/csi/app/src/driver/freenas/api.js:3919:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:18)
I0610 09:03:25.886022       1 snapshot_controller.go:325] createSnapshotWrapper: CreateSnapshot for content snapcontent-f63d67fd-3e3c-41b9-9a27-a56e650b35a2 returned error: rpc error: code = Internal desc = TypeError: response.body.children is not iterable TypeError: response.body.children is not iterable
    at FreeNASApiDriver.CreateSnapshot (/home/csi/app/src/driver/freenas/api.js:3919:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:18)`

**Comment by MGlants** [comment]
I've restarted controlled pod and everything seems normal after it

**Comment by travisghansen** [comment]
Meaning the snapshot created? Can you set the log level to `debug` and send over the actual http request/response data?

**Comment by MGlants** [comment]
I think i will close it, pod restarting solved everything
