### ISSUE TITLE
Question on democratic-csi PVC inode counts / Prometheus

### ISSUE THREAD

**Issue by reefland** [democratic-csi/democratic-csi#213]
I'm using a Grafana Dashboard / Prometheus (kube-stack-prometheus) to monitor my democratic-csi iSCSI volumes.   The "Volume Space Usage" seems to be fine.

However, the "Volume Inodes Usages" shows zeros.  I am using XFS instead of EXT4 but XFS still has inodes from what I remember.

I have democratic-csi iSCSI volumes in the namespace "monitoring", queried via `kubelet_volume_stats_inodes_used{namespace="monitoring"}` and all of them report a value of zero for inodes used:

```
kubelet_volume_stats_inodes_used{endpoint="https-metrics", instance="192.168.10.215:10250", job="kubelet", metrics_path="/metrics", namespace="monitoring", node="k3s01", persistentvolumeclaim="kube-prometheus-stack-grafana", service="kube-prometheus-stack-kubelet"} | 0

kubelet_volume_stats_inodes_used{endpoint="https-metrics", instance="192.168.10.216:10250", job="kubelet", metrics_path="/metrics", namespace="monitoring", node="k3s02", persistentvolumeclaim="prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0", service="kube-prometheus-stack-kubelet"} | 0

kubelet_volume_stats_inodes_used{endpoint="https-metrics", instance="192.168.10.217:10250", job="kubelet", metrics_path="/metrics", namespace="monitoring", node="k3s03", persistentvolumeclaim="alertmanager-kube-prometheus-stack-alertmanager-db-alertmanager-kube-prometheus-stack-alertmanager-0", service="kube-prometheus-stack-kubelet"} | 0

```

I don't understand how the data is pulled, but I assume democratic-csi is not providing the data??  

If I point it to a Longhorn volume, it does return the number of inodes used:

```
kubelet_volume_stats_inodes_used{endpoint="https-metrics", instance="192.168.10.217:10250", job="kubelet", metrics_path="/metrics", namespace="unifi", node="k3s03", persistentvolumeclaim="unifi-longhorn-pvc", service="kube-prometheus-stack-kubelet"} | 3293
```

Prometheus itself is using a 50GB democratic-csi iSCSI PVC, if I go into the container, it reports inodes:
```
/prometheus $ df -h .
Filesystem                Size      Used Available Use% Mounted on
/dev/sda                 50.0G     19.5G     30.5G  39% /prometheus

/prometheus $ df -i .
Filesystem              Inodes      Used Available Use% Mounted on
/dev/sda              26214400       165  26214235   0% /prometheus
```

These also return zeros for each PVC:
`kubelet_volume_stats_inodes{namespace="monitoring"}`
`kubelet_volume_stats_inodes_free{namespace="monitoring"}`

**Comment by travisghansen** [comment]
Good question. I'm guessing k8s invokes the `GetVolumeStats` method of the `Node` service. I'm currently only returning byte info but inode could also be added to the mix.

**Comment by reefland** [comment]
Sounds like that explains why the Space Usage works but inode usage doesn't.   If you get around to adding it to your "next" branch, be glad to test it.

**Comment by travisghansen** [comment]
Ok it should be in the `next` images now: https://github.com/democratic-csi/democratic-csi/commit/b83361535d3ad5fd178066daa9aabf579787f604

**Comment by reefland** [comment]
It's ok if you sleep and eat once in a while too. :)

Fantastic.  Spun up a test VM using the `next` image.  Looking good so far.

![grafana_csi_inodes](https://user-images.githubusercontent.com/16230914/176250411-e64e5ee7-69f3-4566-9466-a311eace2c31.png)

And double-checked:

```shell
$ k exec -it prometheus-kube-prometheus-stack-prometheus-0 -n monitoring -c prometheus -- /bin/sh
/prometheus $ df -i .
Filesystem              Inodes      Used Available Use% Mounted on
/dev/sdf              26214400         9  26214391   0% /prometheus
```

**Comment by travisghansen** [comment]
Released in `v1.7.2`.

**Comment by reefland** [comment]
Based on the metric name `kubelet_volume_stats_inodes_used` I'm assuming that is from Kublet.  Which I enable in my kube-prometheus-stack installation:

```
        kubelet:
          enabled: true
          namespace: kube-system
```

Can query it directly from Prometheus:
`kubelet_volume_stats_inodes_used{cluster="",,job="kubelet", metrics_path="/metrics", namespace="monitoring", persistentvolumeclaim="prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0"}`

Which I now show as `33`:

![grafana_csi_inodes_02](https://user-images.githubusercontent.com/16230914/176319359-f225089b-2a0a-460a-8f6f-b365359f3804.png)

The dashboard was installed as part of the kube-prometheus-stack installation, it is from `kubernetes-mixin` which I assume is from here [https://github.com/kubernetes-monitoring/kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin).

Appears to have same ID as this one [https://grafana.com/grafana/dashboards/12660](https://grafana.com/grafana/dashboards/12660) if you just want to import `12660` to Grafana.

**Comment by travisghansen** [comment]
Cool thanks!
