### ISSUE TITLE
can we use this csi driver with readynas

### ISSUE THREAD

**Issue by thatsk** [democratic-csi/democratic-csi#220]

**Comment by travisghansen** [comment]
Not currently. Assuming it has an api and supports iscsi, nfs, or smb it would likely be pretty straightforward to implement however.

**Comment by thatsk** [comment]
so can't we use generic iscsi luns to target instance. Like a way we can do it for nfs. if we have nfs we can register and mount it for nomad volumes. same way.

**Comment by travisghansen** [comment]
If you want to provision and deprovision manually you may use the `node-manual` driver yes..

**Comment by thatsk** [comment]
can you point me to that pls.

**Comment by travisghansen** [comment]
Just the ‘register’ portion at the bottom of this: https://github.com/democratic-csi/democratic-csi/blob/master/docs/nomad.md

For proper `context` values look at the volumeAttributes of the `node-manual-foo` examples here: https://github.com/democratic-csi/democratic-csi/tree/master/examples

**Comment by thatsk** [comment]
give me some time and I will try to create a scenario and see if that works. as per your example. Don't we need a controller and node. nomad file for iscsi?

**Comment by travisghansen** [comment]
Yeah a single deployment of the node service is sufficient, no controller for that driver.

Config is here: https://github.com/democratic-csi/democratic-csi/blob/master/examples/node-manual.yaml

**Comment by travisghansen** [comment]
Node manual works with any of the protocols available in the project so iscsi, smb, and nfs. There is no cephfs support currently.

**Comment by thatsk** [comment]
```
job "storage-node" {
  datacenters = ["dc1"]
  type        = "system"

  group "node" {
    task "node" {
      driver = "docker"

      config {
        image = "democraticcsi/democratic-csi:latest"

        args = [
          "--csi-version=1.2.0",
          "--csi-name=org.democratic-csi.nfs",
          "--driver-config-file=${NOMAD_TASK_DIR}/driver-config-file.yaml",
          "--log-level=debug",
          "--csi-mode=node",
          "--server-socket=/csi-data/csi.sock",
        ]

        privileged = true
      }

      csi_plugin {
        id        = "generic-iscsi"
        type      = "node"
        mount_dir = "/csi-data"
      }

      template {
        destination = "${NOMAD_TASK_DIR}/driver-config-file.yaml"

        data = <<EOH
driver: node-manual
EOH
      }

      resources {
        cpu    = 30
        memory = 50
      }
    }
  }
}```

is this looks good

**Comment by thatsk** [comment]
volume.nomad
```

**Comment by travisghansen** [comment]
Great work!

I'm not sure exactly how `Nomad` handles csi secrets, but this is the doc: https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/examples/freenas-iscsi.yaml#L29-L38

As an FYI, you may want to rename the plugin to `node-manual` simply because a single deployment can actually handle both iscsi, smb, and nfs (just change the details of the `volume.nomad` as appropriate and the driver will work).

**Comment by travisghansen** [comment]
@tgross any chance you can provide some clarity on using stage secrets? This doc https://www.nomadproject.io/docs/other-specifications/volume#secrets indicates those values correlate to the publish secrets.

**Comment by thatsk** [comment]
@travisghansen if we want to use secrets stanza in volume definition can we just write like this
```
secrets {
     node-db.node.session.auth.authmethod = CHAP
     node-db.node.session.auth.username = foo
    node-db.node.session.auth.password = bar
}
```

**Comment by travisghansen** [comment]
Did that work? In csi spec there are different secrets at play and per the doc that stanza is not the correct set of secrets.

**Comment by thatsk** [comment]
Yes just tried but didn't help
