### ISSUE TITLE
NFS on k3s authentication error

### ISSUE THREAD

**Issue by ondrejkulich** [democratic-csi/democratic-csi#236]
Hi, I just started to install NFS from TrueNas Core and k3s cluster on Rpi 4 with Ubuntu 22.04 Server Edition. I go through the tutorial (https://jonathangazeley.com/2021/01/05/using-truenas-to-provide-persistent-storage-for-kubernetes/) but I stuck with this error on a container zfs-nfs-democratic-csi-controller:
`grpc implementation: @grpc/grpc-js
{"host":"zfs-nfs-democratic-csi-controller-544bd7ff89-b8f9g","level":"info","message":"initializing csi driver: freenas-nfs","service":"democratic-csi","timestamp":"2022-09-29T09:40:25.885Z"}
{"host":"zfs-nfs-democratic-csi-controller-544bd7ff89-b8f9g","level":"info","message":"starting csi server - node version: v16.16.0, package version: 1.7.6, config file: /config/..2022_09_29_08_53_34.2309031433/driver-config-file.yaml, csi-name: org.democratic-csi.nfs, csi-driver: freenas-nfs, csi-mode: controller, csi-version: 1.5.0, address: , socket: unix:///csi-data/csi.sock.internal","service":"democratic-csi","timestamp":"2022-09-29T09:40:28.021Z"}
{"host":"zfs-nfs-democratic-csi-controller-544bd7ff89-b8f9g","level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-node-js/1.6.8\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-09-29T09:40:35.676Z"}
{"date":"Thu Sep 29 2022 09:40:35 GMT+0000 (Coordinated Universal Time)","error":{"level":"client-authentication"},"exception":true,"host":"zfs-nfs-democratic-csi-controller-544bd7ff89-b8f9g","level":"error","message":"uncaughtException: All configured authentication methods failed\nError: All configured authentication methods failed\n    at doNextAuth (/home/csi/app/node_modules/ssh2/lib/client.js:803:21)\n    at tryNextAuth (/home/csi/app/node_modules/ssh2/lib/client.js:993:7)\n    at USERAUTH_FAILURE (/home/csi/app/node_modules/ssh2/lib/client.js:373:11)\n    at 51 (/home/csi/app/node_modules/ssh2/lib/protocol/handlers.misc.js:337:16)\n    at Protocol.onPayload (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)\n    at AESGCMDecipherNative.decrypt (/home/csi/app/node_modules/ssh2/lib/protocol/crypto.js:987:26)\n    at Protocol.parsePacket [as _parse] (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)\n    at Protocol.parse (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:293:16)\n    at Socket.<anonymous> (/home/csi/app/node_modules/ssh2/lib/client.js:713:21)\n    at Socket.emit (node:events:527:28)","os":{"loadavg":[0.23,0.13,0.15],"uptime":837175.23},"process":{"argv":["/usr/local/bin/node","/home/csi/app/bin/democratic-csi","--csi-version=1.5.0","--csi-name=org.democratic-csi.nfs","--driver-config-file=/config/driver-config-file.yaml","--log-level=info","--csi-mode=controller","--server-socket=/csi-data/csi.sock.internal"],"cwd":"/home/csi/app","execPath":"/usr/local/bin/node","gid":0,"memoryUsage":{"arrayBuffers":352260,"external":29483544,"heapTotal":65007616,"heapUsed":38490976,"rss":108752896},"pid":1,"uid":0,"version":"v16.16.0"},"service":"democratic-csi","stack":"Error: All configured authentication methods failed\n    at doNextAuth (/home/csi/app/node_modules/ssh2/lib/client.js:803:21)\n    at tryNextAuth (/home/csi/app/node_modules/ssh2/lib/client.js:993:7)\n    at USERAUTH_FAILURE (/home/csi/app/node_modules/ssh2/lib/client.js:373:11)\n    at 51 (/home/csi/app/node_modules/ssh2/lib/protocol/handlers.misc.js:337:16)\n    at Protocol.onPayload (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)\n    at AESGCMDecipherNative.decrypt (/home/csi/app/node_modules/ssh2/lib/protocol/crypto.js:987:26)\n    at Protocol.parsePacket [as _parse] (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)\n    at Protocol.parse (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:293:16)\n    at Socket.<anonymous> (/home/csi/app/node_modules/ssh2/lib/client.js:713:21)\n    at Socket.emit (node:events:527:28)","timestamp":"2022-09-29T09:40:35.807Z","trace":[{"column":21,"file":"/home/csi/app/node_modules/ssh2/lib/client.js","function":"doNextAuth","line":803,"method":null,"native":false},{"column":7,"file":"/home/csi/app/node_modules/ssh2/lib/client.js","function":"tryNextAuth","line":993,"method":null,"native":false},{"column":11,"file":"/home/csi/app/node_modules/ssh2/lib/client.js","function":"USERAUTH_FAILURE","line":373,"method":null,"native":false},{"column":16,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/handlers.misc.js","function":"51","line":337,"method":null,"native":false},{"column":10,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js","function":"Protocol.onPayload","line":2025,"method":"onPayload","native":false},{"column":26,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/crypto.js","function":"AESGCMDecipherNative.decrypt","line":987,"method":"decrypt","native":false},{"column":25,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js","function":"Protocol.parsePacket [as _parse]","line":1994,"method":"parsePacket [as _parse]","native":false},{"column":16,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js","function":"Protocol.parse","line":293,"method":"parse","native":false},{"column":21,"file":"/home/csi/app/node_modules/ssh2/lib/client.js","function":null,"line":713,"method":null,"native":false},{"column":28,"file":"node:events","function":"Socket.emit","line":527,"method":"emit","native":false}]}
running server shutdown, exit code: Error: All configured authentication methods failed
Stream closed EOF for democratic-csi/zfs-nfs-democratic-csi-controller-544bd7ff89-b8f9g (csi-driver)
` 
Do you have some resolution for this?

Thank you

**Comment by travisghansen** [comment]
Share the solution in case other hit the same issue :)

**Comment by jtackaberry** [comment]
Might have been related to #200.  I ran into this as well when upgrading my ZoL server from Ubuntu 20.04 to 22.04 and just needed to swap the RSA key for ED25519.
