### ISSUE TITLE
Persistent Volumes Migration

### ISSUE THREAD

**Issue by Tony-The-Developer** [democratic-csi/democratic-csi#242]
Hello. I have the freenas provisioner working on a kubernetes cluster. If i set it up again on another cluster. Is there a way to get the provisioner on the new cluster to use these existing PV's.  Any help would be greatly appreciated. 

![image](https://user-images.githubusercontent.com/68414482/196590261-526301ab-0dae-4999-b978-ab46972fdbb7.png)

**Comment by travisghansen** [comment]
You plan to delete the existing cluster and create a new cluster and you want the PVs/PVCs to carry over but nothing else (deployments, etc)?

**Comment by Tony-The-Developer** [comment]
Well everything but my concern is the volumes.

**Comment by Tony-The-Developer** [comment]
Its running a newer version of kubernetes. Will that work.?

**Comment by Tony-The-Developer** [comment]
Is there any tools to just move partial namespaces over to another cluster.

**Comment by travisghansen** [comment]
You could use something like velero. It does a full backup/restore. If the volumes are iscsi you want to make sure you don’t have both clusters attached simultaneously to prevent corruption.
