### ISSUE TITLE
remote error: tls: internal error`

### ISSUE THREAD

**Issue by D1StrX** [democratic-csi/democratic-csi#243]
Noticing something in the logs regarding the values.yaml and extraCaCerts option. Democratic-csi does succesfully create a pvc on Truenas Scale with `allowInsescure: false`, but I still see _remote error: tls: internal error_ on logs zfs-nfs-democratic-csi-controller

Certificate is all good, SANs contain IPs etc. Otherwise Democratic-csi couldn't even create the pvc.

The values.yaml file contains:
```
extraCaCerts: |-
  -----BEGIN CERTIFICATE-----
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  -----END CERTIFICATE-----
....
driver:
  config:
    driver: freenas-api-iscsi
    instance_id:
    httpConnection:
      protocol: https
      host: <truenas_scale_ip>
      port: 443
      apiKey: <api_key>
      username: democratic-csi
      allowInsecure: false
....
```

When viewing the logs of the democratic-csi controller I see this:
`k logs -n democratic-csi zfs-nfs-democratic-csi-controller-<id>`
Output: `Defaulted container "external-provisioner" out of: external-provisioner, external-resizer, external-snapshotter, csi-driver, csi-proxy
Error from server: Get "https://<worker_node_ip>:10250/containerLogs/democratic-csi/zfs-nfs-democratic-csi-controller-7db558c55c-jb725/external-provisioner": remote error: tls: internal error`

`k get pods -n democratic-csi`
NAME                                             READY   STATUS  
zfs-nfs-democratic-csi-controller   5/5        Running 
zfs-nfs-democratic-csi                    4/4        Running 
zfs-nfs-democratic-csi                    4/4        Running 

So everything looks to be okay... except somewhere it is still outputting an error?
Any idea how/if we could figure this out?

**Comment by D1StrX** [comment]
Might have something to do with the serverTLSBootstrap true option in my kubeadm setup .. but if you have additional suggestions, please let me know

**Comment by travisghansen** [comment]
Yeah that error has little to do with csi or your truenas install. Port 10250 on the node is a kubelet thing and the external-provisioner container producing those logs is standard k8s tooling (not something I maintain, so I’m unfortunately pretty ignorant to its internals) so I’m not much help :(

**Comment by D1StrX** [comment]
Completely understandable. Thanks for confirming.
