### ISSUE TITLE
Expanding ZFS volume succeeds but kubelet is throwing warnings

### ISSUE THREAD

**Issue by marcusaram** [democratic-csi/democratic-csi#246]
I'm running democratic-csi a while on OKD4 cluster. This issue came up lately, don't know if it had to do with k8s version or democratic-csi. Was running on pre 1.0 for a while and recently updated. 
When we expand a volume it will actually expand the volume but we're getting warnings from kubelet 
```
NodeExpandVolume.NodeExpandVolume failed for volume "pvc-fe0cddd8-9079-41b0-bbaa-be9fe52f5784" : Expander.NodeExpand found CSI plugin kubernetes.io/csi/org.democratic-csi.nfs to not support node expansion.
```
In the csi-driver log I can find this as related error:
```
{"host":"worker4","level":"error","message":"handler error - driver: FreeNASSshDriver method: NodeGetVolumeStats error: {\"name\":\"GrpcError\",\"code\":10,\"message\":\"operation locked due to in progress operation(s): [\\\"volume_id_pvc-fe0cddd8-9079-41b0-bbaa-be9fe52f5784\\\"]\"}","service":"democratic-csi","timestamp":"2022-10-29T00:59:56.852Z"}
```
Is there a way to remove this operation lock?

Running democratic-csi 1.7.7

**Comment by travisghansen** [comment]
Yeah: https://github.com/democratic-csi/democratic-csi/issues/244

I've had a hardware failure in my lab preventing me from building new images atm that I won't be able to address for another week or 2 however :(

**Comment by travisghansen** [comment]
The lock is in memory and should clear itself up eventually. If not then democratic-csi pod can be restarted on the proper node to make it go away as well.

**Comment by travisghansen** [comment]
Sorry I missed that log entry :( I see better now what your concern is. Can you send over the expand request/response from the controller pod?

**Comment by travisghansen** [comment]
Ok so in the response you see `node_expansion_required\":false` so that's the controller telling k8s should not need/attempt a node resize (unless I'm doing something wrong). Assuming that response is correct this is likely something we'll need to ask the kubelet folks as to why it's getting logged and why it would be a warning if indeed it's been told not to attempt it anyway.

**Comment by marcusaram** [comment]
Hi, I've looked up the specs. Isn't this an online expansion like listed here below?

---

ControllerExpandVolume

A Controller plugin MUST implement this RPC call if plugin has EXPAND_VOLUME controller capability. This RPC allows the CO to expand the size of a volume.

This operation MUST be idempotent. If a volume corresponding to the specified volume ID is already larger than or equal to the target capacity of the expansion request, the plugin SHOULD reply 0 OK.

This call MAY be made by the CO during any time in the lifecycle of the volume after creation if plugin has VolumeExpansion.ONLINE capability. If plugin has EXPAND_VOLUME node capability, then NodeExpandVolume MUST be called after successful ControllerExpandVolume and node_expansion_required in ControllerExpandVolumeResponse is true.
