### ISSUE TITLE
open-iscsi fails to start (ConditionDirectoryNotEmpty)

### ISSUE THREAD

**Issue by etokheim** [democratic-csi/democratic-csi#247]
Hi! 

I can't get the open-iscsi service to run. In the readme it tells me to check its status under the install, so I thought I was screwed when it didn't run. However, I just pushed on and never encountered any errors. I haven't tried to use any of my test pvc's yet, but they seem to work fine and are provisioned in TrueNAS:

```sh
kc get pvc -o wide
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE   VOLUMEMODE
test-claim-nfs     Bound    pvc-c5ad7275-48e4-4d77-973a-676258449300   1Gi        RWO            freenas-nfs-csi     12m   Filesystem
test-claim-iscsi   Bound    pvc-bc55cd17-12e2-4d76-ac0e-a147aaf05baa   1Gi        RWO            freenas-iscsi-csi   11m   Filesystem
```

From the readme:
```md
# Ensure that open-iscsi and multipath-tools are enabled and running
sudo systemctl status multipath-tools
sudo systemctl enable open-iscsi.service
sudo service open-iscsi start
sudo systemctl status open-iscsi
```

```sh
sudo systemctl status open-iscsi
○ open-iscsi.service - Login to default iSCSI targets
     Loaded: loaded (/lib/systemd/system/open-iscsi.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
  Condition: start condition failed at Tue 2022-11-01 17:30:56 UTC; 4h 7min ago
             ├─ ConditionDirectoryNotEmpty=|/etc/iscsi/nodes was not met
             └─ ConditionDirectoryNotEmpty=|/sys/class/iscsi_session was not met
       Docs: man:iscsiadm(8)
             man:iscsid(8)

Nov 01 14:02:36 [user] systemd[1]: Condition check resulted in Login to default iSCSI targets being skipped.
Nov 01 17:18:49 [user] systemd[1]: Condition check resulted in Login to default iSCSI targets being skipped.
Nov 01 17:19:27 [user] systemd[1]: Condition check resulted in Login to default iSCSI targets being skipped.
Nov 01 17:29:02 [user] systemd[1]: Condition check resulted in Login to default iSCSI targets being skipped.
Nov 01 17:30:56 [user] systemd[1]: Condition check resulted in Login to default iSCSI targets being skipped.
```

So my question really boils down to: what to do? Will everything work as expected, or do I have to fix it?

I saw [this previous issue](https://github.com/democratic-csi/democratic-csi/issues/86) mentioned the same problem, but [deefdragon](https://github.com/deefdragon) never mentioned what he did to resolve it.

[travisghansen](https://github.com/travisghansen) commented that successfully running iscsid is all that really matters, but then why does the readme insist on running and verifying open-iscsi? My iscsid status:
```sh
sudo service iscsid status
○ iscsid.service - iSCSI initiator daemon (iscsid)
     Loaded: loaded (/lib/systemd/system/iscsid.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
``` 

PS: Thanks for working on this awesome project! Gotta love the TrueNAS API integration by the way!

**Comment by travisghansen** [comment]
Welcome! Run `iscsiadm -m session` to make sure the daemon is running. The other ensures the daemon is running and starts connections that you would create in a more static/traditional setup (ie: manually configured targets, etc). In the case of k8s volumes that is generally undesirable (and indeed when I setup the targets I ensure the autostart feature is forced to off anyhow for k8s targets).

**Comment by etokheim** [comment]
Thanks for the quick reply, @travisghansen!

Running `iscsiadm` tells me there's no active sessions. Should there be?
```sh
$ iscsiadm -m session
iscsiadm: No active sessions.
```

**Comment by travisghansen** [comment]
Nope (unless you’ve tried attaching). I think you should be good to go at this point.

**Comment by etokheim** [comment]
Amazing! Thanks a lot for the help, @travisghansen!

I would suggest adding a note in the readme, but apart from that, you can just close this issue. Have a nice day!

**Comment by heralight** [comment]
You can fix this issue by launching :
```sh
sudo iscsiadm -m discoverydb -t st -p yourcsi-ip --discover
```
sudo service open-iscsi stop
sudo service open-iscsi start
sudo systemctl status open-iscsi
