### ISSUE TITLE
Using Velero with Truenas/Freenas CSI

### ISSUE THREAD

**Issue by Tony-The-Developer** [democratic-csi/democratic-csi#248]
Hello,

I am wondering how I can use Velero to move data from one cluster to another. I have never done snapshots on the CSI so I dont really know what I am doing. Any help would be appreciated.

**Comment by Tony-The-Developer** [comment]
Ok cool. Is there a good tutorial I can follow or if you have the config files I can use. Thanks.

**Comment by travisghansen** [comment]
There's nothing specific to democratic-csi needed no.
