### ISSUE TITLE
Zvol parent is not a filesystem

### ISSUE THREAD

**Issue by djjudas21** [democratic-csi/democratic-csi#25]
Hi there. I'm new to iSCSI and I'm trying to set up this provisioner with microk8s and TrueNAS 12. I followed the tips in #21 and I've got past but I'm stuck on what value to supply for `datasetParentName`. Everything I try gives me this error when provisioning:

```
2020-12-01T16:19:37.315136901Z stderr F I1201 16:19:37.314898       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"camerahub-preprod", Name:"postgres-postgres-0", UID:"70e15e1f-d92b-4514-942f-3afe9b7c73b3", APIVersion:"v1", ResourceVersion:"2390193", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "freenas-iscsi-csi": rpc error: code = Internal desc = Error: cannot create 'default/iscsi/k8s/pvc-70e15e1f-d92b-4514-942f-3afe9b7c73b3': parent is not a filesystem
```

I have tried values of `default/iscsi`, `default/iscsi/k8s`, `iscsi`, `k8s` and none of them are correct. I don't fully understand ZFS and iSCSI, but I think I've got it set up with a zvol `default/iscsi`:

![pools](https://user-images.githubusercontent.com/604595/100768087-65ec0180-33f2-11eb-9097-320da7714b26.png)

Which contains an extent `k8s`:
![extent](https://user-images.githubusercontent.com/604595/100768085-65536b00-33f2-11eb-9721-d1fc32a5814f.png)

Please could you suggest the correct value based on my setup?

**Comment by travisghansen** [comment]
@djjudas21 hey! Welcome to the project! I've actually been doing a lot of hacking the last week or so and have many many fixes to work-around issues with the FreeNAS API. I *think* I'm about to workaround the last of them and get ready to snap a '1.0' version of this project.

To your specific issue, delete the `default/iscsi` volume. And then set your `datasetParentName` to `default/k8s/i/v` and then set the `detachedSnapshotsDatasetParentName` to `default/k8s/i/s`

Use those above specifically (or change them but make sure they do not overlap (ie: don't put `s` 'below' `v`) and make sure they are total <= 17 chars).

Don't worry about creating `k8s/...` datasets, the app will do that for you.

Remove any extents/targets/etc you have created. Simply make sure you've setup a port and group and put the correct IDs in your config. From there the controller will created all the assets and destroy them if/when appropriate.

Give it a whirl and let me know how it goes!

**Comment by djjudas21** [comment]
@travisghansen thanks for the welcome :)

So I followed your advice, cleaned up the iSCSI bits in TrueNAS that I manually set up and used your values for `datasetParentName` verbatim. It got a lot further but now is getting stuck here:

```
2020-12-01T21:12:18.51225472Z stderr F I1201 21:12:18.512032       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"camerahub-preprod", Name:"postgres-postgres-0", UID:"5cad3f98-a1cc-4554-8026-a4c84b104664", APIVersion:"v1", ResourceVersion:"2470206", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "freenas-iscsi-csi": rpc error: code = Unknown desc = received error creating iscsi target - code: 422 body: {"iscsi_target_create.groups.0.portal":[{"message":"1 Portal not found in database","errno":22}],"iscsi_target_create.groups.0.initiator":[{"message":"1 Initiator not found in database","errno":22}]}
```

**Comment by travisghansen** [comment]
Have you created a portal and initiator group manually? Just create a portal and set the authorization to none, and create an initiator group and just check 'allow all initiators'.  Note the ID for both (likely `1`) and make sure it matches what's in your config file for this project...

**Comment by djjudas21** [comment]
OK, I'll try that. Thanks

**Comment by djjudas21** [comment]
Success! Thanks for your help. I'll close this issue as it was really a support ticket in disguise, but I'll watch the project and try the new release when you've tagged it :+1:

**Comment by djjudas21** [comment]
I guess the only thing that could be done is to improve the docs a bit to explain the confusing iSCSI terminology and/or how to configure TrueNAS

**Comment by travisghansen** [comment]
@djjudas21 yeah, better doc is always welcome and needed. Right now it assumes a bit of experience with iscsi beforehand but some tutorials would be helpful.

I'll re-open and we can review the doc jointly when it gets added to see if it's of more help to newcomers to iscsi.

**Comment by djjudas21** [comment]
@travisghansen so after getting this to work last night, I was experimenting with teardown/reprovision to get a feel for how it works before I put any valuable data in. I'm experimenting using a Postgres statefulset so I cleaned up and reprovisioned with

```
kubectl delete statefulset postgres
kubectl delete pvc postgres-0
# wait to see that the pod has terminated and iSCSI volumes are gone from TrueNAS
kubectl create -f .......
```

I noted new a iSCSI volume had been provisioned, but the pod fails to start with

```
Warning  FailedMount  9m30s (x308 over 10h)  kubelet  MountVolume.MountDevice failed for volume "pvc-8ad31704-956e-4a6c-84a6-16761e9c1c56" : rpc error: code = Internal desc = {"code":1,"stdout":"","stderr":"mke2fs 1.44.5 (15-Dec-2018)\next2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/sde is mounted.\n/dev/sde: Device or resource busy while setting up superblock\n"}
```

I was surprised to see a new device `/dev/sde` but it appears to be an iSCSI mount

```
[jonathan@zeus ~]$ hddtemp /dev/sde
/dev/sde: TrueNAS iSCSI Disk: 255°C
```

Should this have been cleaned up / unmounted?

**Comment by travisghansen** [comment]
Yeah it should be cleaned up. It should unmount the device, logout of the iscsi target, and delete any iscsi files/etc that are associated with the connection.

For each node there is a pod running as a daemonset. Find the democratic-csi pod associated to the node where that workload was running and if you watch the logs you should see it running all the commands etc.

**Comment by travisghansen** [comment]
I've added a few more notes about setting up iscsi in the server prep block. Not a tutorial but closing this for now.
