### ISSUE TITLE
Poor performance over freenas-nfs csi driver

### ISSUE THREAD

**Issue by knoxg** [democratic-csi/democratic-csi#251]
I'm seeing some poor performance of file operations within a k8s container using a freenas-nfs volume, e.g. 5 seconds to 'touch' a new file:

```
root@gitlab-79958f5dd7-xzzvd:/var/log/gitlab/test# time touch a.txt

real    0m5.560s
user    0m0.001s
sys     0m0.000s
```

I tried to get some performance data via 'dd', and can see 40-77 MB/sec when writing 500MB, which seems ok:

```
root@gitlab-79958f5dd7-xzzvd:/var/log/gitlab/test# dd if=/dev/zero of=test5.img bs=500M count=1 oflag=dsync
1+0 records in
1+0 records out
524288000 bytes (524 MB, 500 MiB) copied, 8.82374 s, 59.4 MB/s
```

however if I change the dd parameters to be write 512-byte blocks, then performance falls off a cliff to 0.2kB/s:
```
root@gitlab-79958f5dd7-xzzvd:/var/log/gitlab/test# dd if=/dev/zero of=test1.img bs=512 count=10 oflag=dsync
10+0 records in
10+0 records out
5120 bytes (5.1 kB, 5.0 KiB) copied, 25.1562 s, 0.2 kB/s
```

Are there any options / parameters I can modify to improve performance ? 

As a bit of background, I'm trying to get gitlab running in k8s and most operations appear to be timing out due to poor NFS performance.

NB: I saw the 'MountOptions' on this issue: https://github.com/democratic-csi/democratic-csi/issues/6#issuecomment-654303441
so tried setting these in my helm yaml:
```
  mountOptions:
  - noatime
  - nfsvers=4
  - rsize=16384
  - wsize=16384
```

but I don't think they're taking effect; from the k8s node the mounts are still using a large rsize/wsize:

```
$ cat /proc/mounts | grep gitlab
192.168.0.129:/mnt/raidvolume/k8s/bnekub02/nfs/volumes/pvc-15fc69e7-e5f0-4651-9532-14f0ef5dd2a9/logs /var/lib/kubelet/pods/6faa681a-bbfa-41b2-8ea1-a5c7f289b5fa/volume-subpaths/pvc-15fc69e7-e5f0-4651-9532-14f0ef5dd2a9/gitlab/1 nfs4 rw,noatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.0.131,local_lock=none,addr=192.168.0.129 0 0
```

but I dont think that's the problem either, tried connecting from another machine with a smaller rsize/wsize ( sudo mount -t nfs -o rsize=16485 -o wsize=14384  ... )  but still getting around 0.2 kB/s using `dd`

**Comment by travisghansen** [comment]
Welcome! Performance issues largely fall outside the scope of the driver as we simply mount etc using standard linux tooling. If you manually mount the share from another workstation (non k8s node perhaps) do you see the same performance characteristics?

It has been a while since I reviewed the mount options behavior but they likely only take effect for newly created volumes (copied to the PV at creation time essentially). I have a tool in the repo that should be used with great care to update a PV, but it may be easier to just delete and recreate if the installation of gitlab is new and testing anyway.

**Comment by knoxg** [comment]
Yep I'm also getting poor performance from a non-k8s node connecting via a manully constructed mount, but not sure what could be causing it, maybe it's a server-side config setting ?

This is just a weekend project for me so will try out some variations next weekend.

**Comment by knoxg** [comment]
For anyone else encountering this, I did a bit of googling and discovered that disabling sync on the dataset can speed up I/O operations. 

This isn't recommended for production workloads as it can lead to data corruption, but got me a bit further ( gitlab was able to create new projects OK, whereas it was timing out before )

To change the sync setting:
```
root@bnenas04:/# man zfsprops
root@bnenas04:/# zfs get all raidvolume/k8s/bnekub02/nfs/volumes/pvc-15fc69e7-e5f0-4651-9532-14f0ef5dd2a9 | grep sync
raidvolume/k8s/bnekub02/nfs/volumes/pvc-15fc69e7-e5f0-4651-9532-14f0ef5dd2a9  sync   standard   default
root@bnenas04:/# zfs set sync=disabled raidvolume/k8s/bnekub02/nfs/volumes/pvc-15fc69e7-e5f0-4651-9532-14f0ef5dd2a9
root@bnenas04:/# zfs get all raidvolume/k8s/bnekub02/nfs/volumes/pvc-15fc69e7-e5f0-4651-9532-14f0ef5dd2a9 | grep sync
raidvolume/k8s/bnekub02/nfs/volumes/pvc-15fc69e7-e5f0-4651-9532-14f0ef5dd2a9  sync   disabled                              
```

After making this change, the `dd` test from within the container went form 25 seconds to 0.005 sec:
```
root@gitlab-79958f5dd7-j9rbh:/var/log/gitlab/test#  dd if=/dev/zero of=test3.img bs=512 count=10 oflag=dsync
10+0 records in
10+0 records out
5120 bytes (5.1 kB, 5.0 KiB) copied, 0.00403972 s, 1.3 MB/s
```

Disabling the sync is dangerous, so I'm looking into installing a small optane NVMe drive on a PCIe board in my nas to provide a low-latency SLOG ( separate ZFS intent log device ), which is supposed to give me good performance whilst retaining some safety guarantees around the data.

Some refs:
* https://www.servethehome.com/what-is-the-zfs-zil-slog-and-what-makes-a-good-one/
* https://hothardware.com/news/heads-up-nvme-ssds-lose-data-power-goes-out 
* https://www.reddit.com/r/zfs/comments/u0o5le/why_shouldnt_i_use_a_regular_nvme_drive_as_a_slog/

**Comment by knoxg** [comment]
And as a followup to that, after installing and configuring the optane NVMe to be used as a SLOG, I was able to re-enable sync on the dataset:

```
root@bnenas04:~# zfs inherit -Sr sync raidvolume/k8s/bnekub02/nfs/volumes/pvc-15fc69e7-e5f0-4651-9532-14f0ef5dd2a9
root@bnenas04:~# zfs get all raidvolume/k8s/bnekub02/nfs/volumes/pvc-15fc69e7-e5f0-4651-9532-14f0ef5dd2a9 | grep sync
raidvolume/k8s/bnekub02/nfs/volumes/pvc-15fc69e7-e5f0-4651-9532-14f0ef5dd2a9  sync   standard   default
```

whilst still maintaining those improved dd stats:

```
root@gitlab-79958f5dd7-j9rbh:/var/log/gitlab/test# dd if=/dev/zero of=test4.img bs=512 count=10 oflag=dsync
10+0 records in
10+0 records out
5120 bytes (5.1 kB, 5.0 KiB) copied, 0.00714309 s, 717 kB/s
```
So not quite as fast as with sync disabled, but a whole lot faster than the 0.2 kB/s I was getting the other day, and I'm much more confident that writes aren't going to be lost.

**Comment by travisghansen** [comment]
That still seems super slow to me. I’ll do a little test on my system and send over the results. My system is already quite busy but I’ll venture I can still get more than that but will let you know (I do have an nvme slog in my setup as well).

**Comment by knoxg** [comment]
OK thanks. Note the dd settings on that test were for tiny blocks ( 512 bytes ), if I bump it up to a larger bs value I get better throughput (72MB/s vs 717 kB/s above):

```root@gitlab-79958f5dd7-j9rbh:/var/log/gitlab/test# dd if=/dev/zero of=test4.img bs=500M count=1 oflag=dsync
1+0 records in
1+0 records out
524288000 bytes (524 MB, 500 MiB) copied, 7.24881 s, 72.3 MB/s
```

**Comment by travisghansen** [comment]
Ah fair enough!
