### ISSUE TITLE
truenas-nfs: Am I suppose to manually clean up unused provisioned datasets?

### ISSUE THREAD

**Issue by alex-geometry** [democratic-csi/democratic-csi#253]
I am using truenas-nfs.
If I deleted PVC, and corresponding pv automatically gone. But I can still see nfs datasets in truenas. Am I supposed to leave it there or manually clean it up?

**Comment by travisghansen** [comment]
Yeah it should clean up the datasets and share configuration as well unless the reclaim policy is set to retain.
