### ISSUE TITLE
Question: how to customize the zfs/nfs generated dataset name to include namespace+ pvc name?

### ISSUE THREAD

**Issue by titou10titou10** [democratic-csi/democratic-csi#255]
Q:
- is there a way to configure the name of the created zfs dataset name (and derived nfs share) to include the namespace/pvc related name?
- if so why. democratic-csi is installed via Helm

Currently the name of the zfs volume is`"pvc-<pv uuid>"`
I know it is possible to change the static prefix "pvc-" by some static string
I would like to have the dataset name to be `"<namespace>-<pvc name>-<uuid>"` (of course truncated to the max possible length)

Current config:
- Truenas v13.0-U3
- OpenShift v4.11 (k8s v1.24.6)
- democratic-csi image v1.7, csi-provisioner v3.1.0...

**Comment by travisghansen** [comment]
Short answer is no, mostly because csi is container system agnostic and namespace and pvc etc are specifically k8s constructs. While it is technically feasible some of the ramifications are too much from a support standpoint that I’ve never added support :(

You can set the description on both the dataset and the share however using namespace/name etc.

https://github.com/democratic-csi/democratic-csi/blob/master/examples/freenas-nfs.yaml#L43

https://github.com/democratic-csi/democratic-csi/blob/master/examples/freenas-nfs.yaml#L61

**Comment by titou10titou10** [comment]
@travisghansen thanks for the answer. 

For the nfs share and zfs datasets comments, I already use the tags you pointed out

As for the dataset naming, I understand your point but the "base" dataset name is "forged" somewhere  in the democratic-csi code (it is currently equal to the PV UUID), and passed downstream to the various CSI "actors" : provisioner, resizer, snapshotter etc

In what way would it be difficult to change this base name  before calling the others components and use the same technique as for the nfs/zfs share/dataset comments to override the name before calling them?

It could be something like

    driver:
      config:
        baseNamePrefix: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"

The`baseNamePrefix`could be prepend to the PV UUID, trim to 46 bytes and then passed downstream to the other components. If null, then nothing is prepend and things stay as for now
As a result, the name of the dataset would be`"pvc-<namespace>-<pvcname>-<pv uuid>"` 

"pvc" being the default CSI prefix, it can be currently be overriden for each CSI component like

    controller:
      externalProvisioner:
        extraArgs:
          - volumeNamePrefix: "abcd"

WDYT?

(I tried to check the code to see where the calls to the downstream actors paiing the base volumeid name happens without success...)

**Comment by travisghansen** [comment]
I really wish it were more feasible, there are just too many considerations that make it unlikely. The whole driver is stateless (meaning, I don't use some sort of database or similar to store data so most operations are implicit based off of names provided by the container orchestration system to the various methods defined in the spec) which leads to some tricky things. As an example, the csi spec limits strings to 128 bytes (https://github.com/container-storage-interface/spec/blob/master/spec.md#size-limits) so things like the `volume_id` must be limited to that length. In k8s a namespace is capped at 64 chars while resources (PVC) can reach 253 (PVC may have some other limits, but the principle remains) so in your example `"pvc-<namespace (up to 64)>-<pvcname (up to 253)>-<pv uuid>"` there's the potential for **much** larger than what is allowed by the spec.

A way around this would be to introduce a database that could store all kinds of things...but that adds a massive degree of complexity to the system not to mention a catch 22 situation where storage is needed for the very thing you want providing storage (from a k8s cluster perspective...how do I get a PVC for the driver if the driver is the thing providing PVC storage). Of course a server-side service could be created to make that happen as well, but again further complexity and higher barrier to entry for folks getting started :(

The driver itself never calls anything 'downstream' FYI, it only responds to rpc calls from those various actors.

**Comment by titou10titou10** [comment]
Thanks for your answer

I naively thought that generating a`volume_id`based on`shorten(pvc_namespace+pvc_name+name)`in the`CreateVolume` method executed when the volume is created would do the trick as this is`volume_id`that is received with the other lifecycle calls (eg`DeleteVolume`) by the CSI engine after the volume is created. There is already a`driver.getVolumeIdFromName`method that take care of generating a volume_id:

https://github.com/democratic-csi/democratic-csi/blob/7233bde497271c6a5bac13e757103313ef442359/src/driver/freenas/api.js#L2180

Also the`iscsi`implementation do that via the`iscsi.nameTemplate`parameter that dynamically sets the name of the iSCSI extents/target/zvol in TrueNAS
    
    iscsi:
        nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}

Anyway, thanks for your answer. 

I'll close soon this issue except if you want to keep it as a feature request...

I'm currently evaluating the possibility to create on my side a very specialized  TrueNAS v13+/k8s v1.23+/Filesystem only/NFS CSI driver with this feature and some others from my current non-CSI provisionner: [nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner) (like the possibility to 'archive' -ie rename instead of delete- the dataset when deleted)

**Comment by travisghansen** [comment]
Yeah, iscsi has different limits for sizes etc (none of which are directly impacted by csi limits) making it less of an issue. In that case I use zfs props to store all that info as a quasi database, but I need to know the exact volume/dataset before I can get the props.

Regarding the volumeidfromname code, that works but the other methods which pass the id around don’t pass in the same parameters so I can’t deconstruct it :( the id must be the dataset name by my own convention (due to not having any kind of database).

I’m happy to leave this open. I would even be open to perhaps an entirely new ‘driver’ being introduced in the codebase which could meet your needs. I’m also open to introducing a soft delete to the existing drivers (although that normally would just be setting retain on storage class).

Also if it’s easier you can hit me up on slack/discord/whatever to have a more thorough discussion!

**Comment by d-uzlov** [comment]
Sorry, I'm not familiar with CSI API, and I may have misunderstood the conversation here.

Is the length of the name the only issue?
Could the driver simply return an error if the name is too long?
User will see the error and figure out that they need to use a shorter name for namespace/PVC/whatever-else.

**Comment by travisghansen** [comment]
There are many other reasons. As mentioned many of the csi methods only pass the volume id without the name/namespace. I would recommend setting some custom zfs properties with name/namespace if that's of any help.
