### ISSUE TITLE
Can't launch on K0s distribution

### ISSUE THREAD

**Issue by diogodias24** [democratic-csi/democratic-csi#257]
Hello, 

I'm getting a `MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry is not a directory` whenever I'm trying to spin up a iscsi. The container is the node one. The folder don't exist:

![image](https://user-images.githubusercontent.com/35083226/207711522-45649af5-ae5a-4ca6-9912-ecdc8b35303b.png)

Tried to do this:
`mkdir -p /var/lib/kubelet/plugins_registry`
(I know, not ideal)

Afterwards:
`Liveness probe failed: F1214 21:14:02.986052 34 main.go:159] Kubelet plugin registration hasn't succeeded yet, file=/var/lib/kubelet/plugins/org.democratic-csi.iscsi/registration doesn't exist.`

Using here:

* Debian 11
* K0s v1.25.4+k0s.0

Interesting enough, as it is right now the volume got created on truenas.

Any ideas?

**Comment by diogodias24** [comment]
> Hello,
> 
> I'm getting a `MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry is not a directory` whenever I'm trying to spin up a iscsi. The container is the node one. The folder don't exist:
> 
> ![image](https://user-images.githubusercontent.com/35083226/207711522-45649af5-ae5a-4ca6-9912-ecdc8b35303b.png)
> 
> Using here:
> 
> * Debian 11
> * K0s v1.25.4+k0s.0
> 
> Any ideas on this?

Maybe it's enough to just do this?
`mkdir -p /var/lib/kubelet/plugins_registry`

Seems like container is spinning up after running this command. Any downside on doing it like this?

**Comment by travisghansen** [comment]
Does k0s use a non-standard kubelet data dir?

**Comment by diogodias24** [comment]
Hum I think so:

Accordingly to this, they use their own path:
https://github.com/k0sproject/k0s/issues/1842

But I think there's a way to tell what is going to be the default on the cluster configmap. Is there a option on your helm chart to give It a different path?

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/democratic-csi#a-note-on-non-standard-kubelet-paths

Check that out and let me know how it goes. If it fixes we can explicitly add k0s to the examples.

**Comment by kimattree** [comment]
I got this working by exporting a helm template:

`helm template --values values.yaml --namespace truenas-csi zfs-iscsi democratic-csi/democratic-csi > truenas-csi.yaml`

then just changing any instances of /var/lib/kubelet to /var/lib/k0s/kubelet:

`sed -i 's#/var/lib/kubelet#/var/lib/k0s/kubelet#g' truenas-csi.yaml`

and then just applied normally with kubectl - I get registration now and volume binding through the CSI Driver:


```
2
I1227 11:35:45.118981       1 main.go:109] "Kubelet registration probe created" path="/var/lib/k0s/kubelet/plugins/org.democratic-csi.iscsi/registration"
1
I1227 11:35:45.218440       1 main.go:120] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
```

**Comment by travisghansen** [comment]
There is a value in the chart that will handle that: https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L215

**Comment by kimattree** [comment]
Even better thanks @travisghansen +1

**Comment by travisghansen** [comment]
I've updated the doc to include the specific `k0s` path so the next release will include it.
