### ISSUE TITLE
local-dataset provisioner can't watch CSIStorageCapacity because csi.storage.k8s.io/managed-by too long

### ISSUE THREAD

**Issue by mattlqx** [democratic-csi/democratic-csi#259]
I have [this config](https://gist.github.com/mattlqx/aa10ed0da5d0101d79e574b3351e4e28) that I'm using for Helm values for deploying democratic-csi.

When I try to create this PVC (via kubevirt's virtctl), 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/storage.contentType: kubevirt
    cdi.kubevirt.io/storage.upload.target: ""
    volume.beta.kubernetes.io/storage-provisioner: org.democratic-csi.zfs-local-dataset
    volume.kubernetes.io/storage-provisioner: org.democratic-csi.zfs-local-dataset
  creationTimestamp: "2023-01-04T00:37:52Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: virtio-win-0.1.225-1
  namespace: kubevirt
  resourceVersion: "35268214"
  uid: b7b7b016-cc81-4f60-ad8b-5a8cb9323928
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: zfs-local-dataset
  volumeMode: Filesystem
status:
  phase: Pending
```

I'm getting this in the external-provisioner container logs of the democratic-csi-zfs-node daemonset:

```
W0104 00:55:11.362048       1 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1beta1.CSIStorageCapacity: unable to parse requirement: values[0][csi.storage.k8s.io/managed-by]: Invalid value: "external-provisioner-ip-172-21-113-94.us-west-2.compute.internal": must be no more than 63 characters
E0104 00:55:11.362079       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: unable to parse requirement: values[0][csi.storage.k8s.io/managed-by]: Invalid value: "external-provisioner-ip-172-21-113-94.us-west-2.compute.internal": must be no more than 63 characters
```

Indicating that the label value is invalid because it's too long. I've tried renaming the container to something other than `external-provisioner` but it still produces the same error. I'm also not sure if this is the true issue as to why the dataset/PV isn't being created but this is the only real error I can find. The PVC events just say "waiting for a volume to be created, either by external provisioner "org.democratic-csi.zfs-local-dataset" or manually created by system administrator".

**Comment by travisghansen** [comment]
This issue appears to be related to the k8s tooling installed alongside the driver. Let me get some other eyes in it and then I’ll shout back out.

**Comment by pohly** [comment]
Which version of the external-provisioner is getting deployed here? A fix for this was added in https://github.com/kubernetes-csi/external-provisioner/pull/717 which went into releases >= 3.2.0. It was backported into 3.1.1.

**Comment by travisghansen** [comment]
Thanks @pohly! It looks like my chart is defaulting to 3.1.0 still. @mattlqx can you bump the version using this and let us know how it goes? https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L92

**Comment by mattlqx** [comment]
Thanks for the quick responses. No change in behavior though.

```
I0104 15:11:24.498949       1 reflector.go:255] Listing and watching *v1beta1.CSIStorageCapacity from k8s.io/client-go/informers/factory.go:134                                             
W0104 15:11:24.509789       1 warnings.go:70] storage.k8s.io/v1beta1 CSIStorageCapacity is deprecated in v1.24+, unavailable in v1.27+; use storage.k8s.io/v1 CSIStorageCapacity            
W0104 15:11:24.509943       1 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1beta1.CSIStorageCapacity: unable to parse requirement: values[0][csi.storage.k8s.io/managed-by]: Invalid value: "external-provisioner-ip-172-21-113-94.us-west-2.compute.internal": must be no more than 63 characters                                                                          
E0104 15:11:24.509982       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: unable to parse requirement: values[0][csi.storage.k8s.io/managed-by]: Invalid value: "external-provisioner-ip-172-21-113-94.us-west-2.compute.internal": must be no more than 63 characters                             
I0104 15:11:25.449083       1 controller.go:1299] should provision: checking node for PVC dropsuite/virtio-win-0.1.225-1 with resource version 35854760                                     
I0104 15:11:25.449107       1 controller.go:1301] should provision: done checking node for PVC dropsuite/virtio-win-0.1.225-1 with resource version 35854760: provision false, err <nil> 
```

Running these images in the pod:
```
cleanup               ●  docker.io/busybox:1.32.0
csi-driver            ●  docker.io/democraticcsi/democratic-csi:latest
csi-proxy             ●  docker.io/democraticcsi/csi-grpc-proxy:v0.5.3
driver-registrar      ●  k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.1
external-provisioner  ●  k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
external-snapshotter  ●  k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
```

I also tried the release version, democraticcsi/democratic-csi:v1.7.7.

**Comment by mattlqx** [comment]
Oh, 3.2.0 is what I should be running. Sorry, glanced too quick at that. Will try now.

**Comment by travisghansen** [comment]
Or 3.1.1 if anything is incompatible for whatever reason with 3.2.x

**Comment by mattlqx** [comment]
🎉  Yay, it's working.

I'm using 3.1.1 and that resolved the API failures. I had to change a few other things to get it working for my use-case.

1. Change the volume binding to Immediate and toggle the flag on the external-provisioner for it. (Kubevirt expects the PV to exist before it creates the importer pod.)
2. Add the pool volume mount to the extraMounts for the external-provisioner. Otherwise, it choked because it didn't have access to the FS to chmod.

Again, really appreciate the responses!
