### ISSUE TITLE
TrueNAS Scale volumes not created, RPC error claims already exists

### ISSUE THREAD

**Issue by dakaix** [democratic-csi/democratic-csi#264]
I've been building a new Microk8s cluster, and have deployed a few apps utilising NFS PVC's backed by TrueNAS Scale. These first applications have gone smoothly - however I am now trying to deploy an application ([EmonCMS](https://github.com/jutonz/emoncms-helm), with some tweaks to the API version strings) that uses 5 PVC's, and suddenly the volumes are failing to be created. 

Oddly the error returned is that they already exist (which they don't), yet have a null size. I have tried to turn on debug in the chart values.yaml, but haven't found much more information to go on. Can anyone point me in the right direction?

# PVC Manifests
```# Source: emoncms/templates/emoncmsdocker-emon-db-data-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emoncms-db-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: freenas-nfs-csi-api
  resources:
    requests:
      storage: 10Gi
---
# Source: emoncms/templates/emoncmsdocker-emon-phpfina-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emoncms-phpfina
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: freenas-nfs-csi-api
  resources:
    requests:
      storage: 10Gi
---
# Source: emoncms/templates/emoncmsdocker-emon-phpfiwa-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emoncms-phpfiwa
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: freenas-nfs-csi-api
  resources:
    requests:
      storage: 30Gi
---
# Source: emoncms/templates/emoncmsdocker-emon-phptimeseries-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emoncms-phptimeseries
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: freenas-nfs-csi-api
  resources:
    requests:
      storage: 10Gi
---
# Source: emoncms/templates/emoncmsdocker-emon-redis-data-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emoncms-redis-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: freenas-nfs-csi-api
  resources:
    requests:
      storage: 100Mi
```

# Namespace Events
`LAST SEEN              TYPE      REASON                 OBJECT                                        MESSAGE
4m49s                  Warning   FailedScheduling       Pod/redis-754f5b8654-krswq                    0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod..
4m49s                  Warning   FailedScheduling       Pod/db-5cc4c96676-mmcls                       0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod..
4m49s                  Warning   FailedScheduling       Pod/web-7dcf9dd587-clmfm                      0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod..
4m14s (x26 over 10m)   Normal    ExternalProvisioning   PersistentVolumeClaim/emoncms-redis-data      waiting for a volume to be created, either by external provisioner "org.democratic-csi.nfs-api" or manually created by system administrator
4m14s (x26 over 10m)   Normal    ExternalProvisioning   PersistentVolumeClaim/emoncms-phpfina         waiting for a volume to be created, either by external provisioner "org.democratic-csi.nfs-api" or manually created by system administrator
4m14s (x26 over 10m)   Normal    ExternalProvisioning   PersistentVolumeClaim/emoncms-db-data         waiting for a volume to be created, either by external provisioner "org.democratic-csi.nfs-api" or manually created by system administrator
4m14s (x26 over 10m)   Normal    ExternalProvisioning   PersistentVolumeClaim/emoncms-phptimeseries   waiting for a volume to be created, either by external provisioner "org.democratic-csi.nfs-api" or manually created by system administrator
4m14s (x26 over 10m)   Normal    ExternalProvisioning   PersistentVolumeClaim/emoncms-phpfiwa         waiting for a volume to be created, either by external provisioner "org.democratic-csi.nfs-api" or manually created by system administrator
96s (x10 over 10m)     Normal    Provisioning           PersistentVolumeClaim/emoncms-phpfiwa         External provisioner is provisioning volume for claim "emoncms/emoncms-phpfiwa"
96s (x10 over 10m)     Warning   ProvisioningFailed     PersistentVolumeClaim/emoncms-phpfiwa         failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 32212254720, limit_bytes: 0
96s (x10 over 10m)     Normal    Provisioning           PersistentVolumeClaim/emoncms-db-data         External provisioner is provisioning volume for claim "emoncms/emoncms-db-data"
96s (x10 over 10m)     Warning   ProvisioningFailed     PersistentVolumeClaim/emoncms-db-data         failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
95s (x10 over 10m)     Normal    Provisioning           PersistentVolumeClaim/emoncms-phptimeseries   External provisioner is provisioning volume for claim "emoncms/emoncms-phptimeseries"
95s (x10 over 10m)     Warning   ProvisioningFailed     PersistentVolumeClaim/emoncms-phptimeseries   failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
94s (x10 over 10m)     Normal    Provisioning           PersistentVolumeClaim/emoncms-phpfina         External provisioner is provisioning volume for claim "emoncms/emoncms-phpfina"
94s (x10 over 10m)     Warning   ProvisioningFailed     PersistentVolumeClaim/emoncms-phpfina         failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
94s (x10 over 10m)     Normal    Provisioning           PersistentVolumeClaim/emoncms-redis-data      External provisioner is provisioning volume for claim "emoncms/emoncms-redis-data"
94s (x10 over 10m)     Warning   ProvisioningFailed     PersistentVolumeClaim/emoncms-redis-data      failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 104857600, limit_bytes: 0`

# CSI Controller Log
`II0114 02:00:16.289914       1 controller.go:1337] provision "emoncms/emoncms-phpfiwa" class "freenas-nfs-csi-api": started
W0114 02:00:16.291278       1 controller.go:579] "fstype" is deprecated and will be removed in a future release, please use "csi.storage.k8s.io/fstype" instead
I0114 02:00:16.291425       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"emoncms", Name:"emoncms-phpfiwa", UID:"fa22514b-5ab5-4c70-bb64-e74ae8120f1e", APIVersion:"v1", ResourceVersion:"1489820", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "emoncms/emoncms-phpfiwa"
I0114 02:00:16.312792       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateVolume
I0114 02:00:16.312913       1 connection.go:184] GRPC request: {"capacity_range":{"required_bytes":32212254720},"name":"pvc-fa22514b-5ab5-4c70-bb64-e74ae8120f1e","parameters":{"csi.storage.k8s.io/pv/name":"pvc-fa22514b-5ab5-4c70-bb64-e74ae8120f1e","csi.storage.k8s.io/pvc/name":"emoncms-phpfiwa","csi.storage.k8s.io/pvc/namespace":"emoncms","fsType":"nfs"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"nfs","mount_flags":["noatime","nfsvers=4"]}},"access_mode":{"mode":7}}]}
I0114 02:00:16.403636       1 connection.go:186] GRPC response: {}
I0114 02:00:16.405030       1 connection.go:187] GRPC error: rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 32212254720, limit_bytes: 0
I0114 02:00:16.406177       1 controller.go:764] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 32212254720, limit_bytes: 0
I0114 02:00:16.407947       1 controller.go:1075] Final error received, removing PVC fa22514b-5ab5-4c70-bb64-e74ae8120f1e from claims in progress
W0114 02:00:16.409079       1 controller.go:934] Retrying syncing claim "fa22514b-5ab5-4c70-bb64-e74ae8120f1e", failure 9
I0114 02:00:16.410094       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"emoncms", Name:"emoncms-phpfiwa", UID:"fa22514b-5ab5-4c70-bb64-e74ae8120f1e", APIVersion:"v1", ResourceVersion:"1489820", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 32212254720, limit_bytes: 0
E0114 02:00:16.411483       1 controller.go:957] error syncing claim "fa22514b-5ab5-4c70-bb64-e74ae8120f1e": failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 32212254720, limit_bytes: 0
I0114 02:00:16.571035       1 controller.go:1337] provision "emoncms/emoncms-db-data" class "freenas-nfs-csi-api": started
W0114 02:00:16.571914       1 controller.go:579] "fstype" is deprecated and will be removed in a future release, please use "csi.storage.k8s.io/fstype" instead
I0114 02:00:16.573993       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"emoncms", Name:"emoncms-db-data", UID:"e8afccea-82b0-4878-856f-27b22f88d347", APIVersion:"v1", ResourceVersion:"1489822", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "emoncms/emoncms-db-data"
I0114 02:00:16.606658       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateVolume
I0114 02:00:16.606890       1 connection.go:184] GRPC request: {"capacity_range":{"required_bytes":10737418240},"name":"pvc-e8afccea-82b0-4878-856f-27b22f88d347","parameters":{"csi.storage.k8s.io/pv/name":"pvc-e8afccea-82b0-4878-856f-27b22f88d347","csi.storage.k8s.io/pvc/name":"emoncms-db-data","csi.storage.k8s.io/pvc/namespace":"emoncms","fsType":"nfs"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"nfs","mount_flags":["noatime","nfsvers=4"]}},"access_mode":{"mode":7}}]}
I0114 02:00:16.629332       1 leaderelection.go:278] successfully renewed lease democratic-csi/org-democratic-csi-nfs-api
I0114 02:00:16.675742       1 connection.go:186] GRPC response: {}
I0114 02:00:16.675950       1 connection.go:187] GRPC error: rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0114 02:00:16.676045       1 controller.go:764] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0114 02:00:16.676225       1 controller.go:1075] Final error received, removing PVC e8afccea-82b0-4878-856f-27b22f88d347 from claims in progress
W0114 02:00:16.676297       1 controller.go:934] Retrying syncing claim "e8afccea-82b0-4878-856f-27b22f88d347", failure 9
E0114 02:00:16.676404       1 controller.go:957] error syncing claim "e8afccea-82b0-4878-856f-27b22f88d347": failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0114 02:00:16.676493       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"emoncms", Name:"emoncms-db-data", UID:"e8afccea-82b0-4878-856f-27b22f88d347", APIVersion:"v1", ResourceVersion:"1489822", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0114 02:00:17.080187       1 controller.go:1337] provision "emoncms/emoncms-phptimeseries" class "freenas-nfs-csi-api": started
W0114 02:00:17.119023       1 controller.go:579] "fstype" is deprecated and will be removed in a future release, please use "csi.storage.k8s.io/fstype" instead
I0114 02:00:17.122601       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"emoncms", Name:"emoncms-phptimeseries", UID:"e90a25a0-2646-4bfc-918d-acd6632b794f", APIVersion:"v1", ResourceVersion:"1489823", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "emoncms/emoncms-phptimeseries"
I0114 02:00:17.137440       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateVolume
I0114 02:00:17.137576       1 connection.go:184] GRPC request: {"capacity_range":{"required_bytes":10737418240},"name":"pvc-e90a25a0-2646-4bfc-918d-acd6632b794f","parameters":{"csi.storage.k8s.io/pv/name":"pvc-e90a25a0-2646-4bfc-918d-acd6632b794f","csi.storage.k8s.io/pvc/name":"emoncms-phptimeseries","csi.storage.k8s.io/pvc/namespace":"emoncms","fsType":"nfs"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"nfs","mount_flags":["noatime","nfsvers=4"]}},"access_mode":{"mode":7}}]}
I0114 02:00:17.451969       1 connection.go:186] GRPC response: {}
I0114 02:00:17.452735       1 connection.go:187] GRPC error: rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0114 02:00:17.452972       1 controller.go:764] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0114 02:00:17.454557       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"emoncms", Name:"emoncms-phptimeseries", UID:"e90a25a0-2646-4bfc-918d-acd6632b794f", APIVersion:"v1", ResourceVersion:"1489823", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0114 02:00:17.453528       1 controller.go:1075] Final error received, removing PVC e90a25a0-2646-4bfc-918d-acd6632b794f from claims in progress
W0114 02:00:17.454987       1 controller.go:934] Retrying syncing claim "e90a25a0-2646-4bfc-918d-acd6632b794f", failure 9
E0114 02:00:17.455129       1 controller.go:957] error syncing claim "e90a25a0-2646-4bfc-918d-acd6632b794f": failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0114 02:00:18.373552       1 controller.go:1337] provision "emoncms/emoncms-phpfina" class "freenas-nfs-csi-api": started
W0114 02:00:18.373878       1 controller.go:579] "fstype" is deprecated and will be removed in a future release, please use "csi.storage.k8s.io/fstype" instead
I0114 02:00:18.375236       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"emoncms", Name:"emoncms-phpfina", UID:"a29c5d6e-1a01-4ce3-9efc-6c76ef261730", APIVersion:"v1", ResourceVersion:"1489824", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "emoncms/emoncms-phpfina"
I0114 02:00:18.395981       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateVolume
I0114 02:00:18.396083       1 connection.go:184] GRPC request: {"capacity_range":{"required_bytes":10737418240},"name":"pvc-a29c5d6e-1a01-4ce3-9efc-6c76ef261730","parameters":{"csi.storage.k8s.io/pv/name":"pvc-a29c5d6e-1a01-4ce3-9efc-6c76ef261730","csi.storage.k8s.io/pvc/name":"emoncms-phpfina","csi.storage.k8s.io/pvc/namespace":"emoncms","fsType":"nfs"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"nfs","mount_flags":["noatime","nfsvers=4"]}},"access_mode":{"mode":7}}]}
I0114 02:00:18.465087       1 connection.go:186] GRPC response: {}
I0114 02:00:18.465445       1 connection.go:187] GRPC error: rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0114 02:00:18.465792       1 controller.go:764] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0114 02:00:18.466218       1 controller.go:1075] Final error received, removing PVC a29c5d6e-1a01-4ce3-9efc-6c76ef261730 from claims in progress
W0114 02:00:18.466462       1 controller.go:934] Retrying syncing claim "a29c5d6e-1a01-4ce3-9efc-6c76ef261730", failure 9
I0114 02:00:18.466852       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"emoncms", Name:"emoncms-phpfina", UID:"a29c5d6e-1a01-4ce3-9efc-6c76ef261730", APIVersion:"v1", ResourceVersion:"1489824", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
E0114 02:00:18.468827       1 controller.go:957] error syncing claim "a29c5d6e-1a01-4ce3-9efc-6c76ef261730": failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0114 02:00:18.498178       1 controller.go:1337] provision "emoncms/emoncms-redis-data" class "freenas-nfs-csi-api": started
W0114 02:00:18.498502       1 controller.go:579] "fstype" is deprecated and will be removed in a future release, please use "csi.storage.k8s.io/fstype" instead
I0114 02:00:18.500182       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"emoncms", Name:"emoncms-redis-data", UID:"2cf755a4-7073-4e17-8d5a-00a186fc351c", APIVersion:"v1", ResourceVersion:"1489821", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "emoncms/emoncms-redis-data"
I0114 02:00:18.529436       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateVolume
I0114 02:00:18.529665       1 connection.go:184] GRPC request: {"capacity_range":{"required_bytes":104857600},"name":"pvc-2cf755a4-7073-4e17-8d5a-00a186fc351c","parameters":{"csi.storage.k8s.io/pv/name":"pvc-2cf755a4-7073-4e17-8d5a-00a186fc351c","csi.storage.k8s.io/pvc/name":"emoncms-redis-data","csi.storage.k8s.io/pvc/namespace":"emoncms","fsType":"nfs"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"nfs","mount_flags":["noatime","nfsvers=4"]}},"access_mode":{"mode":7}}]}
I0114 02:00:18.627007       1 connection.go:186] GRPC response: {}
I0114 02:00:18.628164       1 connection.go:187] GRPC error: rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 104857600, limit_bytes: 0
I0114 02:00:18.628713       1 controller.go:764] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 104857600, limit_bytes: 0
I0114 02:00:18.629527       1 controller.go:1075] Final error received, removing PVC 2cf755a4-7073-4e17-8d5a-00a186fc351c from claims in progress
W0114 02:00:18.630200       1 controller.go:934] Retrying syncing claim "2cf755a4-7073-4e17-8d5a-00a186fc351c", failure 9
I0114 02:00:18.629934       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"emoncms", Name:"emoncms-redis-data", UID:"2cf755a4-7073-4e17-8d5a-00a186fc351c", APIVersion:"v1", ResourceVersion:"1489821", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 104857600, limit_bytes: 0
E0114 02:00:18.630831       1 controller.go:957] error syncing claim "2cf755a4-7073-4e17-8d5a-00a186fc351c": failed to provision volume with StorageClass "freenas-nfs-csi-api": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 104857600, limit_bytes: 0`

**Comment by travisghansen** [comment]
Can you send over the logs of the `csi-driver` container of the controller pod?

**Comment by travisghansen** [comment]
Also send over the helm values used to deploy (remove any sensitive details).

**Comment by dakaix** [comment]
**values.yaml**

**Comment by travisghansen** [comment]
So what was the resolution?

**Comment by dakaix** [comment]
> Can you send over the logs of the `csi-driver` container of the controller pod?
> Also send over the helm values used to deploy (remove any sensitive details).

Sure, both included below.
[Values.yaml](https://pastebin.com/Z3teqEVZ)
[csi-driver.log](https://pastebin.com/tM6kB5vG)

**Comment by travisghansen** [comment]
Can you send the values used for the democratic deployment?

**Comment by dakaix** [comment]
Here's the values from the NFS class registration:
[freenas-nfs-csi-api.yaml](https://pastebin.com/WaWTcgRq)

**Comment by travisghansen** [comment]
Redeploy with this set to `debug` https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml and then send the driver logs again 

and send over the output of `zfs list -r` including the relevant volume.

**Comment by dakaix** [comment]
Sorry, I'm a bit lost here. This was originally installed via the helm repo method in the community tutorial below, how can I safely redeploy this without risking the existing zfs-nfs PVC's that are being used?

https://www.lisenet.com/2021/moving-to-truenas-and-democratic-csi-for-kubernetes-persistent-storage/

**Comment by dakaix** [comment]
I added the node & controller debug lines into my existing zfs-nfs values, and ran a helm upgrade (rather than replacing it entirely with the template)... and annoyingly it has now seamlessly provisioned the EmonCMS PVC's immediately. I just reverted the logLevel back to info, and it still worked.

Very confused now what on earth I was doing differently last night - for now I'll blame the late hour!

**Comment by travisghansen** [comment]
Hmm, ok yeah upgrading the deployment won’t affect existing pvcs. There are certain things that cannot be altered such as the parent dataset values etc but most options can be updated. In addition I pretty staunchly maintain backwards compatibility of the configuration so updating to newer versions of the driver is perfectly safe and something that should be done over time as new releases are made.

**Comment by dakaix** [comment]
I'm still having issues with these volumes unfortunately, although they are being created it turns out on closer inspection that they're still not mounting properly. This is now affecting the other applications that were previously working.

kubectl events
> 5s (x6 over 22s)      Warning   FailedMount         Pod/node-red-5fb5755f4-7nrlx    MountVolume.SetUp failed for volume "pvc-1006b698-13c8-494d-9921-f44c5200ef08" : applyFSGroup failed for vol pvc-1006b698-13c8-494d-9921-f44c5200ef08: lstat /var/snap/microk8s/common/var/lib/kubelet/pods/c35d9a11-a3fb-4ea6-a7f7-a2e4a987683e/volumes/kubernetes.io~csi/pvc-1006b698-13c8-494d-9921-f44c5200ef08/mount: no such file or directory

[csi-driver node logs](https://pastebin.com/9qE6xgD1)

Any chance you can point me in the right direction here?

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/democratic-csi#a-note-on-non-standard-kubelet-paths

Looking at your helm values file it seems the above wasn’t addressed if you’re using microk8s. Let’s start with that.

**Comment by dakaix** [comment]
Thank you! It's looking **mucb** better now - both applications are now running. Really appreciate your patience! :)

**Comment by travisghansen** [comment]
Great! Run it through some rigorous tests and make sure it’s all working end to end.
