### ISSUE TITLE
Decoupeling Democratic-CSI deployment and secrets

### ISSUE THREAD

**Issue by D1StrX** [democratic-csi/democratic-csi#266]
Great! You can create the secret and just tell the chart where it is (ie: handle the secret entirely out helm).

_Originally posted by @travisghansen in https://github.com/democratic-csi/democratic-csi/issues/256#issuecomment-1385803403_

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L17-L26

**Comment by D1StrX** [comment]
Trying to take a deep(er) dive what happens when Democratic-csi is being deployed, using **_Helm_**. Main goal is to understand what is an individual component, like the extra-vars, secrets (partially driver config, storageclass parameters) and what is the core/bare-minimum deployment.

Here I am writing what I figured out and what is needed to get it to work. Also in the end what perhaps could be improved/remaining questions. In my adventure I was able to get it work, as a separate deployment next to an existing democratic-csi deployment.

- **Secrets**
     provisioner-secret:
     controller-publish-secret
     node-stage-secret
     node-publish-secret
     controller-expand-secret
    <release_name>-democratic-csi-driver-config
    
**To elaborate:**
Only the `<release_name>-democratic-csi-driver-config` is necessary. But the others are used in the StorageClass parameters (get to this later on in StorageClass):_
When deploying or upgrading the Helm release, it overrides the dirver-config.

- **Configmaps**
   extra-vars

**To elaborate:**
Helm install comes back with some prerequisites in order to use pre-deployed configmaps and secrets.
```
helm install <release_name> democratic-csi/democratic-csi --namespace <namespace> --values .\values.yml

Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install:
ConfigMap "<release_name>-democratic-csi" in namespace "<release_name>" exists and cannot be imported into the current release: 
invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "<release_name>"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "<release_name>"
```
Thus I _must_ annotate & label every secret & configmap to get it working with: 
(I am not labeling with helm.sh/chart: democratic-csi-0.13.5, app.kubernetes.io/instance: <release_name>, app.kubernetes.io/name: democratic_csi)
```
metadata:
  annotations:
    meta.helm.sh/release-name: <release_name>
    meta.helm.sh/release-namespace: <namespace>
  labels:
    app.kubernetes.io/managed-by: Helm
```
When deploying or upgrading the Helm release, it overrides the ConfigMap.

- **StorageClass**
  Just a new pre-created storageClass

**To elaborate:**
It _must_ contain these values, except the ones that have ** in front
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: <storageClass_name>
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: <provisioner_name>
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: <fstype>
  **csi.storage.k8s.io/controller-expand-secret-name: <secret_name>
  **csi.storage.k8s.io/controller-expand-secret-namespace: <namespace>
  **csi.storage.k8s.io/controller-publish-secret-name: <secret_name>
  **csi.storage.k8s.io/controller-publish-secret-namespace: <namespace>
  **csi.storage.k8s.io/node-publish-secret-name: <secret_name>
  **csi.storage.k8s.io/node-publish-secret-namespace: <namespace>
  **csi.storage.k8s.io/node-stage-secret-name: <secret_name>
  **csi.storage.k8s.io/node-stage-secret-namespace: <namespace>
  **csi.storage.k8s.io/provisioner-secret-name: <secret_name>
  **csi.storage.k8s.io/provisioner-secret-namespace: <namespace>
```

- **csiDriver**
  Automatically created.

**To elaborate:**
The csiDriver must not exist, otherwise it will say that it can't be created. Because it already exists. 

- **Values.yml**
  Helm values file.

**To elaborate:**
  The minimum required:
```
csiDriver:
  name: "<provisioner_name>"
  
driver:
  config:
    driver: freenas-api-iscsi
    instance_id:
```

**To elaborate:**
**csiDriver**
When not providing the `csiDriver` it will output this error on `helm install <release_name> democratic-csi/democratic-csi --namespace <namespace> --values .\values.yml` 

**driver**
When not providing the `driver` (even though the secret is created, but you want to specify to install a new csi_driver. (Because in the `driver` config you want the PV's being created on another dataset e.g.)) it will output this error (using same helm install command):
```
Error: INSTALLATION FAILED: template: democratic-csi/templates/node.yaml:5:19: executing "democratic-csi/templates/node.yaml" at <include "democratic-csi.mount-iscsi" .>: 
error calling include: template: democratic-csi/templates/_helpers.tpl:36:31: executing "democratic-csi.mount-iscsi" at <.Values.driver.config.driver>: wrong type for value; expected string; got interface {}
```

The remaining questions for me, for now:
When you do `helm upgrade <release_name> democratic-csi/democratic-csi --namespace <namespace> --values .\values.yml` it overrides the `<release_name>-democratic-csi-driver-config` .
Could this be fixed in the helm chart?
Could the pre-defined secrets definements in the values.yml be improved?
From working with other Helm charts (as enduser), they (like Bitnami or Gitlab) provide all options within the values.yml. Also to refer to existing secrets.

**Comment by D1StrX** [comment]
Also, the PR for the improved README.md in the `Next` branche is still open. (Guess you forgotten :) )

**Comment by travisghansen** [comment]
I'm not sure why you would be getting the secret overwritten: https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/templates/driver-config-secret.yaml#L1

The secrets used for parameters and essentially unused. I only set them long ago because they can't be updated *after* a PV is created, so I was hedging against the future potential use.

I haven't forgotten about the README etc, life took a wild turn for the past few months and I still haven't had a chance to fully dig in :( when things calm down and I don't have other priority items piled up I will revisit and provide feedback.

**Comment by D1StrX** [comment]
`I'm not sure why you would be getting the secret overwritten: https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/templates/driver-config-secret.yaml#L1`
helm upgrade <release_name> democratic-csi/democratic-csi --namespace <namespace> --values .\values.yml
I checked again, and the driver config secret is really overwritten. This is because of this necessary part in the values.yml:
```
driver:
  config:
    driver: freenas-api-iscsi
    instance_id:
```
Without it I cannot do helm upgrade and get this error instead:
```
Error: UPGRADE FAILED: template: democratic-csi/templates/node.yaml:5:19: executing "democratic-csi/templates/node.yaml" at <include "democratic-csi.mount-iscsi" .>: error calling include: template: democratic-csi/templates/_helpers.tpl:36:31: executing "democratic-csi.mount-iscsi" at <.Values.driver.config.driver>: wrong type for value; expected string; got interface {}
```

`The secrets used for parameters and essentially unused. I only set them long ago because they can't be updated after a PV is created, so I was hedging against the future potential use.`
Makes sense.

`I haven't forgotten about the README etc, life took a wild turn for the past few months and I still haven't had a chance to fully dig in :( when things calm down and I don't have other priority items piled up I will revisit and provide feedback.`
Good to hear you haven't forgotten, I hope your days gets better.

**Comment by travisghansen** [comment]
Use this syntax:

```
...
driver:
  existingConfigSecret: <your pre-created secret name here>
  config:
    driver: freenas-api-iscsi
...
```

Doing so will prevent the chart from managing the secret. You can even save the secret you have now and just create it manually from that if you wish. Note that when you manage the secret on your own it would be your responsibility to roll pods should the secret get updated. The chart does a checksum on the secret and show will automatically roll the pods should the secret change.

Alternatively, use https://github.com/jkroepke/helm-secrets or similar to continue letting helm manage it.

**Comment by D1StrX** [comment]
That works for the Driver part. The configmap doesn't need the following annotations & labels as well, I just figured.
```
  annotations:
    meta.helm.sh/release-name: csi-pretain
    meta.helm.sh/release-namespace: csi-pretain
  labels:
    # app.kubernetes.io/instance: csi-pretain
    app.kubernetes.io/managed-by: Helm
```

Only thing left are the storageclass secrets then? A way to predefine which secrets belong to which parameter

**Comment by D1StrX** [comment]
That works for the Driver part. The configmap doesn't need the following annotations & labels as well, I just figured.

  annotations:
    meta.helm.sh/release-name: <release_name>
    meta.helm.sh/release-namespace: <namespace>
  labels:
    app.kubernetes.io/managed-by: Helm
Only thing left are the storageclass secrets then? A way to predefine which secrets belong to which parameter

**Comment by travisghansen** [comment]
I don't think an ability to manage those via 'existing' secrets is in the chart yet. I would welcome a contribution to that for sure.

**Comment by D1StrX** [comment]
I understand, afraid I am not your guy right now 😅 but thanks for confirming that it is a feature/improvement to be made.
