### ISSUE TITLE
Are implementations freenas-api-* compatible with TrueNAS 13 CORE API ?

### ISSUE THREAD

**Issue by nodje** [democratic-csi/democratic-csi#267]
I'm confused about the usage of server implementation freenas-* vs freenas-api-*, i.e. SSH vs HTTPAPI to control TrueNAS.
The doc mentions FreeNAS 12.0+ where TrueNAS CORE 13 is now available with an API as well as TrueNAS SCALE.

I'm really not sure about this but I expected the TrueNAS CORE and SCALE APIs to be compatible for the functionality they both provide.
If this is the case I don't see why the freenas-api-* implementations wouldn't be working with TrueNAS CORE, they same way they work with TrueNAS SCALE.

**Comment by travisghansen** [comment]
CORE unfortunately does not have the same api nor the necessary calls to work with the api driver :( maybe someday but for now the api only drivers work only with scale
