### ISSUE TITLE
Backup and restore PVC

### ISSUE THREAD

**Issue by Tony-The-Developer** [democratic-csi/democratic-csi#272]
Hello. I am using velero to migrate apps and PVC and PV's to a new cluster. The velero backup completes and everything shows up but the app is unable to access data in the PV. Please help.

**Comment by travisghansen** [comment]
I'm assuming you mean after a restore? Are you restoring across clusters or something else?

**Comment by Tony-The-Developer** [comment]
I am restoring across clusters.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tony-The-Developer** [comment]
I have done it before and it worked but this time it is not. I can create a new pvc on the new cluster and it works but the existing ones don't.

**Comment by travisghansen** [comment]
Do the mounts/etc happen correctly, it's just the ownership of the volumes isn't what is necessary?

**Comment by Tony-The-Developer** [comment]
I dont know the pods go into a crashed state.

**Comment by Tony-The-Developer** [comment]
![image](https://user-images.githubusercontent.com/68414482/218009786-cedff459-71d0-4bde-abdd-ce1396ba8c6a.png)

**Comment by Tony-The-Developer** [comment]
executing mount command: findmnt --mountpoint /var/snap/microk8s/common/var/lib/kubelet/pods/2eb3c9b8-88fc-496d-9e73-ed1ca893b275/volumes/kubernetes.io~csi/pvc-bbd6f888-20af-41e7-be3b-533fdd76f253/mount --output source,target,fstype,label,options -b -J --nofsroot
retry - failed condition, not trying again

**Comment by Tony-The-Developer** [comment]
![image](https://user-images.githubusercontent.com/68414482/218019092-9388df45-3578-4b2a-8ecc-f3f7c7c7411b.png)

🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by travisghansen** [comment]
Glad it’s working now! Enjoy!
