### ISSUE TITLE
PVC stuck in Pending on Velero restore (Truenas Scale iscsi API)

### ISSUE THREAD

**Issue by Divinii** [democratic-csi/democratic-csi#278]
Hey,

when I restore a Dataset that contains PVCs the CSI Driver crashes and is unable to bind the PVCs (stuck in Pending). Zvols for the PVCs are not created. I looked for the pvc UID in truenas but could neither see a zvol still present nor a snapshot of said zvol.

The cluster is freshly built and namespaces were also restored using velero. Same Dataset was used but cleaned prior but Zvol naming scheme was changed. New Zvols are not named exactly like the old ones withch might explain why this restore worked.

## My steps were:

1. Decide to restore Namespace and resources in the namespace because of an error
2. Delete said namespace (including pvcs, pvs and zvols attached to pv)
3. create velero restore for specific namespace with --include-namespaces
4. velero creates kubernetes resources (ns, deployment, pods and pvcs)
5. pvc is stuck in pending and csi driver crashes

## Software in use:

- Truenas Scale 22.12.1
- k8s Cluster v1.24.10
- csi-provisioner v3.1.0
- velero Client: Version: v1.10.1
- velero Server: Version: v1.10.1

## Relevant Logs
Because of the following log entries I think this might be a failed api call to the Truenas:

`I0225 19:34:51.826873       1 connection.go:187] GRPC error: rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0225 19:34:51.826889       1 controller.go:764] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 10737418240, limit_bytes: 0
I0225 19:34:51.826923       1 controller.go:1075] Final error received, removing PVC aaf48e27-100d-49e7-a11a-6d23b3376c5a from claims in progress
W0225 19:34:51.826932       1 controller.go:934] Retrying syncing claim "aaf48e27-100d-49e7-a11a-6d23b3376c5a", failure 3`

### Full external provisioner logs
[zfs-iscsi-democratic-csi-controller-7f6ddd6bb-khdkx_external-provisioner.log](https://github.com/democratic-csi/democratic-csi/files/10832127/zfs-iscsi-democratic-csi-controller-7f6ddd6bb-khdkx_external-provisioner.log)

### Helm Values file
[freenas-iscsi-server.zip](https://github.com/democratic-csi/democratic-csi/files/10832131/freenas-iscsi-server.zip)

**Comment by travisghansen** [comment]
Hmm I don’t have a lot of experience with velero unfortunately so don’t have much input here. As I recall everything has to match exactly. Were there differences in the deployment (of democratic-csi) at all? Particularly using different parent datasets or something of that nature?

**Comment by Divinii** [comment]
Hey, thanks for the reply! Velero does not (at least how i configured it with restic restore) restore the pv object itself but lets the storageclass handle the creation of the pv. There is an init container added to the restored pod that waits for the pvc and then the restore is also handled with that init container. As far as i can see there is no democratic-csi data in the pvc itself:

```
root@lab-kube-master:~# k get pvc tdarr-config -n tdarr -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: org.democratic-csi.iscsi
    volume.kubernetes.io/storage-provisioner: org.democratic-csi.iscsi
  creationTimestamp: "2023-03-01T18:46:59Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    velero.io/backup-name: kube-migration
    velero.io/restore-name: tdarr5
  name: tdarr-config
  namespace: tdarr
  resourceVersion: "3483288"
  uid: cc0451c5-7022-40e1-99e1-ed731bc69768
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: freenas-iscsi-csi
  volumeMode: Filesystem
  volumeName: pvc-cc0451c5-7022-40e1-99e1-ed731bc69768
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
```
  
  With that being said I am now unable to reproduce this issue :D I can now restore from the same backup as I tried earlier or a more recent one. Also yes, Dataset Parent was different, but it does not seem to change the outcome. I do see the democratic-csi data in the pv:
  
  ```
root@lab-kube-master:~# k get pv pvc-cc0451c5-7022-40e1-99e1-ed731bc69768 -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: org.democratic-csi.iscsi
  creationTimestamp: "2023-03-01T18:47:08Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-cc0451c5-7022-40e1-99e1-ed731bc69768
  resourceVersion: "3483285"
  uid: d2c4ef1d-ca4c-4387-a8f4-cf4ece86da35
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: tdarr-config
    namespace: tdarr
    resourceVersion: "3483149"
    uid: cc0451c5-7022-40e1-99e1-ed731bc69768
  csi:
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-zfs-iscsi-democratic
      namespace: democratic-csi
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-zfs-iscsi-democrati
      namespace: democratic-csi
    driver: org.democratic-csi.iscsi
    fsType: xfs
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-zfs-iscsi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-zfs-iscsi-democratic-csi
      namespace: democratic-csi
    volumeAttributes:
      interface: ""
      iqn: iqn.2005-10.org.freenas.ctl:k-pvc-cc0451c5-7022-40e1-99e1-ed731bc69768-s
      lun: "0"
      node_attach_driver: iscsi
      portal: 10.200.10.41:3260
      portals: ""
      provisioner_driver: freenas-api-iscsi
      provisioner_driver_instance_id: cc5e84de-3111-4e4d-bc7b-b26661427817
      storage.kubernetes.io/csiProvisionerIdentity: 1677624965791-8081-org.democratic-csi.iscsi
    volumeHandle: pvc-cc0451c5-7022-40e1-99e1-ed731bc69768
  persistentVolumeReclaimPolicy: Delete
  storageClassName: freenas-iscsi-csi
  volumeMode: Filesystem
status:
  phase: Bound
```

I also had one occurence where the iscsi Target was not applied correctly, it would show up in Truenas UI, but not show up when doing `iscsiadm -m discovery -t sendtargets -p 10.200.10.41:3260 | grep <PVC>` I applied it again and then it showed up and would bind. Thought I might add that but I sadly dont have logs as I forgot to collect them..

**Comment by travisghansen** [comment]
Ok cool. Go ahead and close when you’re ready.
