### ISSUE TITLE
Helm chart 0.13.5 secrets problem - "can't iterate over" secret value

### ISSUE THREAD

**Issue by killroy1971** [democratic-csi/democratic-csi#280]
I'm attempting to install helm chart version 0.13.5. I'm using Openshift and TrueNAS Core if that matters.

I've defined the following secrets in my chart's values.yaml file
 secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
#      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
#      # if doing CHAP                                                                                                        
    node-db.node.session.auth.authmethod: CHAP
    node-db.node.session.auth.username: "iscsi_admin"
    node-db.node.session.auth.password: "<My_iSCSI_Password>"

No matter what I put in the node-db.node.session.auth.authmethod: CHAP, None, Dog, etc, I get the following error message during helm chart deployment:

Release "zfs-iscsi" does not exist. Installing it now.
Error: template: democratic-csi/templates/storage-classes.yaml:66:20: executing "democratic-csi/templates/storage-classes.yaml" at <$v>: range can't iterate over CHAP

If I leave node-db.node.session.auth.authmethod blank, the error message occurs in node-db.node.session.auth.password. 
I've tried the usual yaml single quotes, no quotes, and double quotes thing. No luck.

Any idea why I'm receiving this error?

**Comment by travisghansen** [comment]
Can you send over the values cleansed?

**Comment by killroy1971** [comment]
Sure thing

---
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.iscsi"

# add note here about volume expansion requirements
storageClasses:
- name: freenas-iscsi-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: ext4

    # if true, volumes created from other snapshots will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromSnapshots: "false"

    # if true, volumes created from other volumes will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromVolumes: "false"

  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
#      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
#      # if doing CHAP
    node-db.node.session.auth.authmethod: CHAP
    node-db.node.session.auth.username: "iscsi_admin"
    node-db.node.session.auth.password: "<My_iSCSI_Password>"
#
#      # if doing mutual CHAP
#      node-db.node.session.auth.username_in: baz
#      node-db.node.session.auth.password_in: bar
    node-publish-secret:
    controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: freenas-iscsi-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

driver:
  config:
    # please see the most up-to-date example of the corresponding config here:
    # https://github.com/democratic-csi/democratic-csi/tree/master/examples
    # YOU MUST COPY THE DATA HERE INLINE!
    driver: freenas-api-iscsi
    instance_id:
    httpConnection:
      protocol: https
      host: 192.168.4.6
      port: 443
      # use only 1 of apiKey or username/password
      # if both are present, apiKey is preferred
      # apiKey is only available starting in TrueNAS-12
      apiKey: 1-uzjc9s4VvI3pMuRWmcXWjfcM91MiPZOHswbHtOvBVkOkS7pOqvsQ5rH0mMDQDOCZ
      # username: root
      # password:
      allowInsecure: true
      # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
      # leave unset for auto-detection
      apiVersion: 2
    zfs:
      # can be used to override defaults if necessary
      # the example below is useful for TrueNAS 12
      #cli:
      #  sudoEnabled: true
      #
      #  leave paths unset for auto-detection
      #  paths:
      #    zfs: /usr/local/sbin/zfs
      #    zpool: /usr/local/sbin/zpool
      #    sudo: /usr/local/bin/sudo
      #    chroot: /usr/sbin/chroot

      # can be used to set arbitrary values on the dataset/zvol
      # can use handlebars templates with the parameters from the storage class/CO
      #datasetProperties:
      #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      #  "org.freenas:test": "{{ parameters.foo }}"
      #  "org.freenas:test2": "some value"

      # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
      # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
      # standard volume naming overhead is 46 chars
      # datasetParentName should therefore be 17 chars or less when using TrueNAS 12 or below (SCALE and 13+ do not have the same limits)
      # for work-arounds see https://github.com/democratic-csi/democratic-csi/issues/54
      datasetParentName: ssd02/nuc/vols
      # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
      # they may be siblings, but neither should be nested in the other
      detachedSnapshotsDatasetParentName: ssd02/nuc/snaps
      # "" (inherit), lz4, gzip-9, etc
      zvolCompression: inherit
      # "" (inherit), on, off, verify
      zvolDedup: inherit
      zvolEnableReservation: false
      # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
      zvolBlocksize: 16K
    iscsi:
      targetPortal: "192.168.4.6[:3260]"
      # for multipath
      targetPortals: [] # [ "server[:port]", "server[:port]", ... ]
      # leave empty to omit usage of -I with iscsiadm
      interface: 

      # MUST ensure uniqueness
      # full iqn limit is 223 bytes, plan accordingly
      # default is "{{ name }}"
      #nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      namePrefix: csi-
      nameSuffix: "truenas"

      # add as many as needed
      targetGroups:
        # get the correct ID from the "portal" section in the UI
        - targetGroupPortalGroup: 1
          # get the correct ID from the "initiators" section in the UI
          targetGroupInitiatorGroup: 1
          # None, CHAP, or CHAP Mutual
          targetGroupAuthType: CHAP
          # get the correct ID from the "Authorized Access" section of the UI
          # only required if using Chap
          targetGroupAuthGroup: 1

      #extentCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      # 512, 1024, 2048, or 4096,
      extentBlocksize: 512
      # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
      extentRpm: "SSD"
      # 0-100 (0 == ignore)
      extentAvailThreshold: 0

**Comment by killroy1971** [comment]
Sorry it's being treated like markdown...not sure how to avoid that.

**Comment by travisghansen** [comment]
I fixed it :)

**Comment by killroy1971** [comment]
Thanks!

**Comment by travisghansen** [comment]
The `node-db` entries need to be ‘beneath’ the `node-stage-secret` key. ie: indent all 3 keys 2 spaces.

**Comment by travisghansen** [comment]
The zfs values you want inherited should be `””` not `inherit`.

**Comment by killroy1971** [comment]
Change made.  Now I know that comment: "" (inherit) means 'use "" to indicate inherit'

Thank you

**Comment by travisghansen** [comment]
Everything working?

**Comment by killroy1971** [comment]
Sadly no. I still have the same problem. The helm chart won't generate my secrets during install.

**Comment by travisghansen** [comment]
Can you send your current values.yaml?

**Comment by killroy1971** [comment]
I figured it out.
I took a look at values.yaml, and the items containing the CHAP secret values are indented. Now, I've witnessed plenty of properly formatted yaml get a bit mangled after applying it to Kubernetes. On the assumption that the example I'm using was the victim of this, I indented these values.

Now the helm chart deploys!  Too bad I'm running TrueNAS Core instead of Scale.  I'll swap out the api driver for the regular iscsi driver and see what happens.

**Comment by travisghansen** [comment]
API driver doesn’t work with core and isn’t on the roadmap :(

**Comment by killroy1971** [comment]
That's too bad. I assume it's not on the roadmap because TrueNAS appears to be pushing towards Scale?

**Comment by travisghansen** [comment]
I don’t know the reasons but the changes made to the scale api to support it were relatively extensive so I’m not sure what the lift would be to replicate to core.

**Comment by killroy1971** [comment]
I'm not sure where IX Systems is planning to go with TrueNAS - Scale or Core? I'm assuming it won't always be both.

**Comment by travisghansen** [comment]
Yeah good question. I don’t have any insider information or anything. To my knowledge the current messaging is the plan is to continue with both.
