### ISSUE TITLE
Add support for RWX iSCSI to allow for KubeVirt live migration

### ISSUE THREAD

**Issue by peterclauterbach** [democratic-csi/democratic-csi#285]
When running VMs on k8s with [KubeVirt](http://kubevirt.io/), it requires RWX volumes for [live migration](https://kubevirt.io/user-guide/operations/live_migration/). This works fine with NFS based PVs, but RWX iSCSI PVs not supported in democratic-csi yet.
k8s does not provide nor expect concurrency for RWX Block mode PVs. <looking for link> k8s assumes you know what you are doing, and the application mounting an RWX volume on multiple hosts is responsible for the concurrency and access to the data.

For VM live migration in KubeVirt, the QEMU/KVM process of the VM coordinates the creation of the target VM and storage, and handles the migrations of memory/cpu, and the switching of the storage access from the source to target host. KubeVirt prefers block mode PVs over Filesystem, it has less overhead, and generally performs better.

RWX block mode iSCSI volume is supported on the Synology CSI driver, as well as in many CSI drivers for block-mode storage.

relevant comment on a related issue.

              I guess I should mention, nfs is required for rwx workloads which you cannot do with iscsi. But as mentioned, for many workloads the performance of iscsi is far superior.

_Originally posted by @travisghansen in https://github.com/democratic-csi/democratic-csi/issues/73#issuecomment-822979890_

**Comment by travisghansen** [comment]
Interesting note about rwx with block mode. Are you using the synology driver or something else?

**Comment by peterclauterbach** [comment]
Currently using the Synology CSI driver. I started with democratic-csi, it's quite popular amongst my colleagues.

**Comment by travisghansen** [comment]
I'll have an update for you shortly to support this in some shape or form. Is it *standard / default* to allow rwx when block mode is operative in the other drivers mentioned?

**Comment by travisghansen** [comment]
Yeah I understand the mechanics, just enabling that is giving the user the metaphorical gun. I’m surprised the other csi enable that by defusing is all.

**Comment by travisghansen** [comment]
This is now supported by all scenarios where `block` is the access type.

https://github.com/democratic-csi/democratic-csi/pull/286/files

Set the image tag to `v1.8.2`. It would be great if you could run through some tests etc and also attempt a resize/expand of the volume as well.

**Comment by travisghansen** [comment]
@singlecheeze @awels take a peek at this.

https://github.com/democratic-csi/democratic-csi/issues/238#issuecomment-1281148917

When that ^ comment was written I didn't understand that kubevirt had the required smarts to not do stupid things. I'm now under the impression that it does so live migration should work sanely.

https://github.com/ceph/ceph-csi/blob/devel/examples/README.md#how-to-test-rbd-multi_node_multi_writer-block-feature

**Comment by travisghansen** [comment]
Jump to `v1.8.3` actually. The feature added a regression I fixed in the newer version :(
