### ISSUE TITLE
Is there support for Nomad Secrets?

### ISSUE THREAD

**Issue by CarbonCollins** [democratic-csi/democratic-csi#292]
Hi :wave:,

I have an SMB share which I am currently registering with Nomad using the `smb-client` driver. The SMB share itself requires a username and password which I am currently setting in the mount_flags as `username=blah` and `password=blah`.

Is the this driver able to pull these values from the secrets block defined when registering the volume and convert them into mount_flags when attempting to mount instead of having them directly defined as mount_flags?

Thanks!

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/democratic-csi/issues/220#issuecomment-1197345243

**Comment by tgross** [comment]
Hi @CarbonCollins & @travisghansen! I missed the request for input in #220, sorry about that.

I just took a quick pass over the code that talks to the CSI plugins and it's aware of secrets for `NodeStageVolumeRequest` that are passed in with the volume [`secrets`](https://developer.hashicorp.com/nomad/docs/other-specifications/volume#secrets) (we'd also like to be able to get these from encrypted [Nomad Variables](https://github.com/hashicorp/nomad/issues/7978) but that's a ways out). So it _should_ work and if it's not it's probably a bug somewhere in Nomad. If you can submit an issue to the Nomad repo with a minimal reproduction we can try to take a look.

**Comment by travisghansen** [comment]
@tgross so the values in the single stanza are used for several different csi calls?

**Comment by tgross** [comment]
They're used for the entire publish/unpublish/stage/unstage workflow. That is, not for things like snapshot create or listing external volumes. My understanding is that if a plugin needs unique secrets for different stages, they're supposed to be different keys?

**Comment by travisghansen** [comment]
@tgross from a k8s perspective they *can* be set independently of each other. Each operation simply let's you point it to a k8s `Secret` so they may all point to the same or they may each point to unique `Secret`s. k8s even allows templating of the name to make it dynamic by namespace and such, but that's pretty ancillary to the primary point.

https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html

**Comment by CarbonCollins** [comment]
@travisghansen Did some testing and ran a cifs share. I deployed it via terraform so I had this block defined in my config:

```
  mount_options {
    fs_type = "cifs"
    mount_flags = [
      "vers=3.0",
      format("uid=%d", var.cifs_user_id),
      format("gid=%d", var.cifs_group_id),
      "file_mode=0600",
      "dir_mode=0700",
      "noperm",
      "nobrl",
    ]
  }

  secrets = {
    mount_flags = format("username=%s,password=%s", var.mount_username, var.mount_password)
  }
```

and as far as I can see my volume mounts and authenticates at least :D Ive not been able to fully test with a working workload as I am having other cluster issues right now...

**Comment by travisghansen** [comment]
Sounds great! Thanks for reporting back.
