### ISSUE TITLE
Setting format options via StorageClass parameters?

### ISSUE THREAD

**Issue by Winor** [democratic-csi/democratic-csi#294]
I switched from SynologyOpenSource/synology-csi recently due to [this](https://github.com/SynologyOpenSource/synology-csi/issues/25) issue. I saw your comment there and decided to try. However, it's not clear if it's also possible to set formatting parameters via StorageClass and if so, How? (I deployed democratic-csi via Helm) Thanks!

**Comment by travisghansen** [comment]
Welcome! Storage Class parameters do not get sent to the node operations. About the only option would be to introduce a `format_flags` key to the stage secret.
