### ISSUE TITLE
Cannot create PVC, "1 Portal not found in database" even though portal group exists

### ISSUE THREAD

**Issue by UntouchedWagons** [democratic-csi/democratic-csi#299]
I'm trying out D-CSI using the freenas-api-iscsi driver and I can't get it to create a volume because the portal group doesn't exist even though it does.

My `freenas-api-iscsi.yaml` file:

    csiDriver:
      # should be globally unique for a given cluster
      name: "org.democratic-csi.iscsi"

    # add note here about volume expansion requirements
    storageClasses:
    - name: freenas-iscsi-csi
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        # for block-based storage can be ext3, ext4, xfs
        # for nfs should be nfs
        fsType: ext4
          
        # if true, volumes created from other snapshots will be
        # zfs send/received instead of zfs cloned
        # detachedVolumesFromSnapshots: "false"
        
        # if true, volumes created from other volumes will be
        # zfs send/received instead of zfs cloned
        # detachedVolumesFromVolumes: "false"

      mountOptions: []
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
    #      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
    #      # if doing CHAP
    #      node-db.node.session.auth.authmethod: CHAP
    #      node-db.node.session.auth.username: foo
    #      node-db.node.session.auth.password: bar
    #
    #      # if doing mutual CHAP
    #      node-db.node.session.auth.username_in: baz
    #      node-db.node.session.auth.password_in: bar
        node-publish-secret:
        controller-expand-secret:

    # if your cluster supports snapshots you may enable below
    volumeSnapshotClasses: []
    #- name: freenas-iscsi-csi
    #  parameters:
    #  # if true, snapshots will be created with zfs send/receive
    #  # detachedSnapshots: "false"
    #  secrets:
    #    snapshotter-secret:

    driver:
      config:
        driver: freenas-api-iscsi
        instance_id:
        httpConnection:
          protocol: https
          host: 192.168.20.5
          port: 443
          apiKey: 3-eZmWsZp1ipVHJCtGygrQU6E0vanLIqrrb6IQ2kn9unsK58vJtoIoX3rIssfnf1rG
          allowInsecure: true
          apiVersion: 2

        zfs:
          datasetParentName: tank/K8S/Vols
          detachedSnapshotsDatasetParentName: tank/K8S/Snaps
          zvolCompression: ""
          zvolDedup: ""
          zvolEnableReservation: false
          zvolBlocksize: "16K"

        iscsi:
          targetPortal: "192.168.20.5:3260"
          targetPortals: []
          interface:
          namePrefix: csi-
          nameSuffix: "-clustera"
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 1
              targetGroupAuthType: None
              targetGroupAuthGroup:
          #extentCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          # 512, 1024, 2048, or 4096,
          extentBlocksize: 4096
          # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
          extentRpm: ""
          # 0-100 (0 == ignore)
          extentAvailThreshold: 0

My `pvc-test.yaml` file:

    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-test
      namespace: default
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: freenas-iscsi-csi
      resources:
        requests:
          storage: 30Gi

The actual error:

    kubectl describe pvc pvc-test
    Name:          pvc-test
    Namespace:     default
    StorageClass:  freenas-iscsi-csi
    Status:        Pending
    Volume:
    Labels:        <none>
    Annotations:   volume.beta.kubernetes.io/storage-provisioner: org.democratic-csi.iscsi
                  volume.kubernetes.io/storage-provisioner: org.democratic-csi.iscsi
    Finalizers:    [kubernetes.io/pvc-protection]
    Capacity:
    Access Modes:
    VolumeMode:    Filesystem
    Used By:       <none>
    Events:
      Type     Reason                Age               From                                                                                                                Message
      ----     ------                ----              ----                                                                                                                -------
      Normal   Provisioning          9s (x5 over 29s)  org.democratic-csi.iscsi_zfs-iscsi-democratic-csi-controller-5cfd47d6c8-2pcrt_b035431c-76f3-4ac6-82be-e3b3377a94fc  External provisioner is provisioning volume for claim "default/pvc-test"
      Warning  ProvisioningFailed    8s (x5 over 27s)  org.democratic-csi.iscsi_zfs-iscsi-democratic-csi-controller-5cfd47d6c8-2pcrt_b035431c-76f3-4ac6-82be-e3b3377a94fc  failed to provision volume with StorageClass "freenas-iscsi-csi": rpc error: code = Unknown desc = received error creating iscsi target - code: 422 body: {"iscsi_target_create.groups.0.portal":[{"message":"1 Portal not found in database","errno":22}]}
      Normal   ExternalProvisioning  7s (x3 over 29s)  persistentvolume-controller                                                                                         waiting for a volume to be created, either by external provisioner "org.democratic-csi.iscsi" or manually created by system administrator

I manually created a portal group with auth method set to NONE (which has the id of 1) and an initiator group that allows all initiators that also has an id of 1.

**Comment by travisghansen** [comment]
Sometimes the UI doesn't match the id in the database :( Easiest thing to do is edit the thing with the browser devtools up and see what ID is actually getting sent across the wire..or sometimes you can just look in the address bar and see as well.

**Comment by UntouchedWagons** [comment]
Oooh that is super terrible design, I had to use the API docs page to get the right portal group (correct id is 2).

Okay so I changed the extentRpm value (setting it to "" doesn't work as the comments suggest) and reinstall D-CSI but I have a working volume claim!

    kubectl get pvc
    NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
    pvc-test   Bound    pvc-8b248d62-6ac0-4d40-863e-bdf861f8ae30   30Gi       RWO            freenas-iscsi-csi   16s

My only major complaint is that the documentation doesn't make it clear that I'm supposed to merge [this file](https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/examples/freenas-iscsi.yaml) with [this file](https://github.com/democratic-csi/democratic-csi/blob/master/examples/freenas-api-iscsi.yaml), I was getting an error about csiDriver.name and found the solution via #25

**Comment by travisghansen** [comment]
Yeah fair enough on the docs! Basically there are no kubernetes-isms in the core project/doc and the driver configs are relevant to any csi (Nomad, etc). I didn't want to duplicate the content everywhere so put a comment in the helm values about merging the data but I'm sure it could be more clear.

**Comment by fenio** [comment]
> My only major complaint is that the documentation doesn't make it clear that I'm supposed to merge [this file](https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/examples/freenas-iscsi.yaml) with [this file](https://github.com/democratic-csi/democratic-csi/blob/master/examples/freenas-api-iscsi.yaml), I was getting an error about csiDriver.name and found the solution via #25

Had the same problem with I was experimenting with setup. I was completely confused with the fact that I had to merge these two files as part of setting things up. That's why in my own guide (https://github.com/fenio/k8s-truenas) I'm using two wget commands to combine settings file.

Anyway... I'm here cause I'm trying to actually finish that guide and hit issue with wrong portal ID.
Is there anything specific you found in API that I could check to figure out exact portal ID?

**Comment by UntouchedWagons** [comment]
Yes in the API docs click on the RESTful 2.0 tab and authorize then search for /iscsi/portal, the first one will be the GET version, open that one. Click "Try it out" then "Execute", below you'll get a JSON response with all the iscsi portals listed. The objects in the array will have an `id` element, its value is what you need.

**Comment by fenio** [comment]
> Yes in the API docs click on the RESTful 2.0 tab and authorize then search for /iscsi/portal, the first one will be the GET version, open that one. Click "Try it out" then "Execute", below you'll get a JSON response with all the iscsi portals listed. The objects in the array will have an `id` element, its value is what you need.

Thanks for your answer but in the meantime I did some research with CLI... and dear god... I could spent on that crap ages.
WebUI still shows portal ID as 1 while...

```
[nas] sharing iscsi portal> get_instance 0
Validation errors:
* ISCSIPortal 0 does not exist

[nas] sharing iscsi portal> get_instance 1
Validation errors:
* ISCSIPortal 1 does not exist

[nas] sharing iscsi portal> get_instance 2
Validation errors:
* ISCSIPortal 2 does not exist

[nas] sharing iscsi portal> get_instance 3
Validation errors:
* ISCSIPortal 3 does not exist

[nas] sharing iscsi portal> get_instance 4
Validation errors:
* ISCSIPortal 4 does not exist

[nas] sharing iscsi portal> get_instance 5
Validation errors:
* ISCSIPortal 5 does not exist

[nas] sharing iscsi portal> get_instance 6
Validation errors:
* ISCSIPortal 6 does not exist

[nas] sharing iscsi portal> get_instance 7
Validation errors:
* ISCSIPortal 7 does not exist

[nas] sharing iscsi portal> get_instance 8
+----------------------+--------+
|                   id | 8      |
|                  tag | 1      |
|              comment | iscsi  |
|               listen | <list> |
| discovery_authmethod | NONE   |
|  discovery_authgroup | <null> |
+----------------------+--------+
```

**Comment by UntouchedWagons** [comment]
Yeah that's god awful UI design on ixsystems' part.

**Comment by fenio** [comment]
But I really don't get it. It's rather simple story to show actual state in UI.
Now I'm gonna be careful checking if volumes/snapshots showed by webUI means anything. Maybe I've got not data cause they are showing some crap from their test env ;)

**Comment by fenio** [comment]
Well it seems that the most basic thing is still reusing ID. Namely portal ID. I'm gonna update my guide to double check what is CLI returning and ask everyone not to trust webUI. But I really find it truly amazing that such basic stuff can be out of sync in UI.
