### ISSUE TITLE
Order of configuration

### ISSUE THREAD

**Issue by mhabicht** [democratic-csi/democratic-csi#3]
I wanted to verify the order that I need to implement for my X20-TrueNas to work with my Kubernetes cluster on my 10gb storge subnet. 

Is this the correct deployment order? am I missing any yamls?
freenas-nfs.yaml
class.yaml
deployment.yaml  ---is this 1.15 compatible?
rbac.yaml   
secret.yaml
claim.yaml
pod.yaml

Do I need the helm charts?

**Comment by travisghansen** [comment]
Are those files coming from the old project?

It’s highly recommended to use the helm chart for install (you can use the helm template command if you still want to use kubectl apply):

- https://github.com/democratic-csi/charts
- https://github.com/democratic-csi/charts/tree/master/stable/democratic-csi/examples

Use 1 (or both if doing both nfs and iscsi) of the files in the examples dir to use as the helm `values` file.

Happy to help you step through the setup as I haven’t yet documented everything.

I think with 1.15 you’ll be ok but may want/need to enable some feature gates to use all the functionality.

**Comment by mhabicht** [comment]
I have feature gate set to true.

This is a fresh build, so there is nothing old that needs to be converted. 

Are you saying that helm will install and configure all the pieces I need? (removes the manual process)

**Comment by travisghansen** [comment]
Just configure/edit the values file and run the helm command to install/upgrade (I’ll send examples when back to my desk) and it will install/update everything as necessary and continue to do so should you make changes to the values file and rerun.

**Comment by mhabicht** [comment]
It looks like I only need to change a few things under Driver.Config (host and password)

**Comment by travisghansen** [comment]
Yeah shouldn’t be much. Maybe set the proper pool/dataset names for the parents etc.

Also make sure you follow the same node prep guidelines available here: https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/operations/tasks/worker.html

**Comment by mhabicht** [comment]
Okay, I ran the 2 commands. Where does Helm put the yamls?
`root@mackm01-anp1:/u01/yaml# helm repo add democratic-csi https://democratic-csi.github.io/charts/
"democratic-csi" has been added to your repositories
`
`root@mackm01-anp1:/u01/yaml# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "democratic-csi" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
`

**Comment by travisghansen** [comment]
It hasn’t done that yet. If you’re familiar with yum/apt think of those 2 commands as adding a new repo and just making sure the repo is fully updated..but didn’t install anything.

Give me another 15 minutes or so and I’ll send you a couple examples that should get you going.

I’ll also send possible feature gates that you may want.

**Comment by travisghansen** [comment]
If you want helm to manage them down the example `values` files to the `${PWD}`, modify as appropriate and run:

```
kubectl create ns democratic-csi

helm upgrade \
--install \
--values freenas-iscsi.yaml \
--namespace democratic-csi \
zfs-iscsi democratic-csi/democratic-csi

helm upgrade \
--install \
--values freenas-nfs.yaml \
--namespace democratic-csi \
zfs-nfs democratic-csi/democratic-csi
```

You are welcome to change the namespace used and/or the release name (zfs-iscsi, zfs-nfs are both arbitrary in essence).

With the above example you'd end up with 2 instances of the controller deployed one for nfs and one for iscsi. Assuming you did proper node prep and have proper values in the `values` files you'd end up with 2 storage classes which should work appropriately.

If you'd rather not helm 'manage' the releases you can use helm to simply generate yaml but not submit it to k8s. Generally speaking replace `helm upgrade --install` with:

```
helm template --values freenas-nfs.yaml --namespace democratic-csi zfs-nfs democratic-csi/democratic-csi
```

The above will spit out the yaml to `stdout` so you can pipe it directly to `kubectl` or save it off as desired. If you go the above route, just make sure when you `kubectl apply` that you use the same namespace you gave to the `helm` command. ie `kubectl apply -n democratic-csi ...`

**Comment by travisghansen** [comment]
Forgot about feature gates...

```
"VolumePVCDataSource=true,VolumeSnapshotDataSource=true,ExpandCSIVolumes=true,ExpandInUsePersistentVolumes=true"
```

**Comment by mhabicht** [comment]
UPGRADE FAILED
Error: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
Error: UPGRADE FAILED: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"


Do I add the feature gate to the kube- API/CONTROL/SCHED yamls on the manager?
` - --feature-gates=PersistentLocalVolumes=True,VolumeScheduling=True,MountPropagation=True`

**Comment by travisghansen** [comment]
I'm not sure how to add the feature gates to whatever you use for your k8s distro. I use the rancher `rke` tool. Generally they should be added to all components though.

Can you send over the exact command you ran which produced the error above?

**Comment by mhabicht** [comment]
`helm upgrade --install --values freenas-iscsi.yaml --namespace democratic-csi zfs-iscsi democratic-csi/democratic-csi`

**Comment by travisghansen** [comment]
That's a pretty odd error for that command. Are you using a cluster admin account for your `KUBECONFIG`?

Are you using helm 2 or helm 3?

**Comment by mhabicht** [comment]
I am using Kubespray and ansible-playbook to configure my cluster.

# helm version
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}

**Comment by travisghansen** [comment]
Ah, that makes more sense (helm 2 is deprecated...it should still work with the charts for sure though). You must not be running as cluster admin `KUBECONFIG` when executing the helm command...

**Comment by mhabicht** [comment]
It looks to me as if helm is attempting to change or communicate with my storage-class in namespace kube-system. Is this what is making you think helm does not have the correct privileges? Where do the privileges get configured?

**Comment by travisghansen** [comment]
helm 2 stores all it's meta data in the same namespace as where tiller is installed I believe (which I'm guessing is in `kube-system` for you). helm 3 is different and stores it in the namespace of the installed `release`.

In any case, when you create the/a cluster generally the byproduct will be a/the admin kubeconfig file (this applies to stuff generally and is fully independent of this project for sure). I'm guessing `kubectl` generally isn't working for you at the moment. If you can find where `kubespray` left the config file then you need to `export KUBECONFIG=/full/path/to/file` at which point `kubectl` commands will work better and in turn `helm` will be able to do it's thing as well.

**Comment by mhabicht** [comment]
Kubectl and kubeadm work with no problems. All the configs are in /etc/kubernetes. What is the benefits that helm is providing; what files are being created that do not get created if I kubectl create for each of the yaml's?
I have no doubt I am doing something wrong, I just don't know what.

**Comment by travisghansen** [comment]
Helm makes it easy to parameterize yaml (templates if you will) among other things. You can use helm to simply render the yaml and then apply with kubectl if you’d like...

**Comment by mhabicht** [comment]
I think I am going to try that way, so I am only troubleshooting on thing.

**Comment by travisghansen** [comment]
Yeah read the above comment with instructions on how to use helm template command and let me know if it works.

**Comment by mhabicht** [comment]
The template command did not work. I get errors that the file does not exist. It appears that it is looking for the yamls. I manually created the freenas yamls, but now it is looking for the chart yaml. Manually creating the yamls and `kubectl create` might be easier.
`# helm template --values freenas-nfs.yaml --namespace democratic-csi zfs-nfs democratic-csi/democratic-csi`
`Error: stat zfs-nfs: no such file or directory
`
`# mkdir zfs-nfs
`
`# helm template --values freenas-nfs.yaml --namespace democratic-csi zfs-nfs democratic-csi/democratic-csi`
`Error: no Chart.yaml exists in directory "/u01/yaml/ubuntu/zfs-nfs"
`
`# ls`
`freenas-iscsi.yaml  
freenas-nfs.yaml 
zfs-nfs
`

**Comment by travisghansen** [comment]
The syntax may be slightly different for helm 2...let me get a proper sample for you I guess...gonna be about 30 before I’m at my desk.

**Comment by mhabicht** [comment]
upgraded to helm 3. It looks like the commands are working now. But where are the yamls. How do I update the values? Looks like some things are not running.

`# kubectl get all -n democratic-csi
NAME                                                       READY   STATUS                     RESTARTS   AGE
pod/zfs-iscsi-democratic-csi-controller-7d8f78b476-j65xz   5/5     Running                    0          110s
pod/zfs-iscsi-democratic-csi-node-4m8h5                    3/3     Running                    0          110s
pod/zfs-iscsi-democratic-csi-node-d6zmf                    3/3     Running                    0          110s
pod/zfs-iscsi-democratic-csi-node-d95s8                    3/3     Running                    0          110s
pod/zfs-iscsi-democratic-csi-node-jpnn9                    3/3     Running                    0          110s
pod/zfs-iscsi-democratic-csi-node-km789                    0/3     UnexpectedAdmissionError   0          32s
pod/zfs-iscsi-democratic-csi-node-lttm4                    0/3     UnexpectedAdmissionError   0          32s
pod/zfs-iscsi-democratic-csi-node-pzjwx                    3/3     Running                    0          110s
pod/zfs-nfs-democratic-csi-controller-ff6959ffd-f7xqt      5/5     Running                    0          72s
pod/zfs-nfs-democratic-csi-node-24r2r                      0/3     UnexpectedAdmissionError   0          30s
pod/zfs-nfs-democratic-csi-node-552s7                      0/3     UnexpectedAdmissionError   0          30s
pod/zfs-nfs-democratic-csi-node-9pwff                      3/3     Running                    0          72s
pod/zfs-nfs-democratic-csi-node-djcdm                      3/3     Running                    0          72s
pod/zfs-nfs-democratic-csi-node-njnjr                      3/3     Running                    0          72s
pod/zfs-nfs-democratic-csi-node-rlmsm                      3/3     Running                    0          72s
pod/zfs-nfs-democratic-csi-node-xttkn                      3/3     Running                    0          72s



NAME                                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/zfs-iscsi-democratic-csi-node   7         7         5       7            5           <none>          110s
daemonset.apps/zfs-nfs-democratic-csi-node     7         7         5       7            5           <none>          72s

NAME                                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/zfs-iscsi-democratic-csi-controller   1/1     1            1           110s
deployment.apps/zfs-nfs-democratic-csi-controller     1/1     1            1           72s

NAME                                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/zfs-iscsi-democratic-csi-controller-7d8f78b476   1         1         1       110s
replicaset.apps/zfs-nfs-democratic-csi-controller-ff6959ffd      1         1         1       72s

`

**Comment by travisghansen** [comment]
Looks to me like you installed/upgraded so the yaml was sent to k8s and is actively trying to deploy everything. You must use the template command if you want the raw yaml.

It looks like most of the stack came up. You have to do some debugging on the failed pods to see why the admission controller is seemingly disallowing the pods.. you can you kubectl describe on the pods to maybe get an idea.

**Comment by mhabicht** [comment]
`Warning  UnexpectedAdmissionError  7m48s  kubelet, mac01-anp4  Update plugin resources failed due to failed to write checkpoint file "kubelet_internal_checkpoint": open /var/lib/kubelet/device-plugins/.504054321: read-only file system, which is unexpected.
`

I am not sure what it should be doing. Also I have 3 managers and 9 workers, but it appear here there are only 7 deployments?

**Comment by travisghansen** [comment]
The driver is *roughly* deployed in 2 parts, a `controller` which handles the communication with the storage appliance for creating the datasets, shares, etc and a `node` part which runs as a DaemonSet on all nodes (it should run on any node that will handle workloads requiring storage from the driver) which handles mount/format/fsck/etc operations on the nodes. If the `DaemonSet` is not running on all your nodes it's because some of your nodes have taints or similar which is preventing it from doing so.

I honestly have no idea why the devices-plugins directory would be read-only...your experience is making me kinda afraid of kubespray ;)

**Comment by mhabicht** [comment]
LOL!!!

The way it deployed is odd. both NFS and ISCSI deployed to m1/m2/w1/w2/w3 and seems to be running fine. m3/w4 are the ones faulted and w5/w6/w7/w8/w9 have no deployment.

Lets skip that for now though as I can control my containers to only deploy to a working worker node.

What would be the next step? What do I need to add to my deployment yaml to create and attach the volume from the TrueNas X20?

**Comment by travisghansen** [comment]
Well, regrading storage we'll take this one thing at a time I guess since we've had so much fun this far :)

- Did you do 'worker' node prep as described in the netapp docs?
- Is nfs/iscsi daemons running appropriately on the FreeNAS box?
- Is ssh access allowed to the FreeNAS box? Are you sue it will work with the username/password (or key) provided in the yaml?
- Can you send the output of `kubectl get storageclasses.storage.k8s.io`?

Let's start with all that :)

**Comment by mhabicht** [comment]
Where can I find the "netapp doc?"
I believe the daemon is running correctly on the storage appliance.
Yes, the UN/PW are correct for connecting to the VIP
`# kubectl get storageclasses.storage.k8s.io
`
`NAME                PROVISIONER                    AGE
`
`freenas-iscsi-csi   org.democratic-csi.iscsi       51m
`
`freenas-nfs-csi     org.democratic-csi.nfs         51m
`
`local-storage       kubernetes.io/no-provisioner   7d23h
`

**Comment by travisghansen** [comment]
https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/operations/tasks/worker.html

**Comment by travisghansen** [comment]
What version of FreeNAS is installed?

**Comment by mhabicht** [comment]
FreeBSD 11.3-RELEASE-p7 FreeBSD 11.3-RELEASE-p7 #0 r325575+ca0f1a6ba25(HEAD)

**Comment by mhabicht** [comment]
cat motd
        FreeBSD 11.3-RELEASE-p7 (TrueNAS.amd64) #0 r325575+ca0f1a6ba25(HEAD): Wed Apr 22 00:59:22 UTC 2020

        FreeNAS (c) 2009-2020, The FreeNAS Development Team
        All rights reserved.
        FreeNAS is released under the modified BSD license.

        For more information, documentation, help or support, go here:
        http://freenas.org
				Welcome to TrueNAS

        cat version
        TrueNAS-11.3-U2.1 (6a6a2dfda7)

**Comment by travisghansen** [comment]
OK, so updated nicely. Should work great. So after confirming you've done proper node prep it's simply a matter of creating a PVC and then using that PVC with a pod.

**Comment by mhabicht** [comment]
so I only need a PVC not a PV? do you have steps for how to create the PVC? 

This is what my PVC normally looks like

        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: cass1-claim
        spec:
          accessModes:
          - ReadWriteOnce
          storageClassName: local-storage
          resources:
            requests:
              storage: 1Ti

**Comment by travisghansen** [comment]
Well, the csi driver will create a resulting PV that gets `Bound` to the PVC for you. When you delete the PVC (assuming a `Delete` retention policy) the controller will de-provision storage/shares/etc and then remove the PV as well.

If you create just the PVC as above simply change the class as appropriate. If you watch the logs of the appropriate controller pod you should see it go off and create the dataset, and setup the share (iscsi or nfs based on which class you use) etc. At some point the PVC will show as `Bound` in which case you'll be half way there (let's start with just that). After we know that works, we'll try to get a pod to actually use the storage.
