### ISSUE TITLE
NFS driver does not create folders

### ISSUE THREAD

**Issue by f3l1x** [democratic-csi/democratic-csi#311]
Hi! At first, thank you for your work on CSI driver.

I'm using Truenas with NFS and NFS CSI driver.

I've used example in here:
- https://github.com/democratic-csi/democratic-csi/blob/master/docs/Nomad/examples/democratic-csi-nfs-controller.hcl
- https://github.com/democratic-csi/democratic-csi/blob/master/docs/Nomad/examples/democratic-csi-nfs-node.hcl

It looks fine, unfortunately it does not create folder in NFS folder. If I create it manually, everything works as expected.

Is it bug or on purpose?

Thank you.

**Comment by travisghansen** [comment]
It should create a dataset per volume on the pool. Normally datasets are automatically mounted and thus would be available for the nfs share.

Are you seeing new datasets but they aren’t mounted on the nas?

**Comment by f3l1x** [comment]
I've deployed this controller and these nodes.

Controller 

```hcl
job "democratic-csi-nfs-controller" {
  datacenters = ["dc1"]

  group "controller" {
    task "plugin" {
      driver = "docker"

      config {
        image = "docker.io/democraticcsi/democratic-csi:latest"

        args = [
          "--csi-version=1.5.0",
          # must match the csi_plugin.id attribute below
          "--csi-name=org.democratic-csi.nfs",
          "--driver-config-file=${NOMAD_TASK_DIR}/driver-config-file.yaml",
          "--log-level=info",
          "--csi-mode=controller",
          "--server-socket=/csi/csi.sock",
        ]
      }

      template {
        destination = "${NOMAD_TASK_DIR}/driver-config-file.yaml"

        data = <<EOF
driver: nfs-client
instance_id: {{ env "node.unique.id" }}
nfs:
  shareHost: 10.0.0.200
  shareBasePath: /mnt/mydrive/nomad-data
  # shareHost:shareBasePath should be mounted at this location in the controller container
  controllerBasePath: "/storage"
  dirPermissionsMode: "0777"
  dirPermissionsUser: root
  dirPermissionsGroup: root
EOF
      }

      csi_plugin {
        # must match --csi-name arg
        id        = "org.democratic-csi.nfs"
        type      = "controller"
        mount_dir = "/csi"
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

Node

```hcl
job "democratic-csi-nfs-node" {
  datacenters = ["dc1"]

  # you can run node plugins as service jobs as well, but this ensures
  # that all nodes in the DC have a copy.
  type = "system"

  group "nodes" {
    task "plugin" {
      driver = "docker"

      env {
        CSI_NODE_ID = "${attr.unique.hostname}"
      }

      config {
        image = "docker.io/democraticcsi/democratic-csi:latest"

        args = [
          "--csi-version=1.5.0",
          # must match the csi_plugin.id attribute below
          "--csi-name=org.democratic-csi.nfs",
          "--driver-config-file=${NOMAD_TASK_DIR}/driver-config-file.yaml",
          "--log-level=info",
          "--csi-mode=node",
          "--server-socket=/csi/csi.sock",
        ]

        # node plugins must run as privileged jobs because they
        # mount disks to the host
        privileged = true
        ipc_mode = "host"
        network_mode = "host"
      }

      template {
        destination = "${NOMAD_TASK_DIR}/driver-config-file.yaml"

        data = <<EOF
driver: nfs-client
instance_id: {{ env "node.unique.id" }}
nfs:
  shareHost: 10.0.0.200
  shareBasePath: /mnt/mydrive/nomad-data
  # shareHost:shareBasePath should be mounted at this location in the controller container
  controllerBasePath: "/storage"
  dirPermissionsMode: "0777"
  dirPermissionsUser: root
  dirPermissionsGroup: root
EOF
      }

      csi_plugin {
        # must match --csi-name arg
        id        = "org.democratic-csi.nfs"
        type      = "node"
        mount_dir = "/csi"
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

---

When I want to create a volume, for example like that.

```hcl
id        = "nfs-example"
name      = "nfs-example"
type      = "csi"
plugin_id = "org.democratic-csi.nfs" # Needs to match the deployed plugin

capability {
  access_mode     = "multi-node-multi-writer"
  attachment_mode = "file-system"
}
```

I see that in controller there is `/storage/v/nfs-example`. But no `nfs-example` folder on the NFS server (10.0.0.20:/mnt/mydrive/nomad-data)

**Comment by livioribeiro** [comment]
I also had this problem. In my case, I used an NFS server (Ubuntu, nfs-kernel-server). I expected that the csi driver would create the directory inside the nfs share before mounting the directory in the container, but it doens't create it.

**Comment by f3l1x** [comment]
@livioribeiro How did you solve it?

**Comment by livioribeiro** [comment]
> @livioribeiro How did you solve it?

I didn't

**Comment by travisghansen** [comment]
OK, couple things, the `instance_id` should be static across all nodes/controller for a specific deployment (ie: just make a guid and use it for both node/controller for this install).

`nfs-client` is a bit tricky to setup generally and I'm not sure anyone has done it in `Nomad`. The instructions here (assuming some familiarity with k8s) can be a guiding star: https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/examples/nfs-client.yaml

Essentially you need to bind mount a host mount to your root nfs share into the container, or do a `Nomad` equivalent of `postStart` to do the mount inside the container (specifically I'm referring to the controller container).

For example, with the config you've provided you should mount `10.0.0.200:/mnt/mydrive/nomad-data` on your server to `/storage` inside your controller container. Use either a host bind mount, or figure out how to make the controller container to do that on start entirely inside the container.

**Comment by travisghansen** [comment]
Yes. Make note that if you mount in the container the controller will need far more elevated privileges etc though.

**Comment by livioribeiro** [comment]
I did this and it worked

```hcl
      config {
        image = "docker.io/democraticcsi/democratic-csi:${var.version}"

        entrypoint = [
          "${NOMAD_TASK_DIR}/init.sh"
        ]

        network_mode = "host"
        privileged = true
      }

      template {
        destination = "${NOMAD_TASK_DIR}/init.sh"
        perms = "755"

        data = <<-EOT
          #!/bin/sh

          if [ ! -d /storage ]; then
            mkdir -p /storage
          fi

          mount {{ env "NFS_SHARE_HOST" }}:{{ env "NFS_SHARE_PATH" }} /storage

          exec ./bin/democratic-csi \
            --csi-version=1.5.0 \
            --csi-name=org.democratic-csi.nfs \
            --driver-config-file={{ env "NOMAD_TASK_DIR" }}/driver-config-file.yaml \
            --log-level=info \
            --csi-mode=controller \
            --server-socket=/csi/csi.sock
        EOT
      }
```

**Comment by travisghansen** [comment]
Beautiful! If you could open a PR with sample deployment files that would be appreciated.
