### ISSUE TITLE
Truenas Scale ISCSI `FreeNASApiDriver method: CreateVolume error:`

### ISSUE THREAD

**Issue by dmaclaury** [democratic-csi/democratic-csi#317]
Versions:
- TrueNAS-SCALE-22.12.3.3
- democratic-csi Chart `0.14.1`

I've been trying to set up the `freenas-api-iscsi` driver on my home lab cluster. I've had NFS running for a while now, but iSCSI will not work.

I'd appreciate any help figuring out where this has gone bad.

Everything seems to deploy correctly but I get this error when the driver tries to create a test PVC:
```text
{"host":"storage-iscsi-democratic-csi-controller-59fdbd987f-mckwl","level":"error","message":"handler error - driver: FreeNASApiDriver method: CreateVolume error: Error: {\"message\":\"\"} Error: {\"message\":\"\"}\n    at Api.DatasetCreate (/home/csi/app/src/driver/freenas/http/api.js:391:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async FreeNASApiDriver.CreateVolume (/home/csi/app/src/driver/freenas/api.js:2765:7)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:18)","service":"democratic-csi","timestamp":"2023-08-02T18:12:24.330Z"}
```

`csi-driver` container log: [csi-driver (1).txt](https://github.com/democratic-csi/democratic-csi/files/12243611/csi-driver.1.txt)

I've tried a couple of different things and started from scratch based on the `fenio` guide linked in the README.

Values: [iscsi-values.txt](https://github.com/democratic-csi/democratic-csi/files/12243628/iscsi-values.txt)
DataSet: ![iscsi Dataset](https://github.com/democratic-csi/democratic-csi/assets/1966417/a0ea5cbb-eb3c-45db-96d2-2fae49556c80)

I used a `netshoot` container in the same namespace to confirm that truenas is listening on `3260`:
```
Starting Nmap 7.93 ( https://nmap.org ) at 2023-08-02 18:37 UTC
Nmap scan report for <host> <IP>)
Host is up (0.00019s latency).
Not shown: 988 closed tcp ports (reset)
PORT     STATE SERVICE
22/tcp   open  ssh
81/tcp   open  hosts2-ns
111/tcp  open  rpcbind
139/tcp  open  netbios-ssn
444/tcp  open  snpp
445/tcp  open  microsoft-ds
2049/tcp open  nfs
3260/tcp open  iscsi
5357/tcp open  wsdapi
5800/tcp open  vnc-http
5900/tcp open  vnc
6000/tcp open  X11

Nmap done: 1 IP address (1 host up) scanned in 1.27 seconds
```

From my nodes, `iscsiadm ` reports no active sessions:
```
$ iscsiadm -m session
iscsiadm: No active sessions.
```

`iscsiadm` discover successfully runs:
```
<IP>:3260,1 iqn.2005-10.org.freenas.ctl:k8s
(truncated the full result)
```

**Comment by travisghansen** [comment]
Those logs don't help much do they lol. Try to turn on `debug` logs here: https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L167

That should show full requests/responses of the api and maybe help pinpoint which request is failing.

**Comment by dmaclaury** [comment]
Here's the log after debug was enabled
[csi-driver.txt](https://github.com/democratic-csi/democratic-csi/files/12244026/csi-driver.txt)

**Comment by dmaclaury** [comment]
Well... through some further trial and error, throwing anything at the wall to see what stuck, I got it working.

I had to manually create the `v` and `s` datasets that I had used in my values - either I missed this or it wasn't in the guide I followed.

After that, there was an error about RPM not being set. I set that to `"7200"` and then it started working.

**Comment by dmaclaury** [comment]
Thank you for the tip on enabling `debug` logs. That proved to be helpful!

**Comment by travisghansen** [comment]
Glad it's working! I'm surprised you needed to create the parents (maybe you wouldn't need to if the RPM was set).

**Comment by rinseaid** [comment]
I still needed to create the parent sets with the RPM parameter defined. Also on TrueNAS Scale 22.12.3.3. The controller debug logs show almost all requests resulting in 404 errors until creating the parent datasets (at around "2023-09-05T03:24:07" in the logs.

[controller.log](https://github.com/democratic-csi/democratic-csi/files/12518485/controller.log)

**Comment by travisghansen** [comment]
I will run some tests and see. If that’s the case it’s a regression for sure.
