### ISSUE TITLE
Unable to attach nfs volumes to pods running on control plane nodes

### ISSUE THREAD

**Issue by prabhupraveen** [democratic-csi/democratic-csi#327]
I have a 6 node kubernetes on prem cluster, with 3 control plane and 3 worker nodes. I also have an ixsystems truenas server. I have been able to successfully configure nfs and iscsi democratic csi driver on the kubernetes cluster, and use them successfully on worker nodes.

I am trying to setup a custom backup cronjob on kubernetes that would backup the etcd running on the control plane nodes and store snapshot on the Truenas. Since I need to access the etcd folders on the control plane nodes, i need to run the job only on control plane nodes.

While I am able to run the job successfully using a local directory, when I try to run the job with a Truenas pvc created using democratic csi, the share wont mount, and would fail with the following error:

```
 Warning  FailedMount             3s (x8 over 67s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-9efcfd69-222c-4fd1-807c-e15ff8fb1c6a" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name org.democratic-csi.nfs not found in the list of registered CSI drivers
```

And the job wont start. I tried to search internet for any help on mounting pvcs to pods running on control plane nodes, but unable to find any. Are there any steps or help available to be able to mount pvcs to pods running on control plane nodes?

**Comment by d-uzlov** [comment]
If I remember correctly, democratic-csi doesn't deploy its pod on control plane by default.

Try adjusting your helm values like following:

```yaml
node:
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
```

**Comment by prabhupraveen** [comment]
Yes it doesn't I can see there are no csi-node pods running on control plane nodes.

Thanks for the configuration, I think this may be the solution. I will configure this and confirm how it went, might take some time as I need to do this on production cluster and I already have nfs and scsci mounts configured and being consumed by pods running on worker nodes, so need to do this without impacting production workload.
