### ISSUE TITLE
freenas-api-nfs: truenas Scale 23 nfs share unknown field: quiet

### ISSUE THREAD

**Issue by mdegouw** [democratic-csi/democratic-csi#333]
Truenas: SCALE 23.10-RC1
democratic-csi helm chart: 0.14.1

I'm unable to create nfs shares, the csi-driver gives to following error:

> {"host":"truenas-nfs-democratic-csi-controller-5894bcbb4b-cqqzj","level":"error","message":"handler error - driver: FreeNASApiDriver method: CreateVolume error: {\"name\":\"GrpcError\",\"code\":2,\"message\":\"received error creating nfs share - code: 422 body: {\\\"sharingnfs_create.quiet\\\":[{\\\"message\\\":\\\"Field was not expected\\\",\\\"errno\\\":22}]}\"}","service":"democratic-csi","timestamp":"2023-10-22T23:27:09.697Z"}

This is because democratic-csi add the field `quiet:false` but truenas doesn't recognise it
![image](https://github.com/democratic-csi/democratic-csi/assets/3748069/939d9dda-05ce-443e-8e90-3fb1b5228152)

Perhaps the api changed from truenas SCALE 22 -> 23
This is a screengrab from the swagger docs or truenas SCALE 23
![image](https://github.com/democratic-csi/democratic-csi/assets/3748069/8ee45820-f136-4bd1-a6b2-03b1535b25f6)
**quiet** is nowhere to be seen.

**Comment by mdegouw** [comment]
My Helm Values:
![image](https://github.com/democratic-csi/democratic-csi/assets/3748069/d72c2213-3938-464c-9772-0ff8365178a3)

**Comment by travisghansen** [comment]
Ok thanks for the report! I’ll get it cleaned up after a little research.

**Comment by mdegouw** [comment]
I saw your commits and changed the container to the next branch.
So far it works great, tnx!

Ill let you know if i run into problems.

**Comment by travisghansen** [comment]
Got a few more things to work through and then snap a release.

**Comment by rouke-broersma** [comment]
I also just hit this and am running `next` until it comes to main :)

**Comment by garcetto** [comment]
hit same problem, can someone help me understand how can i change container version to next in helm? thank you

**Comment by travisghansen** [comment]
This is now fixed in `v1.8.4`.

You can pin the tag using:
- https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L167
- https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L233
