### ISSUE TITLE
Synology suport "DSM 6.3+ is supported."

### ISSUE THREAD

**Issue by hardillb** [democratic-csi/democratic-csi#335]
Is `DSM 6.3+ is supported.` in the README.md a typo?

https://github.com/democratic-csi/democratic-csi/blob/1856b4fa295cec64aa84a0fcaf007f5271a27f9f/README.md?plain=1#L535

As far as I can see the latest version of DSM 6.x is "6.2.4-25556 Update 7"  or 7.x.

https://www.synology.com/en-global/releaseNote/DSM

Just trying to decide if I need to upgrade my NAS to 7.x

**Comment by travisghansen** [comment]
I run ci tests against the 6.2.4. I think that misguided comment in the readme is about the newer addon naming and which versions it’s available on.

In short 6.2.4 should run fine as long as you have all the iscsi bit enabled etc

**Comment by travisghansen** [comment]
To be clear I also run ci against 7.1-42661

**Comment by hardillb** [comment]
Thanks

**Comment by travisghansen** [comment]
Yeah! Welcome! I checked out your blog and you got some great stuff on there. You may be interested in this project: https://github.com/travisghansen/node-red-contrib-kubernetes-client
