### ISSUE TITLE
Allow storing non-secret configuration in configmap

### ISSUE THREAD

**Issue by rouke-broersma** [democratic-csi/democratic-csi#338]
I use a tool called sealed-secrets to encrypt all secrets such as api keys so I can store the secrets in git, however since the complete democratic-csi config is stored in a secret instead of only the secret bits I have to encrypt the whole config every time I make a small change. It would be more convenient if the config could be stored as a configmap or passed through the values directly and only the secret information was loaded from secrets.

**Comment by travisghansen** [comment]
Some context available here: https://github.com/democratic-csi/democratic-csi/issues/93#issuecomment-852404466

**Comment by rouke-broersma** [comment]
> Some context available here: [#93 (comment)](https://github.com/democratic-csi/democratic-csi/issues/93#issuecomment-852404466)

I see, that makes it more difficult. Perhaps some generic 'include from file here' templating in the config file could be used to make this generically usable? A similar approach is used in another product I've recently started using: https://github.com/buildarr/buildarr/issues/144

Also:

> Another tricky part with managing the secrets 'outside' the helm chart would be to ensure the pods restart when the secret has been updated. The chart currently generates a 'checksum' of the value to ensure pods roll as necessary.

Since secrets and config maps are loaded as volumes in the filesystem you should be able to use a filesystem watch to be notified about changes and restarting the relevant parts of the driver instead of rolling the pods. Assuming that this is not too complicated to do compared to just rolling. 

At the same time since external secret is already supported for the complete config the checksum rolling is already missing for users using that.

**Comment by rouke-broersma** [comment]
> For CI I do some very crude/controlled variable expansion. That gets a bit tricky with anything beyond the simplest of use-cases such as multi-line etc. If there’s a decent tool to do that I would happily add it.
> 
> The updated secrets problem has been solved now with most folks using this: https://github.com/stakater/Reloader

Not sure what kind of tools you're looking for but I think merging different yaml files with yq should be pretty straight forward. This would require the secrets to have the same structure as the config so they're merged at the correct key but I think that's fine.

**Comment by travisghansen** [comment]
I’m referring to any tool which is capable of doing env variable expansion in yaml.
