### ISSUE TITLE
Space reclamation flag with zfs-generic-iscsi driver is not supported 

### ISSUE THREAD

**Issue by Dixon3** [democratic-csi/democratic-csi#346]
I found the issue that there is no place to enable space reclamation flag with default zfs-generic-iscsi driver.

technically it required to set attribute emulate_tpu=1 on backstorage configuration somwhere there:
https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs-generic/index.js#L265

Some of such configuration was done for synology driver, but not with typical targetcli

https://github.com/democratic-csi/democratic-csi/blob/79f16a0cf636f376f394f9b10084d949004b1e62/ci/configs/synlogy/dsm6/iscsi.yaml#L22

Is it possible some how to support attributes in the current configuration with zfs-generic-iscsi driver?

I also try to find any default settings by targetcli, but issue is deeper, seems emulate_tpu is pass from kernel configuration wher it is 0 by default...

**Comment by travisghansen** [comment]
Yeah we can add that easily enough. Traveling currently but will be home in a couple weeks. Otherwise PR is welcome. There is an example block of code above for setting tpg attrs so we just need to copy that with a new a key essentially.
