### ISSUE TITLE
smb example for nomad

### ISSUE THREAD

**Issue by vacquah** [democratic-csi/democratic-csi#350]
I have an smb dataset on a truenas server I need to connect to my nomad cluster. I see examples for nfs and iscsi for nomad but not for smb [here ](https://github.com/democratic-csi/democratic-csi/tree/master/docs/Nomad/examples).

Can someone point me to a good example of csi smb on nomad? I am trying to mount smb shares for my media libraries ( so just want to consume the content in nomad). In this case should I jsut use the csi smb client instead?

**Comment by travisghansen** [comment]
For a preexisting shares you can use the csi driver or this driver deployed in the `node-manual` fashion. I don't know if any examples exist but it shouldn't be very difficult to achieve.
