### ISSUE TITLE
AxiosError: timeout of 60000ms exceeded

### ISSUE THREAD

**Issue by stepanovdg** [democratic-csi/democratic-csi#356]
TrueNAS-SCALE-23.10.1 
Created both shares for nfs and iscsi ( followed https://github.com/fenio/k8s-truenas guide). Only for iscsi created zvol and not dataset as dataset wasnt allowed to be shared through iscsi wizard (and also require not 0 size).
<img width="1151" alt="Screenshot 2023-12-27 at 08 39 49" src="https://github.com/democratic-csi/democratic-csi/assets/1208467/e4c78786-d65e-4f12-8f16-e413f4b72d15">
 
 After helm install node-pods are running but controller is constantly restarting.
 
 csi-driver (both similar nfs and iscsi)
    grpc implementation: @grpc/grpc-js
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"initializing csi driver: freenas-api-nfs","service":"democratic-csi","timestamp":"2023-12-27T07:12:16.920Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"starting csi server - node version: v16.18.0, package version: 1.8.4, config file: /config/..2023_12_27_07_12_12.2139132929/driver-config-file.yaml, csi-name: org.democratic-csi.nfs, csi-driver: freenas-api-nfs, csi-mode: controller, csi-version: 1.5.0, address: , socket: unix:///csi-data/csi.sock.internal","service":"democratic-csi","timestamp":"2023-12-27T07:12:17.653Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: GetPluginInfo call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.50.1\"],\"x-forwarded-host\":[\"localhost\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:12:18.569Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new response - driver: FreeNASApiDriver method: GetPluginInfo response: {\"name\":\"org.democratic-csi.nfs\",\"vendor_version\":\"1.8.4\"}","service":"democratic-csi","timestamp":"2023-12-27T07:12:18.570Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.51.0\"],\"x-forwarded-host\":[\"localhost\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:12:18.594Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.50.1\"],\"x-forwarded-host\":[\"localhost\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:12:18.746Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.54.0\"],\"x-forwarded-host\":[\"localhost\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:12:18.778Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"x-forwarded-host\":[\"localhost\"],\"user-agent\":[\"grpc-go/1.54.0\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:12:19.024Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-node-js/1.9.9\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:13:13.946Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"x-forwarded-host\":[\"localhost\"],\"user-agent\":[\"grpc-go/1.51.0\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:13:49.629Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"x-forwarded-host\":[\"localhost\"],\"user-agent\":[\"grpc-go/1.50.1\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:13:49.727Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"x-forwarded-host\":[\"localhost\"],\"user-agent\":[\"grpc-go/1.54.0\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:13:49.780Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.54.0\"],\"x-forwarded-host\":[\"localhost\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:13:50.030Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-node-js/1.9.9\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:14:14.044Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"error","message":"handler error - driver: FreeNASApiDriver method: Probe error: Error: FreeNAS error getting system version info: {\"errors\":{\"v2\":\"AxiosError: timeout of 60000ms exceeded\",\"v1\":\"AxiosError: timeout of 60000ms exceeded\"},\"responses\":{}} Error: FreeNAS error getting system version info: {\"errors\":{\"v2\":\"AxiosError: timeout of 60000ms exceeded\",\"v1\":\"AxiosError: timeout of 60000ms exceeded\"},\"responses\":{}}\n    at Api.getSystemVersion (/home/csi/app/src/driver/freenas/http/api.js:284:11)\n    at runNextTicks (node:internal/process/task_queues:61:5)\n    at listOnTimeout (node:internal/timers:528:9)\n    at processTimers (node:internal/timers:502:7)\n    at async Api.getIsScale (/home/csi/app/src/driver/freenas/http/api.js:160:27)\n    at async FreeNASApiDriver.Probe (/home/csi/app/src/driver/freenas/api.js:2190:13)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:18)","service":"democratic-csi","timestamp":"2023-12-27T07:14:18.737Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"error","message":"handler error - driver: FreeNASApiDriver method: Probe error: Error: FreeNAS error getting system version info: {\"errors\":{\"v2\":\"AxiosError: timeout of 60000ms exceeded\",\"v1\":\"AxiosError: timeout of 60000ms exceeded\"},\"responses\":{}} Error: FreeNAS error getting system version info: {\"errors\":{\"v2\":\"AxiosError: timeout of 60000ms exceeded\",\"v1\":\"AxiosError: timeout of 60000ms exceeded\"},\"responses\":{}}\n    at Api.getSystemVersion (/home/csi/app/src/driver/freenas/http/api.js:284:11)\n    at runNextTicks (node:internal/process/task_queues:61:5)\n    at listOnTimeout (node:internal/timers:528:9)\n    at processTimers (node:internal/timers:502:7)\n    at async Api.getIsScale (/home/csi/app/src/driver/freenas/http/api.js:160:27)\n    at async FreeNASApiDriver.Probe (/home/csi/app/src/driver/freenas/api.js:2190:13)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:18)","service":"democratic-csi","timestamp":"2023-12-27T07:14:18.784Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"error","message":"handler error - driver: FreeNASApiDriver method: Probe error: Error: FreeNAS error getting system version info: {\"errors\":{\"v2\":\"AxiosError: timeout of 60000ms exceeded\",\"v1\":\"AxiosError: timeout of 60000ms exceeded\"},\"responses\":{}} Error: FreeNAS error getting system version info: {\"errors\":{\"v2\":\"AxiosError: timeout of 60000ms exceeded\",\"v1\":\"AxiosError: timeout of 60000ms exceeded\"},\"responses\":{}}\n    at Api.getSystemVersion (/home/csi/app/src/driver/freenas/http/api.js:284:11)\n    at runNextTicks (node:internal/process/task_queues:61:5)\n    at listOnTimeout (node:internal/timers:528:9)\n    at processTimers (node:internal/timers:502:7)\n    at async Api.getIsScale (/home/csi/app/src/driver/freenas/http/api.js:160:27)\n    at async FreeNASApiDriver.Probe (/home/csi/app/src/driver/freenas/api.js:2190:13)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:18)","service":"democratic-csi","timestamp":"2023-12-27T07:14:18.808Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"error","message":"handler error - driver: FreeNASApiDriver method: Probe error: Error: FreeNAS error getting system version info: {\"errors\":{\"v2\":\"AxiosError: timeout of 60000ms exceeded\",\"v1\":\"AxiosError: timeout of 60000ms exceeded\"},\"responses\":{}} Error: FreeNAS error getting system version info: {\"errors\":{\"v2\":\"AxiosError: timeout of 60000ms exceeded\",\"v1\":\"AxiosError: timeout of 60000ms exceeded\"},\"responses\":{}}\n    at Api.getSystemVersion (/home/csi/app/src/driver/freenas/http/api.js:284:11)\n    at runNextTicks (node:internal/process/task_queues:61:5)\n    at listOnTimeout (node:internal/timers:528:9)\n    at processTimers (node:internal/timers:502:7)\n    at async Api.getIsScale (/home/csi/app/src/driver/freenas/http/api.js:160:27)\n    at async FreeNASApiDriver.Probe (/home/csi/app/src/driver/freenas/api.js:2190:13)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:18)","service":"democratic-csi","timestamp":"2023-12-27T07:14:19.043Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-node-js/1.9.9\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:15:13.704Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"error","message":"handler error - driver: FreeNASApiDriver method: Probe error: Error: FreeNAS error getting system version info: {\"errors\":{\"v2\":\"AxiosError: timeout of 60000ms exceeded\",\"v1\":\"AxiosError: timeout of 60000ms exceeded\"},\"responses\":{}} Error: FreeNAS error getting system version info: {\"errors\":{\"v2\":\"AxiosError: timeout of 60000ms exceeded\",\"v1\":\"AxiosError: timeout of 60000ms exceeded\"},\"responses\":{}}\n    at Api.getSystemVersion (/home/csi/app/src/driver/freenas/http/api.js:284:11)\n    at runNextTicks (node:internal/process/task_queues:61:5)\n    at listOnTimeout (node:internal/timers:528:9)\n    at processTimers (node:internal/timers:502:7)\n    at async Api.getIsScale (/home/csi/app/src/driver/freenas/http/api.js:160:27)\n    at async FreeNASApiDriver.Probe (/home/csi/app/src/driver/freenas/api.js:2190:13)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:18)","service":"democratic-csi","timestamp":"2023-12-27T07:15:14.008Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.51.0\"],\"x-forwarded-host\":[\"localhost\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:15:20.633Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.50.1\"],\"x-forwarded-host\":[\"localhost\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:15:20.731Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.54.0\"],\"x-forwarded-host\":[\"localhost\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:15:20.783Z"}
{"host":"nfs-democratic-csi-controller-57b8b54756-fpr84","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"x-forwarded-host\":[\"localhost\"],\"user-agent\":[\"grpc-go/1.54.0\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-12-27T07:15:21.034Z"}
running server shutdown, exit code: SIGTERM

Not sure how to get more logs.

Truenas - 10.5.6.8
K8s nodes 10.5.6.100-106
Pods 10.42.0.0/24

I can run shell in csi-driver or csi-proxy. 
csi-driver - not really anything to run
csi-proxy:
 - ping 10.5.6.8 is lost, ping to anything other (10.5.6.100 other nodes, 10.5.6.1 router) is working
 - nc 10.5.6.8 80 working
- 
netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      1 iscsi-democratic-csi-controller-67d8d8746b-v9sbj:60560 nas:http SYN_SENT    
tcp        0      1 iscsi-democratic-csi-controller-67d8d8746b-v9sbj:60574 nas:http SYN_SENT    
tcp        0      1 iscsi-democratic-csi-controller-67d8d8746b-v9sbj:60588 nas:http SYN_SENT    
tcp        0      1 iscsi-democratic-csi-controller-67d8d8746b-v9sbj:60586 nas:http SYN_SENT    
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node Path
unix  3      [ ]         STREAM     CONNECTED     10623671 /csi-data/csi.sock
unix  3      [ ]         STREAM     CONNECTED     10623666 
unix  3      [ ]         STREAM     CONNECTED     10623667 /csi-data/csi.sock.internal
unix  3      [ ]         STREAM     CONNECTED     10623673 /csi-data/csi.sock
unix  3      [ ]         STREAM     CONNECTED     10621554 
unix  3      [ ]         STREAM     CONNECTED     10621553 
unix  3      [ ]         STREAM     CONNECTED     10625067 
unix  3      [ ]         STREAM     CONNECTED     10625079 /csi-data/csi.sock
unix  3      [ ]         STREAM     CONNECTED     10625065 /csi-data/csi.sock
unix  3      [ ]         STREAM     CONNECTED     10625078 

i am using cilium native routing and nas is available on 10.5.6.8 from nodes.

**Comment by travisghansen** [comment]
The error fundamentally means the http client cannot connect to your TN box. Generally these are because something underlying is causing connectivity issues. For example a firewall etc. You can try to telnet to the http port from the controller container and see what you get.

**Comment by stepanovdg** [comment]
Thank you. Found was some issue with my network. 
Using native routing with cilium.
Was able to connect to any servers from pods in 10.5.6.0/24 network and just truenas wasnt working (as had several ip addresses due to vlan and default route was not aware of pods network. So adding static routes for pod network to use 10.5.6.8 interface worked.)
