### ISSUE TITLE
Multiple instances of CSI driver on one cluster?

### ISSUE THREAD

**Issue by inzanez** [democratic-csi/democratic-csi#361]
Hi

Is there a way to run multiple instances of the democratic-csi driver for a protocol on one given cluster? For instance, I have different storage pools that I would like to assign to different storage-classes but shared over the same protocol (NFS, iSCSI). Like this, I would like to distinguish between data for internal applications (LAN applications) and external applications (SaaS hostings).

It seems I can only have one setup for NFS CSI driver and therefore only have one storage pool & storage class. Is there a way around that which I might have missed?

**Comment by travisghansen** [comment]
Sure, just follow the guidelines here: https://github.com/democratic-csi/democratic-csi#multiple-deployments

**Comment by inzanez** [comment]
@travisghansen oh, thanks. I wonder how I managed to miss that ... :-/ Sorry about that!
