### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by austinterris** [democratic-csi/democratic-csi#363]
I've successfully got this working on my TrueNAS Scale machine using both iSCSI and NFS.  It works very well and is a life saver.  Unfortunately, I am having a couple of issues.  

Whether I'm using iSCSI or NFS, the persistent volume's user and group are always set to root.  I can change the securityContext for most apps, however some apps do not allow being run as root.  The remedy is to go to the TrueNAS interface and manually change the permissions of the child dataset but I was curious if there was a way to automatically do this on creation.

Thanks in advance!

**Comment by travisghansen** [comment]
`iscsi` should work fine with standard `securityContext` features (this is actually handled by kubelet, not the csi drivers). For `nfs` to work properly you should probably set the value here https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L40 to `File`.

Further info here: https://github.com/democratic-csi/democratic-csi/issues/274#issuecomment-1426922600
