### ISSUE TITLE
feat: ApiKey/Username&Password stored in secrets

### ISSUE THREAD

**Issue by simon-b64** [democratic-csi/democratic-csi#366]
Hey ^^
I really like democratic-csi and would like to deploy it via gitops (fluxcd)
In the current configuration I would have to commit my apiKey to git.
Would it be possible to add an option to configure the apiKey or the username&password with secrets?
Thanks in advance :)

**Comment by travisghansen** [comment]
The chart supports using a pre-existing secret. I would recommend templating with the values you need first to see the syntax and then you can handle it however you need.

https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L22
