### ISSUE TITLE
[BUG] (NVMEoF) scale-nvmet-start.sh fails to start on TrueNAS SCALE 23

### ISSUE THREAD

**Issue by crutonjohn** [democratic-csi/democratic-csi#370]
First off, thank you all for your hard work on this project.

I has come to my attention that upon upgrading from TrueNAS SCALE version 22 ("Bluefin") to version 23 ("Cobia") the [scale-nvmet-start.sh](https://github.com/democratic-csi/democratic-csi/blob/10af6c639b430af106be3ea769fcaddec1e5e9d3/contrib/scale-nvmet-start.sh) script fails to run. I believe there were some underlying changes made to the SCALE system Python that is preventing this from working.

Since I depend heavily on NVME-oF working I quickly threw together a script to get this working seen [here in a gist](https://gist.github.com/crutonjohn/9fa0bb368149cff189fa2ae89021a9e8) that refactors the script a bit to use functions and more importantly sets up a Python virtual environment to get everything working again.

This needs some further investigation but I only have the one TrueNAS system and use it for some important things so I can't really provide any more testing data other than the gist.

If this is found to be problematic for others I can upstream my script to this project. I'm thinking that they should either be broken up into `22-scale-nvmet-start.sh` and `23-scale-nvmet-start.sh` or perhaps someone could test my version of the script on 22 to verify that it works there as well and we could just keep it as a singular `scale-nvmet-start.sh`.

Let me know how I can help!

**Comment by travisghansen** [comment]
I made some slight changes to ensure it works on the upcoming 24 release.

In the config you'll need to set the following moving forward.

`nvmetcliPath: /root/.local/bin/nvmetcli` 

https://github.com/democratic-csi/democratic-csi/commit/6ada2684f3f53d371299b70125e1040f9ca390fb

24 makes the filesystem `ro` so it cannot install the `nvmetcli` script to `/usr/sbin/nvmetcli`
