### ISSUE TITLE
Origin of ISCSI initiator name

### ISSUE THREAD

**Issue by gjrtimmer** [democratic-csi/democratic-csi#375]
I have a question; I cannot find where the ISCSI initiator name comes from.
I would like to know where to configure this To create Hosts in my Synology identifying each node initiator.

I hope anybody has an idea.

I'm looking for where to configure `iqn.2004-10.com.ubuntu:01:cea0b497234a`. I have a single controller running, but I cannot find where this is configured. Nor can I find anything in the repository's code.

I have checked, the unique ID at the end is NOT one of the following:

- Hostname of controller Image
- Hostname of Node1 image
- Hostname of Node2 image
- Hostname of Node3 image
- Hostname of Node4 image
- Hostname of Node1
- Hostname of Node2
- Hostname of Node3
- Hostname of Node4
- /etc/iscsi/initiatorname.iscsi of any Node Image, Controller of Node hosts

Kind of lost where to configure this.

In my Synology, I see this:

<img width="946" alt="image" src="https://github.com/democratic-csi/democratic-csi/assets/6072255/8c8c8d8a-4d49-4806-b3c1-0fca8440c255">

**Comment by travisghansen** [comment]
Is .21 and .22 a server on your network with 2 nics? Or are those 2 separate nodes connecting with the same initiator iqn?

**Comment by gjrtimmer** [comment]
.21 and .22 are separate ubuntu nodes on the network. They are Node1, and Node2 of my Nomad cluster. I run a single controller, that is my current guess why they are the same. I have no idea why there are the same. I have a total of 4 Nodes

**Comment by travisghansen** [comment]
The controller shouldn't be managing that. What is the nature of the nodes (which os, how are they built, etc)? It seems to me that the initiatorname file got baked into a golden image or something.

**Comment by rouke-broersma** [comment]
For reference my Talos Kubernetes hosts have an initiator in the format `iqn.2016-04.com.open-iscsi:<some-host-specific-hashlike-string>` and it's different for every host.

**Comment by travisghansen** [comment]
Got a link to the os image you are using for that? I can take a peek and see if something is baked in.
