### ISSUE TITLE
Failed to create PVC via democracy-csi

### ISSUE THREAD

**Issue by cordeirolaffite** [democratic-csi/democratic-csi#386]
Hey guys.

I started using K8S not long ago, so I'm struggling a lot to get my cluster working properly.
Right now I'm having problems using my Truenas Scale storage with my K8S cluster via democracy-csi. And it is now that I come to ask for help to try to move forward.

Well, my cluster is assembled and my truenas configured, but my PVC does not go up.

Can you help me?

![Screenshot 2024-04-08 061013](https://github.com/democratic-csi/democratic-csi/assets/136263567/61f60e1a-1128-4951-bec9-fa5ff9339386)

**Comment by travisghansen** [comment]
Welcome! Can you send over the config you are using?

Also send the output of: `zfs get all CO_BSB/teste`

**Comment by cordeirolaffite** [comment]
I don't understand the reason for this zfs get query.

Attached files ...

root@bsbdtccpl01:~/yamls/democratic# zfs get all CO_BSB/teste
cannot open 'CO_BSB/teste': dataset does not exist
root@bsbdtccpl01:~/yamls/democratic#


[iscsi_api.yaml.txt](https://github.com/democratic-csi/democratic-csi/files/14916189/iscsi_api.yaml.txt)
[teste_dep.yaml.txt](https://github.com/democratic-csi/democratic-csi/files/14916190/teste_dep.yaml.txt)

**Comment by travisghansen** [comment]
Based on the error message it appears that either the pool you have configured does not exist or `/teste` is not a dataset but rather a zvol or doesn't exist.

**Comment by cordeirolaffite** [comment]
Created and configured

![image](https://github.com/democratic-csi/democratic-csi/assets/136263567/0b4bf633-4cbd-4d87-8d73-e9e3a6c55b4c)

**Comment by cordeirolaffite** [comment]
Sorry, the command was supposed to be typed in my storage and not in my control plane.

root@BSBDTCSTG01:~# zfs get all CO_BSB/teste
NAME          PROPERTY                 VALUE                    SOURCE
CO_BSB/teste  type                     volume                   -
CO_BSB/teste  creation                 Mon Apr  8  5:45 2024    -
CO_BSB/teste  used                     22.0G                    -
CO_BSB/teste  available                2.04T                    -
CO_BSB/teste  referenced               1.66M                    -
CO_BSB/teste  compressratio            18.37x                   -
CO_BSB/teste  reservation              none                     default
CO_BSB/teste  volsize                  22.0G                    local
CO_BSB/teste  volblocksize             128K                     -
CO_BSB/teste  checksum                 on                       default
CO_BSB/teste  compression              lz4                      inherited from CO_BSB
CO_BSB/teste  readonly                 off                      default
CO_BSB/teste  createtxg                290514                   -
CO_BSB/teste  copies                   1                        default
CO_BSB/teste  refreservation           22.0G                    local
CO_BSB/teste  guid                     13139239051006315253     -
CO_BSB/teste  primarycache             all                      default
CO_BSB/teste  secondarycache           all                      default
CO_BSB/teste  usedbysnapshots          0B                       -
CO_BSB/teste  usedbydataset            1.66M                    -
CO_BSB/teste  usedbychildren           0B                       -
CO_BSB/teste  usedbyrefreservation     22.0G                    -
CO_BSB/teste  logbias                  latency                  default
CO_BSB/teste  objsetid                 19645                    -
CO_BSB/teste  dedup                    off                      default
CO_BSB/teste  mlslabel                 none                     default
CO_BSB/teste  sync                     standard                 default
CO_BSB/teste  refcompressratio         18.37x                   -
CO_BSB/teste  written                  1.66M                    -
CO_BSB/teste  logicalused              7.25M                    -
CO_BSB/teste  logicalreferenced        7.25M                    -
CO_BSB/teste  volmode                  default                  default
CO_BSB/teste  snapshot_limit           none                     default
CO_BSB/teste  snapshot_count           none                     default
CO_BSB/teste  snapdev                  hidden                   default
CO_BSB/teste  context                  none                     default
CO_BSB/teste  fscontext                none                     default
CO_BSB/teste  defcontext               none                     default
CO_BSB/teste  rootcontext              none                     default
CO_BSB/teste  redundant_metadata       all                      default
CO_BSB/teste  encryption               off                      default
CO_BSB/teste  keylocation              none                     default
CO_BSB/teste  keyformat                none                     default
CO_BSB/teste  pbkdf2iters              0                        default
CO_BSB/teste  volthreading             on                       default
CO_BSB/teste  org.truenas:managedby    201.6.4.161              local
CO_BSB/teste  org.freenas:description                           local
root@BSBDTCSTG01:~#

**Comment by travisghansen** [comment]
Yeah, that should be a dataset, not a zvol (`type` should `filesystem` not `volume`).

**Comment by travisghansen** [comment]
You should probably configure a different parent value vs deleting that zvol assuming you are using it for something.

**Comment by cordeirolaffite** [comment]
So should I define a file system for my volume, and only then mount it?

**Comment by travisghansen** [comment]
The parent dataset is just a place to put the volumes, zvols will be created within that dataset and inherit any quotas/etc you place on the dataset. You won't actually try to store anything in the dataset directly via nfs/smb or directly on the nas.

**Comment by cordeirolaffite** [comment]
Very good, I hadn't understood that and that's why I wasn't successful.
Thanks ...

I was able to adjust the parameters in truenas.
Now I'm just left with a "Multi-Attach" problem between my "worker" servers.

![image](https://github.com/democratic-csi/democratic-csi/assets/136263567/12d77b1c-3713-4dac-9c24-0d1b7a50a71d)

**Comment by travisghansen** [comment]
iscsi vols can only be attached to 1 node at a time.
