### ISSUE TITLE
nvmeof targets not getting symlinked to port 1

### ISSUE THREAD

**Issue by depeo10** [democratic-csi/democratic-csi#387]
nvmeof

Hello,

I have tried to get nvmeof working on truenas scale.  I have started the scale-nvmet-start.sh and created the config as specified in the README.

I can create the pvc via kubernetes without any problems, and the config is being added into nvmecli.
But the "targets" are not getting symlinked to port 1, so In order to get the port to open I have to run this command.

ln -s /sys/kernel/config/nvmet/subsystems/nqn.2003-01.org.linux-nvme:pvc-53f47b4d-f85e-44e0-854a-8024ba237f54 /sys/kernel/config/nvmet/ports/1/subsystems/test

then in dmesg:
nvmet_tcp: enabling port 1 (0.0.0.0:4420)

In zfs-generic...yaml.
```
        # add more ports here as appropriate if you have multipath
        ports:
          - "1"
```		  
		  
Beginning of nvmecli-config.json
```
{
  "hosts": [],
  "ports": [
    {
      "addr": {
        "adrfam": "ipv4",
        "traddr": "0.0.0.0",
        "treq": "not specified",
        "trsvcid": "4420",
        "trtype": "tcp"
      },
      "ana_groups": [
        {
          "ana": {
            "state": "optimized"
          },
          "grpid": 1
        }
      ],
      "param": {
        "inline_data_size": "-1",
        "pi_enable": "0"
      },
      "portid": 1,
      "referrals": [],
      "subsystems": []
    }
  ],
  "subsystems": [
    {
      "allowed_hosts": [],
      "attr": {
        "allow_any_host": "1",
        "cntlid_max": "65519",
        "cntlid_min": "1",
        "model": "Linux",
        "pi_enable": "0",
        "qid_max": "128",
        "serial": "8ec9fe89f2954bb6be5d",
        "version": "1.3"
      },
      "namespaces": [
        {
          "ana": {
            "grpid": "1"
          },
          "ana_grpid": 1,
          "device": {
            "nguid": "00000000-0000-0000-0000-000000000000",
            "path": "/dev/zvol/storage/nvmeof/pvc-faf143da-344a-42ea-8590-d89990ebfb55",
            "uuid": "6d5032e5-d8f2-497e-9f6d-900a6aa32dbc"
          },
          "enable": 1,
          "nsid": 1
        }
      ],
      "nqn": "nqn.2003-01.org.linux-nvme:pvc-faf143da-344a-42ea-8590-d89990ebfb55"
    },
    {
      "allowed_hosts": [],
    . . .
  ```

Any idea what I'm doing wrong here?

**Comment by depeo10** [comment]
Never mind, I fixed it, it must have been some kind of mismatch in the config.

**Comment by travisghansen** [comment]
Great! Let me know how it goes.

**Comment by depeo10** [comment]
I had to symlink $SCRIPTPATH/nvmet-config.json to /etc/nvmet/config.json
Otherwise the scale bash script would restore an old config when running it.
