### ISSUE TITLE
Volume mount fails when resize fails

### ISSUE THREAD

**Issue by rouke-broersma** [democratic-csi/democratic-csi#392]
I tried resizing a volume and found out that the filesystem had some errors which block online resizing:

```
There are errors in the filesystem, so online resizing is not allowed
```

```
4m11s (x506 over 44m)    Warning   FailedMount          Pod/alpine                      MountVolume.Setup failed while expanding volume for volume "pvc-3e0e9bd7-5c3a-418f-b6a4-6f008acccca7" : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = {"code":1,"stdout":"Filesystem at /dev/sdl is mounted on /host/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.iscsi.hdd/0ee0287604124898644c00f65443d390c8f67b62f865064d56ec33147efbf033/globalmount; on-line resizing required\nold_desc_blocks = 1, new_desc_blocks = 1\n","stderr":"resize2fs 1.47.0 (5-Feb-2023)\nresize2fs: Permission denied to resize filesystem\n","timeout":false}
3m21s (x1318 over 28h)   Warning   VolumeResizeFailed   Pod/sabnzbd-7587cdf7bc-m6fnr    NodeExpandVolume.NodeExpandVolume failed for volume "pvc-3e0e9bd7-5c3a-418f-b6a4-6f008acccca7" : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = {"code":1,"stdout":"Filesystem at /dev/sdl is mounted on /host/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.iscsi.hdd/0ee0287604124898644c00f65443d390c8f67b62f865064d56ec33147efbf033/globalmount; on-line resizing required\nold_desc_blocks = 1, new_desc_blocks = 1\n","stderr":"resize2fs 1.47.0 (5-Feb-2023)\nresize2fs: Permission denied to resize filesystem\n","timeout":false}
```

However because the resize operation fails the volume is not mounted and the pod doesn't spin up. This also means that I can't spin up any pod with tools to fix the filesystem, so the resize can continue.

Ideally there would be a way for me to mount the volume into a pod even though resizing fails so I can fix the underlying problem.

Not sure if this is something within the influence of democratic-csi or if this is simply blocked by Kubernetes. Would appreciate any tips in dealing with these kinds of issues.

**Comment by rouke-broersma** [comment]
Worked around it by spinning up a separate machine, mounting the volume, and running fsck. Volume would then resize and mount properly in kubernetes. Then realized I could've also just spun up a pod and manually mounted the iscsi target in it instead of trying to use csi to do this.

Would love to hear if there's a better, kubernetes native way to manage the volume fs health.

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/democratic-csi/blob/master/examples/node-common.yaml#L8-L20

**Comment by rouke-broersma** [comment]
> https://github.com/democratic-csi/democratic-csi/blob/master/examples/node-common.yaml#L8-L20

Oh awesome! Thanks!

**Comment by travisghansen** [comment]
The csi team recommended against doing that a year or 2 ago back. I disagreed so I defaulted off but left the ability to enable for the sane among us :D
