### ISSUE TITLE
NFS thinks storage already exists with different size

### ISSUE THREAD

**Issue by RossWilliamson** [democratic-csi/democratic-csi#402]
For some reason I can no longer create NFS mounts.  Error is as below.  Confirmed no volume of same name.  Tried upgrading from helm with no joy.  System is now broken and no idea how to fix.  Don't want to go back to longhorn :(

_Warning  ProvisioningFailed    2s (x4 over 9s)  org.democratic-csi.nfs-client_nfs-democratic-csi-controller-676b4bfc87-rxd48_c2fb115a-516e-4baf-966e-e6cbb30c817c  failed to provision volume with StorageClass "democratic-nfs-client": rpc error: code = AlreadyExists desc = volume has already been created with a different size, existing size: -, required_bytes: 104857600, limit_bytes: 0_

**Comment by djjudas21** [comment]
FYI @RossWilliamson I'm running into the same thing so it isn't just you. I reported #406 before I spotted you'd already reported it.

FWIW, I've been running democratic-csi and TrueNAS for 2-3 years now and it has been extremely stable until this bug. Hopefully it will be resolved quickly.

**Comment by djjudas21** [comment]
@RossWilliamson You didn't mention what version your TrueNAS is running, but I just upgraded my TrueNAS from 23.10.2 (Cobia) to 24.04.1.1 (Dragonfish) and the problem magically went away. Let me know if this solves your problem too.

**Comment by boulc** [comment]
I just encountered the same issue, after a reboot of TrueNAS: a restart of the controller deployment solved the issue.
I rebooted again to try and it reoccurred.

Some system info:
- OS Version:TrueNAS-SCALE-24.04.1.1
- helm.sh/chart:democratic-csi-0.14.6
- registry.k8s.io/sig-storage/csi-attacher:v4.4.0
- registry.k8s.io/sig-storage/csi-provisioner:v3.6.0
- registry.k8s.io/sig-storage/csi-resizer:v1.9.0
- registry.k8s.io/sig-storage/csi-snapshotter:v6.3.0
- docker.io/democraticcsi/democratic-csi:latest (assuming v1.9.3)
- docker.io/democraticcsi/csi-grpc-proxy:v0.5.6

**Comment by f1reSong** [comment]
I had same issue and restarting of controller deployment with pvc solved issue:
```
kubectl -n democratic-csi delete pod democratic-csi-controller-678c877687-v6wh5
kubectl -n superset delete pvc data-superset-postgresql-0
```

I think some creation task is stucks by some reason on controller side, but no any related issue in controller logs.

**Comment by RossWilliamson** [comment]
> @RossWilliamson You didn't mention what version your TrueNAS is running, but I just upgraded my TrueNAS from 23.10.2 (Cobia) to 24.04.1.1 (Dragonfish) and the problem magically went away. Let me know if this solves your problem too.

I'm on TrueNAS-SCALE-22.12.2

Going to try the restart below by @f1reSong and see if that fixes it

**Comment by RossWilliamson** [comment]
> I had same issue and restarting of controller deployment with pvc solved issue:
> 
> ```
> kubectl -n democratic-csi delete pod democratic-csi-controller-678c877687-v6wh5
> kubectl -n superset delete pvc data-superset-postgresql-0
> ```
> 
> I think some creation task is stucks by some reason on controller side, but no any related issue in controller logs.

OK restarting the controller fixed the issue - Thanks!  Not sure of the root cause but do have a fix

**Comment by travisghansen** [comment]
Yeah, I need someone to turn on debug logging on the controller so when this happens I can see exactly what the nas is receiving/returning during the respective api requests.

**Comment by mattgruter** [comment]
@travisghansen How do I enable debug logging when installed with Helm? (I assume it's the csi-driver container that needs changing, right?)

**Comment by djjudas21** [comment]
@mattgruter I think you need to add this to your `values.yaml` and redeploy:

```yaml
controller:
  driver:
    logLevel: debug
```

**Comment by etokheim** [comment]
+1

I've also been encountering the same issue (with csi volumes) for about a month now. I just reinstalled the chart to get it up and running again.

**Comment by travisghansen** [comment]
Duplicate of #389
