### ISSUE TITLE
Couldn't get csi account to work instead of the root

### ISSUE THREAD

**Issue by sameeraman** [democratic-csi/democratic-csi#41]
Thank you for this great contribution!

I was trying my best to get the csi account to work instead of root account to do the ssh. I tried many things and couldn't get it work. 

1) I added NOPASSWD:ALL to the sudoers file using visudo. It didn't work. Furthermore, I noticed that when I rebooted truenas, this configuration is erased. 
2) I created a separate csi file under /usr/local/etc/sudoers.d/ and assigned NOPASSWD to zfs and zpool commands. 

I still get the following error. 
![image](https://user-images.githubusercontent.com/18417281/103201568-1f26f400-492b-11eb-9ab3-4a12d9747d53.png)

I can manually ssh into the truenas using the csi account. I can run the zfs to create a volume without password prompts, however, I have to run it as sudo. Otherwise, I get the same "permission denied" error. 

Am I doing anything wrong here ? or the storage controller is not executing the commands as sudo ?

**Comment by travisghansen** [comment]
Hey! Welcome to the project! I do have a ticket with ixsystems to make an option for the nopasswd in the gui so it persists reboots etc. Hopefully we’ll have that soon.

Can you send over your config? I’m guessing you simply haven’t set the `sudoEnabled` flag which actually tells it to use sudo vs simply changing the user in the connection.

**Comment by sameeraman** [comment]
@travisghansen thanks for that! Yes, there was a flag for it in the config file. I enabled it, and it works fine now. However, will have to wait for the NOPASSWD persistent support from the GUI. 

by the way, I have also added the API key, when is that used?

**Comment by travisghansen** [comment]
Great! apiKey is used for creating all the share related assets (nfs share, iscsi targets, extents, etc). All zfs/volume operations are done over ssh and avoid the http api entirely.

**Comment by sameeraman** [comment]
Nice work! thanks for the help.
