### ISSUE TITLE
[zfs-generic-iscsi] Add support for tgt (tgtadm)

### ISSUE THREAD

**Issue by joaquinrovira** [democratic-csi/democratic-csi#413]
Hello,

I have been looking into this project to provide support for dynamically provisioned PVs from an external ZFS pool.
My "homelab" currently consists of two `amd64` devices based on Rockchip RK3588 SoC. One of them has 4x2TB SSD attached and a ZFS pool configured.

I was following the docs for setting up `zfs-generic-iscsi` but the device kernel has issues with missing kernel modules. In particular it is missing `target_core_mod`. I am unable to compile the Linux kernel with the module included. 

Would it be possible to add support for `tgt` - a userspace alternative to `targetcli`?

I have successfully shared an iSCSI volumen between both devices device so I know it is possible. I am familiar with NodeJS and I could be up to the task. Some guidance would be appreciated.

**Comment by travisghansen** [comment]
Welecome! Code would be welcomed for sure, everything you need would be done in here: https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs-generic/index.js

`createShare` gets invoked and a new implementation would be wholly self contained in that file with the rest handled automatically. The existing bits should be pretty readable/understandable.

Having said that, unless you have a specific reason it may be easier to simply use the `nvmeof` driver instead. Server-side the only requirements are essentially any modern kernel version.

**Comment by joaquinrovira** [comment]
Thank you for the quick response! I'll make sure will read about `nvmeof`. I have never used it. 

If it does not my problems I will reopen this issue and try to publish a PR that adds support for `tgtadm`.

**Comment by travisghansen** [comment]
No problem! nvmeof is the same concept as iscsi, just sharing over the nvme protocol instead of scsi. The underlying storage does not have to be nvme, everything will ‘just work’ no matter what you have as the actual storage for the pool.

**Comment by joaquinrovira** [comment]
Sadly, the necessary kernel modules were also missing in order to use `nvmeof`. The chips are pretty now and not very supported. I am going to use `smb` for now. It's a toy homelab and I still have much to learn. Maybe I'll attempt the `tgt` support RP anyways. It will surely achieve better I/O speeds.

Thank you for your great work - awesome project!

**Comment by travisghansen** [comment]
Why smb over nfs? smb is really only there for clusters with windows nodes.

**Comment by travisghansen** [comment]
If you’re looking for a user space solution you can use spdk: https://spdk.io/ with the nvmeof driver (it would be pretty easy to port iscsi with spdk as well).

However, spdk is supposed to have very high performance, but because it runs in userspace with a while true it keeps the cpu at 100%. That may not be an issue or concern for you though.

**Comment by joaquinrovira** [comment]
From what I have read nfs is unsecured by default. I do not want the NFS share to be open to my home network. SMB provides an easy way to require some level of credentials without having to deploy and manage Kerberos. You could always limit the IP ranges but I do not want to be managing IPs by hand if possible.
