### ISSUE TITLE
Add support for imagePullSecrets

### ISSUE THREAD

**Issue by asgeirn** [democratic-csi/democratic-csi#420]
Add support for imagePullSecrets in values, according to helm/helm#5271

I often get rate-limited on pulling `docker.io/democraticcsi/democratic-csi:latest`, so being able to inject my docker.io login secret would help tremendously.

**Comment by travisghansen** [comment]
Please open this in the charts repo. Contributions welcome and also note the images are simultaneously published to ghcr.

https://github.com/democratic-csi/democratic-csi/pkgs/container/democratic-csi
