### ISSUE TITLE
Iscsi example on regular FreeBSD 14.1?

### ISSUE THREAD

**Issue by depeo** [democratic-csi/democratic-csi#430]
Hi,

Is it possible to use this on a normal FreeBSD 14.1-host?
Truenas Core is more or less EOL now, and I still want to use FreeBSD.

the zfs generic iscsi uses targetcli, so that won't work, and the freenas-iscsi.yaml seem to have to connect to the truenes web server, so that probably won't work either? Is it possible to remove the httpconnection requirement?

Thanks!

**Comment by travisghansen** [comment]
Welcome! Not currently no, but support would likely be very easy to add. Essentially we need the commands to run on the freebsd box directly to  create the iscsi assets. Essentially a new strategy in this file: https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs-generic/index.js

**Comment by travisghansen** [comment]
Are you aware of an equivalent to targetcli for freebsd that can be used to manipulate the ctl.conf file? It appears the ctl command isn’t used to manage that file at all?

**Comment by depeo** [comment]
I don't know, but I looked into it now, and I didn't find anything, I guess it would be quite messy to manage a conf file manually via democratic-csi.

**Comment by travisghansen** [comment]
Writing a parser to manage that would be an undertaking and making sure the file has a proper global mutex on it etc would be tricky. There’s got to be something…

**Comment by travisghansen** [comment]
Not sure what exactly is running on your server but freebsd supports spdk, I have support for that. It works already to share over nvmeof but if you really need iscsi that would likely be doable easily enough. Thoughts?

**Comment by depeo** [comment]
Ah, nvmeof is fine, didn’t know that existed on BSD, thats probably faster than iscsi anyway.

I actually tried nvmeof (nvmetcli) on Linux a while back, but I kept getting kernel panics and reboots, but that was probably Some Linux bug.

**Comment by travisghansen** [comment]
Well, spdk runs outside the kernel. The odd thing people find with it is that it appears the cpu is running 100% all the time due to running in userland and being a while true loop. Anyway, if you want to give it a try just try and compile it on freebsd and see what you get.

**Comment by depeo** [comment]
I tried spdk now but it's not really viable due to the massive cpu usage, it seems to be a very weird design choice to use those while loops. 🤨

Would be great with proper support for ctld in democratic-csi., but I fully understand if it won't happen due to the work involved.

**Comment by travisghansen** [comment]
My understanding is that the 100% is a bit of a bogus number and that the cpu isn’t really doing 100%. Haven’t dug into it deeper than that though.
