### ISSUE TITLE
Handling a Domain Name Change?

### ISSUE THREAD

**Issue by Routhinator** [democratic-csi/democratic-csi#434]
Hey there, I am trying to work out how to handle a domain name change. I used a `.io` address in my home and public networks and with the looming possibility that `.io` gets deprecated I have switched to a new TLD - everything seems to work but old volumes seem to be "stuck" on the old Truenas domain so I've had to provide a CNAME for now. 

How do we update the target hostname for existing volumes?

**Comment by travisghansen** [comment]
Hi! Use this https://github.com/democratic-csi/democratic-csi/blob/master/contrib/pv-updater.sh

Read the code thoroughly and test it with garbage PVs but it will do what you need. Effectively you need to recreate all the PVs and that script handles the tricky logic for you.

**Comment by Routhinator** [comment]
Thanks! will give that a go

**Comment by Routhinator** [comment]
Hmmm not sure what OS that script was built on, but `yq` at least in Arch, does not have an `eval` subcommand - so the script gets to line 46 and bombs out - trying to trace back to what version of `yq` may have been used and what that subcommand originally did.

**Comment by Routhinator** [comment]
Oh

> Note that (as of 4.18.1) this is the default command when none is supplied to yq.

https://mikefarah.gitbook.io/yq/commands/evaluate

**Comment by Routhinator** [comment]
Ok, I have had this work now - I will open a PR. In addition to the `eval` change, this line now results in the `reclaimPolicy` var containing wrapping `""`

```shell
reclaimPolicy=$(yq '.spec.persistentVolumeReclaimPolicy' "${PV_ORIG_FILE}") 
```

So line 72 needed to change to:

```shell
kubectl patch pv "${PV}" -p "{\"spec\":{\"persistentVolumeReclaimPolicy\":${reclaimPolicy}}}"
```

To avoid:

```shell
+ kubectl patch pv pvc-0de79afe-ecd8-4590-b878-38ca33f9478d -p '{"spec":{"persistentVolumeReclaimPolicy":""Delete""}}'
Error from server (BadRequest): invalid character 'D' after object key:value pair
```

**Comment by travisghansen** [comment]
Thanks!
