### ISSUE TITLE
Possible to grab the same zvol after deleting and recreating pvc?

### ISSUE THREAD

**Issue by dstotz** [democratic-csi/democratic-csi#44]
This is a question, not a bug report. Forgive me, I'm pretty new to Kubernetes storage so this may not make much sense.

I was wondering if it is possible to grab the same zvol even if the pvc is deleted. For instance;
1. Have the democratic-csi storage class reclaimPolicy set to Retain
2. Deploy a pod and pvc
3. Create some data
4. Delete that pod and pvc
5. Recreate the same pod and pvc later down the line and want to use existing zvol so I have the existing data

I tried setting a volumeName on the pvc thinking that would name the created zvol for future grabs, but it just left the pvc in pending.

**Comment by travisghansen** [comment]
I would use the snapshot feature (you would have to use a detached snapshot if you wanted to be able to delete the original pv) but read through this and let me know if it help...

https://stackoverflow.com/questions/34282704/can-a-pvc-be-bound-to-a-specific-pv

**Comment by dstotz** [comment]
@travisghansen thanks for the suggestion. I took a look at the link and it looks like it theoretically would be possible if I were to create the pv myself and include all the csi information there, and just reference that pv with my pvc.

I took a look into the snapshots and it seems like it would solve my issue, but I wasn't able to get detached snapshots working properly. I'm assuming this is due to my lack of knowledge though and not an issue here. But if you have any example files of what a pvc and sv should look like using democratic-csi, I'd be interested in trying. Here is as far as I got

```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myapp-config
spec:
  storageClassName: truenas-isci
  dataSource:
    name: myapp-config-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
kind: VolumeSnapshot
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: myapp-config-snapshot
spec:
  volumeSnapshotClassName: truenas-iscsi-csi
  source:
    persistentVolumeClaimName: myapp-config

```

and the relevant parameters in my helm values file I'm setting

```
storageClasses:
  - name: truenas-isci
    reclaimPolicy: Retain
    volumeBindingMode: Immediate

volumeSnapshotClasses:
  - name: truenas-iscsi-csi
    parameters:
    detachedSnapshots: true
    secrets:
      snapshotter-secret:

driver:
  config:
    driver: truenas-iscsi
    zfs:
      datasetParentName: k8s/vol
      detachedSnapshotsDatasetParentName: k8s/snap
```

These are the events on the pvc
```
Events:
  Type     Reason                Age                From                                                                                                           Message
  ----     ------                ----               ----                                                                                                           -------
  Warning  ProvisioningFailed    12s (x2 over 12s)  modlab-truenas-isci_zfs-iscsi-democratic-csi-controller-77865fbbcf-nsjw9_45256a39-0138-49c2-a580-9ce4265ac0f0  failed to provision volume with StorageClass "truenas-isci": error getting handle for DataSource Type VolumeSnapshot by Name myapp-config-snapshot: error getting snapshot myapp-config-snapshot from api server: volumesnapshots.snapshot.storage.k8s.io "myapp-config-snapshot" not found
  Normal   ExternalProvisioning  12s (x3 over 12s)  persistentvolume-controller                                                                                    waiting for a volume to be created, either by external provisioner "modlab-truenas-isci" or manually created by system administrator
  Normal   Provisioning          7s (x4 over 12s)   modlab-truenas-isci_zfs-iscsi-democratic-csi-controller-77865fbbcf-nsjw9_45256a39-0138-49c2-a580-9ce4265ac0f0  External provisioner is provisioning volume for claim "default/myapp-config"
  Warning  ProvisioningFailed    7s (x2 over 11s)   modlab-truenas-isci_zfs-iscsi-democratic-csi-controller-77865fbbcf-nsjw9_45256a39-0138-49c2-a580-9ce4265ac0f0  failed to provision volume with StorageClass "truenas-isci": error getting handle for DataSource Type VolumeSnapshot by Name myapp-config-snapshot: snapshot myapp-config-snapshot not bound
```

And these are the events from the volumesnapshot
```
Events:
  Type     Reason                         Age    From                 Message
  ----     ------                         ----   ----                 -------
  Warning  SnapshotContentCreationFailed  2m27s  snapshot-controller  Failed to create snapshot content with error failed to get input parameters to create snapshot myapp-config-snapshot: "the PVC myapp-config is not yet bound to a PV, will not attempt to take a snapshot"
```

So it seems like the pvc can't be created because the snapshot doesn't exist and the snapshot can't exist until the pvc is created. So I'm definitely missing something here. Thanks in advance for any help.

**Comment by travisghansen** [comment]
Hey! Been a little busy and wasn't able to reply. I think you've got an order of operations issues with the above.

You need to do the following:

- create pvc A (no datasource)
- add data, do whatever in terms of populating with data
- create a snapshot of pvc A
- delete pvc A (assuming you want to use the same name)
- create pvc A with the datasource set to the snapshot

Does that make sense?

**Comment by dstotz** [comment]
@travisghansen that definitely makes sense now that I hear it! Thanks a bunch! I'll go ahead and close this issue since you answered all of my questions! Thanks again!

**Comment by travisghansen** [comment]
Alternatively:

- Create PVC with arbitrary name
- populate with data manually/out of band of your app
- create your app with pvc with source set to above PVC

The matrix is pretty big in terms of options and features depending on whether you use detached snapshosts and and the detachedVolumesFromSnapshots/detachedVolumesFromVolumes options on the storage class. They should all 'just work' but if you run into something weird let me know!

**Comment by dstotz** [comment]
Will do! Thanks again!

**Comment by dstotz** [comment]
@travisghansen I was working on my config again and accidentally tricked democratic-csi into doing exactly what I was looking for in the beginning where it will keep using the same zvol even if the entire cluster is torn down and built back up using a deploy script.

By setting
```
storageClasses:
    reclaimPolicy: Retain

iscsi:
      nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
```

It will reuse the existing iSCSI target already set up on Truenas that has the same name and that target points to the zvol that was previously created and has all the data on it.

It does still create a new zvol too, but thats easy to clean up when/if it happens.

**Comment by travisghansen** [comment]
Ah yeah that’s kinda a bug actually :( I should probably confirm the target points to the correct zvol when it already exists and if not throw an error.

**Comment by dstotz** [comment]
Bummer :( Another thought would be to lean into this bug and allow named resources end to end and it would do a "find or create" type logic. If the pv could have a desired name passed from the pvc instead of using the auto-generated one to create the zvol, then this bug could become a supported feature haha.

**Comment by travisghansen** [comment]
That's actually how the previous nfs-based provisioners worked/works...things are a bit more tricky with csi.

The challenges primarily are:

- k8s had no way of passing that information down to the csi driver (pv/pvc are k8s-isms that are not part of the csi spec). That has since changed and the pvc name/namespace can be passed in as parameters so it's hypothetically possible
- specifically with iscsi there's the problem with zvol name length (the 63 char issue). If I *do* allow setting the volume name templatized (like the `nameTemplate` parameter for iscsi) then very easily that limit could be passed (namespaces and pvc name can be up to 255 chars each I believe) resulting in non-functional volumes

Damn limits! :) but in all seriousness I would love to be able to support that, the killer is that bottom point though...it's a pretty highly likely scenario to hit that quickly. We could potentially introduce some kind of heimdall/sha/md5 hash of the name/namespace combo to keep things deterministic and still remain under the 63 char limit...

**Comment by travisghansen** [comment]
That's a bit of an undertaking honestly but certainly possible. You actually need to hack a bunch of details in the `PV`s, probably not much in the `PVC`s if anything.

There a simple script (meant to be run from your workstation directly) available here: https://github.com/democratic-csi/democratic-csi/blob/master/contrib/pv-updater.sh

Beyond that (although probably not really an issue in k8s) I set a bunch of zfs properties that include a bunch of details regarding the share etc which technically should be updated.

**Comment by travnewmatic** [comment]
thanks other travis! :)

my solution was to actually learn about how truenas does iscsi things and recreate the various things (in truenas and in the cluster) manually.  was a little tedious, it wasn't really that bad.  i dont have so many PVs.

really the lesson is:  if democratic-csi makes it, leave it alone.  also, if you move to a new apartment, put all your crap on the same subnet that you were using before :)

**Comment by travisghansen** [comment]
I will note that it’s also possible to use the `node-manual` driver to connect to existing assets not managed by democratic-csi at all. Not exactly what your situation was but something to note.
