### ISSUE TITLE
Add support for dataset parents that are longer than 17 characters

### ISSUE THREAD

**Issue by venezia** [democratic-csi/democratic-csi#54]
Hi

From [current iscsi example config](https://github.com/democratic-csi/democratic-csi/blob/v1.0.1/examples/freenas-iscsi.yaml#L47-L54) I appreciate that kubernetes names have to conform to a subset of specific characters / length less than 64, and that names must adhere to ZFS naming structure, but I feel that by by only allowing 17 characters in the dataset parent path we may be excluding otherwise acceptable ZFS environments.

I personally have an environment that won't work effectively with this 17 character limit, in part because the ZFS environment was created before knowledge of this 17 character limit for this project.

Just spitballing but what if instead of using the full path to the location on ZFS as the kubernetes name value, we hash the path as the name (thus ensuring compliance) and have an annotation on the object that reveals the full path.  This way kubernetes limitations do not cross into limitations within the ZFS environment.

**Comment by travisghansen** [comment]
Yeah it's an unfortunate situation honestly. It may be possible to add some hashing functionality. Another (probably cleaner option) would be to:

- set the `--volume-name-uuid-length` parameter in the `external-provisioner` arguments which let's you truncate how large the volume name is that k8s generates.
- https://github.com/kubernetes-csi/external-provisioner/tree/v2.0.4 (see this link for details)

As an example:

```
# default results in a name like below
pvc-0226ae59-18d3-49a8-92a1-c5e0feb1c506

# if you set the above to something like 8 the name would be like
pvc-0226ae59
```

That gives you an extra 28 chars to use in the dataset naming but limits the total number of unique volume names you can have (even with 8 chars 'only' it's still a huge amount of volumes so I wouldn't be bothered by it).

Currently the chart doesn't support setting a value for that param but if you could try this out in theory and let me know if it works we can add support to the chart and you should be on your way :)

**Comment by venezia** [comment]
Thanks for the response!

So I tried out having `--volume-name-uuid-length=8` set in the deployment (for the `external-provisioner` container) and adjusted the configuration yaml accordingly with a 38 character length `detachedSnapshotsDatasetParentName` and things worked just great - `pvc-46733d77` was an example persistent volume record created

I agree - 8 hexadecimal digits is 32 bits which is a ridiculous amount of volumes that you could have relative to the limit of iscsi targets that you are capped with, etc.

In general I think it would be great to add this support ... also a little bit more samples on the chart might be nice.  I was scrounging around for how to handle credentials properly before finding #13 - but maybe I was just reading in the wrong places.

Unsure where to go from here - I could offer a PR on the helm repo if you want, etc.

**Comment by travisghansen** [comment]
Great! Glad it worked out!

I’ll update the chart to support setting those flags and also document the chap settings in the relevant examples. I’ll make sure to shout out here when it’s done and won’t close the issue before then.

**Comment by travisghansen** [comment]
OK, just snapped a new chart version `0.7.0` with greatly expanded control over this kind of thing.

Try this:

```
controller:
  externalProvisioner:
    extraArgs:
    - --volume-name-uuid-length=8
```

Let me know how it goes.

**Comment by venezia** [comment]
Sorry for the delay in responding - I tried this out, its seems to working great!

On a different note, you may want to consider stuffing the driver on a different provider than docker hub, like maybe quay.io or some other public alternative.  I seem to always reach my limit with docker hub now that they rate limit and all the other images are hosted on k8s.gcr.io, etc.  I vendored democratic-csi now, but for others it might be nice, etc.

Thanks so much!

**Comment by travisghansen** [comment]
Great! A new hub is on my list for sure. Just haven't gotten around to it yet.
