### ISSUE TITLE
Is there a way to change the targetportal IP for existing PVs?

### ISSUE THREAD

**Issue by djbobyd** [democratic-csi/democratic-csi#58]
Hi,
First I would like to say that I am extremely grateful for having such a nice implementation. It works perfectly for my small home setup. Thank you for that!

Now for my question, I 've recently upgraded the networking of my TrueNAS server by adding 10Gbe card to it. Everything is working as expected and now I am wondering how to make my existing PVs use this new connection. 

It is an additional card with different IP and my old card is still in use but it is only 1Gbe. I can deploy the drivers with the updated IP for 10Gbe card, but this does no change the existing PVs and as far as I understand it I cannot directly edit the PVs. 

One option will be to do so kind of volume migration with for example velero or even manual but I was hoping for a simpler approach giving that it is still the same server just the IP should be changed.

Thanks in advance for your help!

**Comment by travisghansen** [comment]
I'm actually a step ahead of you on this. I've been thinking about it for some time now and have a couple ideas but nothing ready yet. In any case, it's something I'm very aware of and will be addressing, just not sure on your time frame :(

**Comment by djbobyd** [comment]
Hi,
I am not in a hurry as the old network card will continue to exist and as I said this is a home server, thus nobody is pushing me to improve the performance. Still it is nice to be able to use 10Gbe connection when one is already available :)

Thanks for your efforts!

**Comment by travisghansen** [comment]
Yup! I would recommend using a dedicated host name for this access in the future that make that not be an issue.

**Comment by djbobyd** [comment]
Yeah, I would normally agree with you, but in the case of adding a new interface without removing the old one you would usually want to preserve the old hostname for the old interface, to be used by other services, and add a new hostname for the new interface. Thus rendering the idea of hostnames useless in this scenario. 
I could also use a virtual IP, but that would have the same result if I want to reserve the same IP for the old interface to be used by other services, and use the new interface for the kubernetes cluster only.

And this leaves us with the possibility to somehow change the existing PVs to use the new IP, maybe by utilizing the new volume cloning feature or by some other clever ideas that you might have :)

**Comment by travisghansen** [comment]
Yeah, I would create per-portal host aliases pointing to whatever IP (meaning, it doesn't preclude you from using the IP with other hostnames for other purposes).

In any case, on my list is to look into is:
- save a PV to yaml
- remove finalizers on the PV in the cluster
- delete the PV in the cluster
- recreate the PV after mucking with the yaml (restoring the link to the pvc, finalizers, etc)
 
It's just a theory currently but something that may work without any harmful side-effects...don't try with a real/production workload in case my theory is wrong :) If it does work, it opens up quite a few opportunities to migrate from the old provisioners etc.

**Comment by djbobyd** [comment]
here is what I tried on a NFS based PV.
* I created a test PVC which created some PV.
* I changed the reclaim policy of the PV to Retain.
* I saved the PV to yaml
* I tried to remove the finalizers of the PV but kubernetes wouldn't let me. Well technically there was no error saving the PV after removing the finalizers, but when I open it again the finalizers are there again.
* I then removed the PVC as otherwise I was not able to delete the PV. (the PVC finalizers were also automatically recreated, so they cannot be deleted too)
* I deleted the PV
* I have modified the saved PV to point to the other IP and deployed it. This worked flawlessly and I now have the same PV pointing to the same dataset but through a different IP.

Overall it is a partial success, however the point with deleting the PVC is not very convenient. This is what was available through userland tooling. It is possible that you can do more via the API or some internals but I am not that familiar with the design to comment on that.

**Comment by travisghansen** [comment]
Thanks for trying it! Interesting. I wonder if a delete with —force ignores the finalizers. My goal would be to just delete the pv behind the scenes so any workloads using the pv/pvc continue to function for the momentary period that the pv reference is gone.

**Comment by djbobyd** [comment]
that is the result of force deletion. It writes that it has deleted the PV but actually the command never exits and just hangs.

`kubectl delete pv pvc-dcd5c190-3378-470d-875f-5316dff2e6a0 --force
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
persistentvolume "pvc-dcd5c190-3378-470d-875f-5316dff2e6a0" force deleted
`

Additionally the PV continues to run on the cluster

**Comment by travisghansen** [comment]
Did it still appear doing `get pv` after killing the command? I'm near certain that's the finalizers kicking in.

**Comment by djbobyd** [comment]
Yes it does

`pvc-1a08f232-a981-4f87-b392-15ee5882ee11   1Mi        RWX            Delete           Terminating   default/test-claim                                                     
`

**Comment by travisghansen** [comment]
Yeah, dang. I'm gonna ask around and see if it's possible to somehow ensure the finalizers don't get added for a period of time to make this all possible...

**Comment by djbobyd** [comment]
I did some more testing and I managed to delete a PV that was bound. 
It was all in the sequence. You have to:
* first copy the PV .yaml file
* delete the PV, it will stay in status deleting as it is protected by the finalizers
* then you go and delete the finalizers
* and voila the PV disappears
To restore it again you have to create the PV from the saved .yaml but in order for it to work you have to delete resourceVersion field. It will automatically bind in a couple of seconds.

So it is not impossible to implement it ;)

**Comment by travisghansen** [comment]
As an FYI I haven't forgotten, nobody is responding quite yet :( This sounds relatively sane but the danger resides in what exactly is holding up the deletion:

- the fact that a workload has the PV mounted?
- the fact that a PVC is still connected to it?

If it's the former it's dangerous if a pod isn't in use and it *actually* delete before you can remove the finalizers. If it's the latter then it's probably safe enough.

An alternative to get around the 1st issue would be to:

- save yaml of all relevant PVs
- set the reclaim policy to `Retain` on all of them
- delete them
- edit PVs in the yaml to your liking
  - remove the `resourceVersion` field
  - update connection parameters as appropriate

That should do the trick. If so, a handy little script to automate this allowing for selectors on which PVs to export would be fantastic.

In the more complex use-use case of using it to migrate from the old (non csi) provisioners to the new it would need a bit more massaging but seems doable.

**Comment by djbobyd** [comment]
I am not sure what is holding it, but it seems that the deletion of PV does not unmount it from the pod. I suspect these are 2 entirely different operations. The PV is just a description of the volume that exists somewhere. The actual mount is hold by the container and since we do not really delete the physical carrier the mount is not disrupted only the metadata that it exists. We then restore the metadata and it looks fine. 
Of course the volume that is mounted in the container is still pointing to the old IP so to make it start using the new one you just have to restart the pod, which is relatively safe operation. 
I validated it both with nfs and iscsi that after rebooting the pod it reattaches the volume through the new IP address that I've updated in the metadata(the PV)
So far things seems doable. It will require a bit of planning which volumes to edit and when, which pods to restart and when , but it looks like it will work. I have backups for all volumes of course and will first test that the restore procedure is working before going forward with this :-)

**Comment by travisghansen** [comment]
Yeah I don't think the workloads will drop if they are currently using the updates, that's correct.

Did you change the `Retain` parameter in your second test? That's for sure the safest way to go.

**Comment by djbobyd** [comment]
Hi, 
Yeah, the "Retain" parameter is a must. With regards to provisioning a new volume it doesn't seem to be the case. I deleted one PV in the above described way and before I recreate it I was interrupted by a call. 10 minutes later there was still no new volume created and I just created the PV from the saved .yaml and it was fine. I checked the status of the PVC and it was in status "Lost". It seems that kubernetes does not try to create a new PV when the PVC is in this status. I see it for the first time and have no idea what it means but it fits the current exercise :-)

**Comment by travisghansen** [comment]
Yeah, this is all really good news then. There's a feasible path to move not only your use-case but also the old provisioners which is fantastic. Thanks for doing all the tests/research!

**Comment by djbobyd** [comment]
No problem, it was a useful exercise. 
I can now confirm that I was able to migrate all my PVs successfully with the above described procedure. They are all working fine even a full restart of the whole cluster due to hardware maintenance.
If you like you can keep this issue open until some more automated implementation is available but my problem is now resolved.
Thanks a lot for your cooperation and guidance during testing. I really like what you have created. Keep up the good work! 

BTW: are there some donation possibilities? I would like to at least buy you a beer ;-)

**Comment by travisghansen** [comment]
Thanks for the kind words and offer of a beer! Maybe someday if I travel to your part of the world I'll take you up on that.

So I've spent some time the last couple days putting together a process to migrate from the old non-csi based provisioners (similar to this request, but much broader in scope). I have that fully working and have migrated several of my own clusters over so I can get rid of the non-csi bits now.

In any case, during that process I realized I forgot to mention to you that technically you should also update some zfs properties on the zvols/datasets. Currently I don't think k8s uses the info, but essentially when the csi call to List/Get csi volumes is invoked the plugin/driver will response with the volume context based on the data stored in the zfs properties.

Examples for nfs and iscsi:

```
# iscsi
democratic-csi:freenas_iscsi_assets_name          arm64-pvc-f8d40101-9bf7-4f29-83e1-855a845a30cb                                                                                                                                      
democratic-csi:csi_volume_name                    pvc-f8d40101-9bf7-4f29-83e1-855a845a30cb                                                                                                                                            local
democratic-csi:freenas_iscsi_target_id            5                                                                                                                                                                                   local
democratic-csi:csi_share_volume_context           {"node_attach_driver":"iscsi","portal":"172.29.0.114:3260","portals":"","interface":"","iqn":"iqn.2005-10.org.freenas.ctl:arm64-pvc-f8d40101-9bf7-4f29-83e1-855a845a30cb","lun":0}  local
democratic-csi:freenas_iscsi_extent_id            4                                                                                                                                                                                   local
democratic-csi:managed_resource                   true                                                                                                                                                                                local
democratic-csi:freenas_iscsi_targettoextent_id    342                                                                                                                                                                                 local
democratic-csi:volume_context_provisioner_driver  freenas-iscsi                                                                                                                                                                       local
democratic-csi:provision_success                  true           

# nfs
democratic-csi:csi_volume_name                         pvc-5d1fd442-bdf4-4fc1-ab45-65b06e520de5                                                                           local
democratic-csi:volume_context_provisioner_instance_id  10770748-2542-4392-bbb4-7f0106353e36                                                                               local
democratic-csi:freenas_nfs_share_id                    2160                                                                                                               local
democratic-csi:provision_success                       true                                                                                                               local
democratic-csi:volume_context_provisioner_driver       freenas-nfs                                                                                                        local
democratic-csi:csi_share_volume_context                {"node_attach_driver":"nfs","server":"bits","share":"/mnt/tank/k8s/n/v/pvc-5d1fd442-bdf4-4fc1-ab45-65b06e520de5"}  local
democratic-csi:managed_resource                        true                                                                                                               local
```

Specifically you'll be looking the `csi_share_volume_context` value and updating that as appropriate.

I'll commit my migration work and then subsequently commit a simple script addressing this ticket as well.

**Comment by djbobyd** [comment]
Ok ,thanks
I will fix that on the freenas server. 
The offer still stands if you by chance come by to Sofia, Bulgaria

**Comment by travisghansen** [comment]
Looks nice, I'll add it to my list :D

**Comment by travisghansen** [comment]
Crude script available here: https://github.com/democratic-csi/democratic-csi/blob/master/contrib/pv-updater.sh

**Comment by djbobyd** [comment]
> Crude script available here: https://github.com/democratic-csi/democratic-csi/blob/master/contrib/pv-updater.sh

Looks great, only one remark. You don't need to restore the reclaim policy explicitly at the end. It is already available in the backup of the original PV and will also be restored together with the PV.

**Comment by travisghansen** [comment]
Oh right. I have some specific logic around that with the migration script but I’ll confirm it didn’t need to carry over and remove that. Thanks!
