### ISSUE TITLE
fresh installation

### ISSUE THREAD

**Issue by cranky-coder** [democratic-csi/democratic-csi#59]
I have just installed the provisioner into my cluster and setup it up to my freenas.  I deployed a pvc and I can see the pvc created on my free nas.  But the pvc shows as pending in my cluster.  When I do a kubectl describe on the pvc I see the following message in the logs.  

  Type     Reason                Age                   From                                                                                                                Message
  ----     ------                ----                  ----                                                                                                                -------
  Warning  ProvisioningFailed    117s (x7 over 3m32s)  org.democratic-csi.nfs_freenas-nfs-democratic-csi-controller-657b7bc85c-z82wv_09135695-e410-441e-9687-fccd5ec36e22  failed to provision volume with StorageClass "freenas-nfs-csi": rpc error: code = Internal desc = Error: Unmatched '"'.

Then it tries again and then sais waiting for someone to manually create it.  But it's been created on the freenas dataset.  Very strange.  not sure what the "Error Unmatched" means

  Normal   Provisioning          53s (x8 over 5m)      org.democratic-csi.nfs_freenas-nfs-democratic-csi-controller-657b7bc85c-z82wv_09135695-e410-441e-9687-fccd5ec36e22  External provisioner is provisioning volume for claim "default/ds-files"
  Normal   ExternalProvisioning  45s (x18 over 4m59s)  persistentvolume-controller                                                                                         waiting for a volume to be created, either by external provisioner "org.democratic-csi.nfs" or manually created by system administrator

**Comment by travisghansen** [comment]
Change the shell to bash or sh for whatever user is being used for the ssh connection. It’s some silly bug in csh that causes that error to show up.

**Comment by cranky-coder** [comment]
That was it!!! Thank you for the quick response!! Spot on!  By the time I could even get back to my k8s console to check after changing the shell it had already bound it and the pods had finished loading!  Thanks!
