### ISSUE TITLE
iscsi target not mounted but in session

### ISSUE THREAD

**Issue by gregod-com** [democratic-csi/democratic-csi#60]
Hey @travisghansen,
I got this strange behaviour that I can‘t (always) remount a previously working PVC on a node. The pvc iscsi target is shown when running iscsiadm -m session manually on the node but it is not getting mounted to /dev/sd(x). So when the democratic-csi Node daemon tries to setup the connection it fails due to /dev/sd(x) not being existent. 
When accessing the node and trying to logout of the iscsi session manually I get a iscsi internal error 9 saying it cannot log out of the target.
```bash
iscsiadm: Could not logout of [sid: 1, target: iqn.2005-10.org.freenas.ctl:csi-pvc-c9965a38-946b-4da3-b0d2-2faaaf367a01 ...
iscsiadm: initiator reported error (9 - internal error)
iscsiadm: Could not logout of all requested sessions

```
After rebooting the problem gets resolved (most of the time).
I‘m running rancherOS which does not support multipathd. (Is that of any relevance?)
It looks like there are no problems what so ever for pvcs that are connected and just running.
I was thinking of changing the OS to Centos but would like to avoid this because other than that RancherOS still does a great job acting as a k8s node.
I cannot fully confirm that this problem is limited to RancherOS but Centos and K3OS definitely ran smoother when doing fast rescheduling of Pods with attached PVCs.
Oh and k8s was spun up by rke (v1). I saw that you created an issue on the rke repo, but this seems to be something different.
Any ideas why iscsid gets confused?

This is the resulting log from Node-Daemon:
```
info: successfully logged into portal xx.xx.xx.xx:3260 and created device /dev/disk/by-path/ip-xx.xx.xx.xx:3260-iscsi-iqn.2005-10.org.freenas.ctl:csi-pvc-c9965a38-946b-4da3-b0d2-2faaaf367a01-iam-ssd-lun-0 with realpath /dev/sdb
executing fileystem command: sh -c for file in $(ls -la /dev/mapper/* | grep "\->" | grep -oP "\-> .+" | grep -oP " .+"); do echo $(F=$(echo $file | grep -oP "[a-z0-9-]+");echo $F":"$(ls "/sys/block/${F}/slaves/");); done;
executing fileystem command: realpath /dev/sdb
executing fileystem command: lsblk -a -b -l -J -O
executing fileystem command: realpath /dev/loop0
executing fileystem command: blkid -p -o export /dev/sdb
failed to execute filesystem command: blkid -p -o export /dev/sdb, response: {"code":2,"stdout":"","stderr":"blkid: error: /dev/sdb: No such device or address\n"}
executing fileystem command: mkfs.ext4 /dev/sdb
failed to execute filesystem command: mkfs.ext4 /dev/sdb, response: {"code":1,"stdout":"","stderr":"mke2fs 1.44.5 (15-Dec-2018)\nCould not open /dev/sdb: No such device or address\n"}
error: handler error - driver: FreeNASDriver method: NodeStageVolume error: {"code":1,"stdout":"","stderr":"mke2fs 1.44.5 (15-Dec-2018)\nCould not open /dev/sdb: No such device or address\n"}
{
  code: 13,
  message: '{"code":1,"stdout":"","stderr":"mke2fs 1.44.5 (15-Dec-2018)\\nCould not open /dev/sdb: No such device or address\\n"}'
}

```

**Comment by travisghansen** [comment]
I’ve seen some weirdness like this myself, but if I recall I believe it was consistent (meaning, if it didn’t work it didn’t work) and was related to being over the 64 char limit on volume path.

Next time it shows up let’s try a rescan of the session and see what happens.

**Comment by gregod-com** [comment]
So I switched out the underlying nodes to CentOS and everything seems to work properly now. I would assume that the sharing of iscsi(adm/d) control by
1) RancherOS iscsi service container
1) rke kublet
1) democratic-csi node container
+ the requirements(?) of RancherOS to install iscsid on the host anyways
just leads to a lot of confusion between the services.
Anyways.. since RancherOS is also EOL this issue can be closed.

**Comment by travisghansen** [comment]
Yeah iscsid needs to be running on the legit host. If using rke please check the link in the readme for considerations as well.

**Comment by cbpowell** [comment]
> I’ve seen some weirdness like this myself, but if I recall I believe it was consistent (meaning, if it didn’t work it didn’t work) and was related to being over the 64 char limit on volume path.

Just for future people searching for this problem, I just ran into this same issue when using Nomad and iSCSI volumes. I was getting the error at the `blkid` call:
`failed to execute filesystem command: blkid -p -o export /dev/sdg, response: {"code":2,"stdout":"","stderr":"blkid: error: /dev/sdb: No such device or address\n"}`

I assume it's because the allocation IDs are already pretty long, and then adding a longish volume name hit the character limit. Shortening the volume name solved the failure.
