### ISSUE TITLE
Error resizing a pvc

### ISSUE THREAD

**Issue by venezia** [democratic-csi/democratic-csi#61]
Unsure if I'm doing something wrong or not, but I tried resizing a PVC managed my democratic-csi (changing a volume from 10G to 20G)

The resize seems to have happened within the NAS and looking at `/proc/partitions` (this is a iSCSI mount) it is showing the increased number of blocks, but I'm getting an error from (I'm guessing) democratic-csi trying to run `resize2fs`

Relevant log entry in the democratic-csi daemonset container:
```
error: handler error - driver: FreeNASDriver method: NodeStageVolume error: {"code":1,"stdout":"Filesystem at /dev/sdj is mounted on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4e217ea2/globalmount; on-line resizing required\nold_desc_blocks = 2, new_desc_blocks = 3\n","stderr":"resize2fs 1.44.5 (15-Dec-2018)\nresize2fs: Permission denied to resize filesystem\n"}
}
executing fileystem command: resize2fs /dev/sdj
{
  code: 13,
failed to execute filesystem command: resize2fs /dev/sdj, response: {"code":1,"stdout":"Filesystem at /dev/sdj is mounted on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4e217ea2/globalmount; on-line resizing required\nold_desc_blocks = 2, new_desc_blocks = 3\n","stderr":"resize2fs 1.44.5 (15-Dec-2018)\nresize2fs: Permission denied to resize filesystem\n"}
  message: '{"code":1,"stdout":"Filesystem at /dev/sdj is mounted on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4e217ea2/globalmount; on-line resizing required\\nold_desc_blocks = 2, new_desc_blocks = 3\\n","stderr":"resize2fs 1.44.5 (15-Dec-2018)\\nresize2fs: Permission denied to resize filesystem\\n"}'
}
```

* This host is running Fedora CoreOS 33.20210217.3.0
* democratic-csi was installed via the helm chart
* version of the container is: `docker.io/democraticcsi/democratic-csi@sha256:65f11e119701dd910b923e2560e0da43dd8dd26f41d35210d5289b3b4e0c3353`

Update:
After digging through it, the reason why it wasn't resizing was that the partition felt it was in need of a e2fschk ... unmounting the partition, e2fschk-ing the partition, then deleting the pod so it could re-attempt things resolved the issue.  Unsure what caused the partition to think it was uncleanly unmounted (I waited for the pvc status to say "waiting for pod to restart" and deleted the pod.  Unsure if there is value in having the resize2fs command be prepended with a e2fschk call to fix errors, etc.

Thanks for any advice

**Comment by travisghansen** [comment]
That’s pretty strange. Online resizing is supported so you shouldn’t need to delete the pod(s) at all.

**Comment by venezia** [comment]
This is what the pvc was saying that caused me to restart the pod:

```yaml
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: freenas-iscsi-csi
    volumeMode: Filesystem
    volumeName: pvc-4e217ea2
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2021-03-08T06:20:11Z"
      message: Waiting for user to (re-)start a pod to finish file system resize of
        volume on node.
      status: "True"
      type: FileSystemResizePending
    phase: Bound
```

Which sort of matched [k8s blog entry](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/#file-system-expansion) ... should I have not acted on that status message?  I literally went into the pvc, changed the request size and nothing else.  It made sense to me that it might need a pod bounce, etc.

**Comment by travisghansen** [comment]
What k8s version are you on? I was thinking this is enabled by default but you may still need to flip the feature gates: https://kubernetes-csi.github.io/docs/volume-expansion.html

**Comment by venezia** [comment]
1.20.4 - created by kubeadm, though I think it started at 1.17 and I've been upgrading it periodically since - nothing is really explicitly enabled/disabled/exotic in the api serveer, except for oidc authentication and rbac.

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates suggests that `ExpandInUsePersistentVolumes` defaults to true since 1.15 ... so unsure what i did wrong here.  I can try creating other volumes tomorrow and see if I get a similar result.

**Comment by travisghansen** [comment]
Ok yeah let me know what you experience. It’s a 2 step operation essentially:

- resize the volume on the storage server
- rescan the device on the k8s node to reflect the new size of the disk and then expand the fs

I’m not sure how long you let it sit for all this to play out but it shouldn’t take long. Meaning, if it’s sitting in that state for more than a couple minutes something is probably off.

**Comment by venezia** [comment]
So after playing with this - I think it was a bit of impatience and bad assumptions by myself.  I created a few PVCs and if given time to do their thing, they do resize correctly.  That being said, there is a intermediate state that does exist that may be misleading:

I took a PVC and incrementally expanded it...
You can get to a state where you see this:
```
Conditions:
  Type                      Status  LastProbeTime                     LastTransitionTime                Reason  Message
  ----                      ------  -----------------                 ------------------                ------  -------
  FileSystemResizePending   True    Mon, 01 Jan 0001 00:00:00 +0000   Mon, 08 Mar 2021 17:14:43 -0500           Waiting for user to (re-)start a pod to finish file system resize of volume on node.
Events:
  Type     Reason                      Age                    From                                                                                                                  Message
  ----     ------                      ----                   ----                                                                                                                  -------
  Normal   ExternalProvisioning        2m45s                  persistentvolume-controller                                                                                           waiting for a volume to be created, either by external provisioner "org.democratic-csi.iscsi" or manually created by system administrator
  Normal   Provisioning                2m33s (x2 over 2m45s)  org.democratic-csi.iscsi_truenas-csi-democratic-csi-controller-6c8cdf55d6-vz9jp_f0420757-8fb6-48c8-9b08-79b050b134e9  External provisioner is provisioning volume for claim "default/my-request-for-storage"
  Normal   ProvisioningSucceeded       2m31s (x2 over 2m33s)  org.democratic-csi.iscsi_truenas-csi-democratic-csi-controller-6c8cdf55d6-vz9jp_f0420757-8fb6-48c8-9b08-79b050b134e9  Successfully provisioned volume pvc-9f4e4f03
  Normal   FileSystemResizeSuccessful  61s                    kubelet                                                                                                               MountVolume.NodeExpandVolume succeeded for volume "pvc-9f4e4f03"
  Normal   Resizing                    32s (x2 over 77s)      external-resizer org.democratic-csi.iscsi                                                                             External resizer is resizing volume pvc-9f4e4f03
  Warning  ExternalExpanding           32s (x2 over 77s)      volume_expand                                                                                                         Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   FileSystemResizeRequired    31s (x2 over 76s)      external-resizer org.democratic-csi.iscsi                                                                             Require file system resize of volume on node
```

The status would make someone (or at least me) think "Oh, we're in a state where I need to restart the pod" because of `FileSystemResizePending` condition and the message that is paired with that.  But if you just let it sit for a bit longer it will resolve itself...

```
Events:
  Type     Reason                      Age                    From                                                                                                                  Message
  ----     ------                      ----                   ----                                                                                                                  -------
  Normal   ExternalProvisioning        3m7s                   persistentvolume-controller                                                                                           waiting for a volume to be created, either by external provisioner "org.democratic-csi.iscsi" or manually created by system administrator
  Normal   Provisioning                2m55s (x2 over 3m7s)   org.democratic-csi.iscsi_truenas-csi-democratic-csi-controller-6c8cdf55d6-vz9jp_f0420757-8fb6-48c8-9b08-79b050b134e9  External provisioner is provisioning volume for claim "default/my-request-for-storage"
  Normal   ProvisioningSucceeded       2m53s (x2 over 2m55s)  org.democratic-csi.iscsi_truenas-csi-democratic-csi-controller-6c8cdf55d6-vz9jp_f0420757-8fb6-48c8-9b08-79b050b134e9  Successfully provisioned volume pvc-9f4e4f03
  Normal   Resizing                    54s (x2 over 99s)      external-resizer org.democratic-csi.iscsi                                                                             External resizer is resizing volume pvc-9f4e4f03
  Warning  ExternalExpanding           54s (x2 over 99s)      volume_expand                                                                                                         Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   FileSystemResizeRequired    53s (x2 over 98s)      external-resizer org.democratic-csi.iscsi                                                                             Require file system resize of volume on node
  Normal   FileSystemResizeSuccessful  15s (x2 over 83s)      kubelet                                                                                                               MountVolume.NodeExpandVolume succeeded for volume "pvc-9f4e4f03"
```

I think this status and message is handled by CSI-proper and not democratic-csi, so I'm unsure who to complain to, but I think that people like me might be hovering over the PVC, see this condition and think "clearly I need to bounce the pod" and run into my problem ... unsure who to complain to to possibly give a better message to the user, but I would like other people to not end up in the weird situation I did.

Feel free to close the ticket, but if there is value to think about rewording that condition message, perhaps an issue (in whatever repo) should be created?

**Comment by travisghansen** [comment]
Ah! Indeed that is handled by 'K8S' generally and the driver is not involved. I will leave this open and see if I can get someone in k8s storage group to take a look and see what they think.
