### ISSUE TITLE
[Question] Supported AccessModes?

### ISSUE THREAD

**Issue by monkey-b** [democratic-csi/democratic-csi#62]
Hi,
I can't find the information in the docs. What are the supported accessmodes for the different drivers (nfs/iscsi)? 

Is it possible to have a support matrix for accessmodes? I am especially interested about the readwritemany support.

Thank you

**Comment by travisghansen** [comment]
`csi` doesn't map exactly to k8s constructs, but this should be apparent enough:

```
# nfs/cifs

              "UNKNOWN",
              "SINGLE_NODE_WRITER",
              "SINGLE_NODE_READER_ONLY",
              "MULTI_NODE_READER_ONLY",
              "MULTI_NODE_SINGLE_WRITER",
              "MULTI_NODE_MULTI_WRITER",
```

```
# block/iscsi

              "UNKNOWN",
              "SINGLE_NODE_WRITER",
              "SINGLE_NODE_READER_ONLY",
              "MULTI_NODE_READER_ONLY",
              "MULTI_NODE_SINGLE_WRITER",
```

`nfs` does support rwx. Note that the relevant values are effectively determined by the underlying limitations of the various protocols.  In general file-based shares (nfs/cifs/etc) will support rwx while block-based shares (iscsi, fiber channel, etc) will be rwo.

**Comment by monkey-b** [comment]
Thanks for the confirmation. I thought so but wasn't sure.
I'll close the issue.
Keep on the good work!
