### ISSUE TITLE
SMB Permission Denied

### ISSUE THREAD

**Issue by kbmanseau** [democratic-csi/democratic-csi#67]
I have setup the freenas-smb driver and I can see the pvc volumes being created in truenas, they get bound in k8s too but the pod is unable to mount them?

Output of kubectl describe pod:
`MountVolume.MountDevice failed for volume "pvc-e465b419-30fe-4b91-a034-00c7915f9b7d" : rpc error: code = Internal desc = {"code":32,"stdout":"","stderr":"mount error(13): Permission denied\nRefer to the mount.cifs(8) manual page (e.g. man mount.cifs)\n"}`

Output of csi-driver container logs from the node pod:
`executing mount command: mount -t cifs -o username=root,password=password!,defaults //192.168.10.127/SMB/volumes/pvc-1a6a6441-ca7b-482c-8038-e8a93797b9b6 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1a6a6441-ca7b-482c-8038-e8a93797b9b6/globalmount
{"service":"democratic-csi","level":"error","message":"handler error - driver: FreeNASDriver method: NodeStageVolume error: {\"code\":32,\"stdout\":\"\",\"stderr\":\"mount error(13): Permission denied\\nRefer to the mount.cifs(8) manual page (e.g. man mount.cifs)\\n\"}"}
{
  code: 13,
  message: '{"code":32,"stdout":"","stderr":"mount error(13): Permission denied\\nRefer to the mount.cifs(8) manual page (e.g. man mount.cifs)\\n"}'
}`

I cannot figure out what is causing the permission denied. I am able to mount //192.168.10.127/SMB/volumes/pvc-1a6a6441-ca7b-482c-8038-e8a93797b9b6 on my mac

**Comment by travisghansen** [comment]
Hmm that’s strange. See anything in your logs server side?

Maybe try running the mount command directly on a node and try adding the sec=<foo> options or something of that nature.

https://unix.stackexchange.com/questions/124342/mount-error-13-permission-denied

**Comment by kbmanseau** [comment]
Thank you for your reply. The issue ended up being permissions on the Truenas side. I have no idea why but the root user was unable to be used for the mount options section of the config. My current config uses a custom user for that section and root user for ssh and http connections.

Thank you, I will close this as the issue is not with the tool

**Comment by travisghansen** [comment]
Ok cool. The project does support invoking setacl commands if necessary as an FYI but I’m no expert with smb shares generally. Any particular reason you’re doing smb vs nfs?

**Comment by kbmanseau** [comment]
I have a large pool in truenas made of HDDs. When I was originally performance testing SMB was able to meet my performance needs so I didn't look into nfs, I could be mistaken but I didn't think my setup would be good for the synchronous writes with nfs

**Comment by travisghansen** [comment]
Sounds good! Thanks for sharing.

You’re probably already aware but there are various options both at the nfs mount level and the zfs level that could be tweaked per the needs, but it sounds like you’ve done your research and know what’s best! That’s why it’s there is to get used so I hope you find it useful :)
