### ISSUE TITLE
Daemonset Stuck on creating

### ISSUE THREAD

**Issue by Tony-The-Developer** [democratic-csi/democratic-csi#68]
![image](https://user-images.githubusercontent.com/68414482/112677523-1610ca80-8e27-11eb-8cf8-f19ce206cbf6.png)

**Comment by Tony-The-Developer** [comment]
![image](https://user-images.githubusercontent.com/68414482/112677573-2759d700-8e27-11eb-8fa2-576cca7256e0.png)

Deployment works and datasets are being created. But cant store data.

**Comment by Tony-The-Developer** [comment]
getting this error. Im using k3s 

(combined from similar events): MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/snap/microk8s/common/var/lib/kubelet/plugins_registry is not a directory
--

MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/snap/microk8s/common/var/lib/kubelet/plugins_registry is not a directory
--

**Comment by travisghansen** [comment]
Welcome! If using k8s why the custom microk8s path for kubelet?

**Comment by Tony-The-Developer** [comment]
Thanks for the reply. I Used the article. How can I update the helm install? And what URL should I use? I am using k3s with rancher.

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L191

**Comment by travisghansen** [comment]
If setting the value correctly in your `values.yaml` doesn't clear up the issue I'll need you to cleanse your values and send them over to review.

**Comment by Tony-The-Developer** [comment]
ok, so should I rerun the update command but this time with the new path.

**Comment by travisghansen** [comment]
Yes please do.

**Comment by Tony-The-Developer** [comment]
All containers started up now. Let me try to startup a pod and make sure that it can read and write data.

**Comment by travisghansen** [comment]
How did the testing go?
