### ISSUE TITLE
Unable to get this working.

### ISSUE THREAD

**Issue by MarkLFT** [democratic-csi/democratic-csi#73]
I have followed the excellent article https://jonathangazeley.com/2021/01/05/using-truenas-to-provide-persistent-storage-for-kubernetes/ to set this up.  For testing purposes I used both the iscsi and nfs implementations.
All of the issue seems to related to permissions of some sort.
In both cases;
- I use an APIKey, and that seems to be fine.
- For the SSH, if I use the root account, all the pods start, but when I try to bind a PVC I receive the error "Error: Sorry, user root is not allowed to execute '/usr/local/sbin/zfs create -p ...... as root on nas.domain.name"
- For SSH if I use an account I created, then the pods do not start correctly. The democratic-csi-controller remains in a CrashLoopBackOff status.

I have spent several days, trying to change permissons on the Datasets, no difference.  I have set the option for root to login with password, no difference. 

Honestly, I would prefer to get it going not using root.  But cannot see how.  Maybe I have missed a step?

When I describe the failing pod, I get 

`Name:         zfs-nfs-democratic-csi-controller-f7f74948d-thcbl
Namespace:    csi
Priority:     0
Node:         k8snode1/192.168.1.32
Start Time:   Sun, 18 Apr 2021 04:05:58 +0000
Labels:       app.kubernetes.io/csi-role=controller
              app.kubernetes.io/instance=zfs-nfs
              app.kubernetes.io/name=democratic-csi
              pod-template-hash=f7f74948d
Annotations:  checksum/secret: 8d169505d98469a310c7df1023ef59e5b929723bc6735958c045d9a06ce0dc64
              cni.projectcalico.org/podIP: 172.16.249.27/32
              cni.projectcalico.org/podIPs: 172.16.249.27/32
Status:       Running
IP:           172.16.249.27
IPs:
  IP:           172.16.249.27
Controlled By:  ReplicaSet/zfs-nfs-democratic-csi-controller-f7f74948d
Containers:
  external-provisioner:
    Container ID:  docker://1e461dc1ed22c35e800e70f15a5a04aa1bc1f00bfd5bc593da5a4fa8adf28db6
    Image:         k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
    Image ID:      docker-pullable://k8s.gcr.io/sig-storage/csi-provisioner@sha256:20c828075d1e36f679d6a91e905b0927141eef5e15be0c9a1ca4a6a0ed9313d2
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --leader-election
      --leader-election-namespace=csi
      --timeout=90s
      --worker-threads=10
      --extra-create-metadata
      --csi-address=/csi-data/csi.sock
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 18 Apr 2021 04:07:03 +0000
      Finished:     Sun, 18 Apr 2021 04:07:03 +0000
    Ready:          False
    Restart Count:  3
    Environment:    <none>
    Mounts:
      /csi-data from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from zfs-nfs-democratic-csi-controller-sa-token-97h7r (ro)
  external-resizer:
    Container ID:  docker://3c36309683781bacb7fba23e9f8a936aacd7eb897d637e1cf95b67df3346f98b
    Image:         k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
    Image ID:      docker-pullable://k8s.gcr.io/sig-storage/csi-resizer@sha256:7a5ba58a44e0d749e0767e4e37315bcf6a61f33ce3185c1991848af4db0fb70a
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --leader-election
      --leader-election-namespace=csi
      --timeout=90s
      --workers=10
      --csi-address=/csi-data/csi.sock
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Sun, 18 Apr 2021 04:07:04 +0000
      Finished:     Sun, 18 Apr 2021 04:07:04 +0000
    Ready:          False
    Restart Count:  3
    Environment:    <none>
    Mounts:
      /csi-data from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from zfs-nfs-democratic-csi-controller-sa-token-97h7r (ro)
  external-snapshotter:
    Container ID:  docker://a050c8a089af88f52b7bd4561c1165e6caff5f67125bc1a0bf437117e0945595
    Image:         k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
    Image ID:      docker-pullable://k8s.gcr.io/sig-storage/csi-snapshotter@sha256:9af9bf28430b00a0cedeb2ec29acadce45e6afcecd8bdf31c793c624cfa75fa7
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --leader-election
      --leader-election-namespace=csi
      --timeout=90s
      --worker-threads=10
      --csi-address=/csi-data/csi.sock
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 18 Apr 2021 04:07:05 +0000
      Finished:     Sun, 18 Apr 2021 04:07:05 +0000
    Ready:          False
    Restart Count:  3
    Environment:    <none>
    Mounts:
      /csi-data from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from zfs-nfs-democratic-csi-controller-sa-token-97h7r (ro)
  csi-driver:
    Container ID:  docker://3ccfe3315a9bdf5dc060b5015a44aa100e6c43770802d5f57331acc5fec2fe98
    Image:         democraticcsi/democratic-csi:latest
    Image ID:      docker-pullable://democraticcsi/democratic-csi@sha256:8cd5f03aa2a8344a8652e6fbb8f626780013e8f2e45b015c20914a3788f2ac06
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-version=1.2.0
      --csi-name=org.democratic-csi.nfs
      --driver-config-file=/config/driver-config-file.yaml
      --log-level=info
      --csi-mode=controller
      --server-socket=/csi-data/csi.sock
    State:          Running
      Started:      Sun, 18 Apr 2021 04:06:07 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       exec [bin/liveness-probe --csi-version=1.2.0 --csi-address=/csi-data/csi.sock] delay=10s timeout=3s period=60s #success=1 #failure=5
    Environment:    <none>
    Mounts:
      /config from config (rw)
      /csi-data from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from zfs-nfs-democratic-csi-controller-sa-token-97h7r (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  socket-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  zfs-nfs-democratic-csi-driver-config
    Optional:    false
  zfs-nfs-democratic-csi-controller-sa-token-97h7r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  zfs-nfs-democratic-csi-controller-sa-token-97h7r
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  68s                default-scheduler  Successfully assigned csi/zfs-nfs-democratic-csi-controller-f7f74948d-thcbl to k8snode1
  Normal   Pulling    61s                kubelet            Pulling image "democraticcsi/democratic-csi:latest"
  Normal   Pulled     61s                kubelet            Successfully pulled image "democraticcsi/democratic-csi:latest" in 574.289416ms
  Normal   Created    60s                kubelet            Created container csi-driver
  Normal   Started    60s                kubelet            Started container csi-driver
  Normal   Pulled     57s (x2 over 66s)  kubelet            Container image "k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0" already present on machine
  Normal   Created    57s (x2 over 64s)  kubelet            Created container external-provisioner
  Normal   Started    56s (x2 over 63s)  kubelet            Started container external-resizer
  Normal   Pulled     56s (x2 over 63s)  kubelet            Container image "k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3" already present on machine
  Normal   Started    56s (x2 over 64s)  kubelet            Started container external-provisioner
  Normal   Pulled     56s (x2 over 64s)  kubelet            Container image "k8s.gcr.io/sig-storage/csi-resizer:v1.1.0" already present on machine
  Normal   Created    56s (x2 over 63s)  kubelet            Created container external-resizer
  Normal   Created    55s (x2 over 62s)  kubelet            Created container external-snapshotter
  Normal   Started    55s (x2 over 61s)  kubelet            Started container external-snapshotter
  Warning  BackOff    54s                kubelet            Back-off restarting failed container
  Warning  BackOff    54s                kubelet            Back-off restarting failed container
  Warning  BackOff    54s                kubelet            Back-off restarting failed container
`
Any help anyone can offer will be greatly appreciated.

**Comment by travisghansen** [comment]
@MarkLFT welcome to the project! I’m sure we can get you going. Let’s start with the following:

- send logs from whatever container is failing to start
- Send your helm values files (cleanse them first of secrets)
- Tell me what version of truenas you’re running 

That should be a pretty good start. If you’re running the very latest truenas (12.0-u3) then using a non-root user should be just fine. It’s fine in older versions as well but the sudoers file can get overwritten by various situations. The latest version has added a field to do that in a supported way.

**Comment by MarkLFT** [comment]
Many thanks for the response.  To avoid confusion, mainly on my part, I will focus just on one scenario, this is using nfs and a non-root account.

In this scenario the controller pod fails to start.  I have attached the logs. But the common theme seems to be All configured authentication methods failed.

I have attached my yaml file with passwords and keys removed.

TrueNAS is version 12.0-u3, but not really clear what I need to do to my account to make it usable in this instance.   My account is called k8s. 

Hope fully this is enough for you to give me some advise.

Many thanks

[freenas-nfs-clean-yaml.txt](https://github.com/democratic-csi/democratic-csi/files/6335064/freenas-nfs-clean-yaml.txt)
[csidriver.txt](https://github.com/democratic-csi/democratic-csi/files/6335037/csidriver.txt)
[extprov.txt](https://github.com/democratic-csi/democratic-csi/files/6335039/extprov.txt)
[extresizer.txt](https://github.com/democratic-csi/democratic-csi/files/6335040/extresizer.txt)
[extsnap.txt](https://github.com/democratic-csi/democratic-csi/files/6335041/extsnap.txt)

**Comment by travisghansen** [comment]
Ok, we have 2 things to deal with here (I’m guessing).

1. basic ssh connection works
2. non-root configuration

Currently you are even passing 1 so let’s focus on that and then we’ll move to 2.

The response seems to indicate the ssh server is running and that it is attempting to connect. Can you send over what the settings are for the user account from truenas (a screenshot)? I’m guessing the key or the password is off. Also maybe send a screenshot of the ssh server configuration on truenas as well.

**Comment by MarkLFT** [comment]
Please find request snapshots attached.

**Comment by travisghansen** [comment]
OK, are you using password or ssh key for the user account? You will need to select the 'permit sudo' checkbox for that aspect by the way.

If you're using password, you could be getting hit by a yaml escaping issue. There was another issue created here where that showed up but I'm not finding atm..

**Comment by MarkLFT** [comment]
I will test the Permit sudo option shortly. With regards to the password we already quote it.

**Comment by travisghansen** [comment]
Permit likely won't do anything until you're past the issue at hand anyway. Are you seeing anything in the sshd logs on the nas that show what the failure is?

**Comment by MarkLFT** [comment]
ok, we have a little progress.  Again, just focusing on NFS.

For the SSH login, I solved that.  It was password related.  I use a program Dashlane to create and save passwords, but it seems it saved the wrong password.

Once I corrected the password, the pod started.  However I was unable to create a PVC, with an error message that the home directory does not exist.

I tried to set the home directory to the top level Dataset, but TrueNAS wouldn't let me, so I needed to create an extra layer so the path now is k8s/csi/nfs, and I have been able to change the home directory to k8s/csi/.

Then the error message on creating the PVC changed to 'cannot create k8s/csi/nfs/vols' permission denied.

So I made my account the owner of k8s/csi, and k8s/csi/nfs.  But I still get the permissions denied error.

I have enabled this account to permit sudo, but that does not seem to make any difference either. 

Any thoughts what I am doing wrong?

**Comment by travisghansen** [comment]
Ah, the home directory is the home directory of your `k8s` user. I would simply create `/home/k8s` or `/mnt/tank/home/k8s` and set the home directory on your user to that (it does not need to be a dedicated dataset).

Is `k8s` the name of the pool? If not you'll want to add pool name in front of that for the datasetParent values. 

Details about setting up sudo can be found here: https://github.com/democratic-csi/democratic-csi/issues/34#issuecomment-822861979

You'll want to uncomment these lines in your values.yaml (and of course redeploy):

```
#      cli:
#        sudoEnabled: true
```

Some other notes about the config:

- Are you certain you want nfsv4? I recommend nfsv3 unless you have a very specific reason to use v4.
- I would recommend setting an `instance_id`. Just generate a guid and stick it in there (and never change it). Do this per helm release.

Looks like you're really close!

**Comment by MarkLFT** [comment]
Thanks, will try this now.

**Comment by MarkLFT** [comment]
ok, done all of those and the nfs version works.  Many thanks.
As this is working, is there any particular reason to have both nfs and iscsi in a real world scenario?  If not, I will cut my losses and stick with nfs.

**Comment by travisghansen** [comment]
Great! You’ll absolutely want iscsi if you’re running production workloads that are database type workloads. This is very app specific but nfs does not do great with mysql/postgres and others. nfs is great for many workloads however.

**Comment by travisghansen** [comment]
I guess I should mention, nfs is required for rwx workloads which you cannot do with iscsi. But as mentioned, for many workloads the performance of iscsi is far superior.

**Comment by MarkLFT** [comment]
OK, thanks.  Will start again now with iscsi then. ;-)

based on what I already learned, let me see if I can get it going.

**Comment by MarkLFT** [comment]
Using what I learned previously, iscsi now works.  That is great, many thanks for your help.

Now to test them with some pods.

**Comment by travisghansen** [comment]
We’ll leave this open until you’re 100% going.

**Comment by MarkLFT** [comment]
Seems keeping it open was a good plan. ;-)

I am trying to use an iscsi pvc, but it lways fails to mount.  The pod description is recording

`Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    7m27s                default-scheduler  Successfully assigned default/test to k8snode0
  Warning  FailedMount  3m7s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[kube-api-access-xpvpm data]: timed out waiting for the condition
  Warning  FailedMount  85s (x3 over 5m27s)  kubelet            MountVolume.MountDevice failed for volume "pvc-d8768425-8dd2-4221-b5f2-f830a5266985" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount  50s (x2 over 5m24s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data kube-api-access-xpvpm]: timed out waiting for the condition
` 

I have tried this with two seperate pods, and bot give the same result.

I checked in the NAS, and the volume has been correctly created, as have the targets, extents and associated targets. 

Any advice on where I went wrong this time?  

Many thanks for your help.

**Comment by travisghansen** [comment]
Can you pull the logs from the node pod (the daemonset for the iscsi driver) on the node the pod was scheduled on?

What did you do for node prep as it relates to iscsi?

**Comment by MarkLFT** [comment]
I am having a ball here.  I found there is an issue with the multipath caused by VMWare.  I had to shutdown all nodes and make an advanced setting for disk.EnableUUID = TRUE, without this the multipath service failed to start properly.  But that still did not fix the problem.

With regards to the nodes, I prepared all of these on all nodes, master and worker.
sudo apt-get install -y nfs-common

# Install the following system packages
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools

# Enable multipathing
sudo tee /etc/multipath.conf <<-'EOF'
defaults {
    user_friendly_names yes
    find_multipaths yes
}
EOF

sudo systemctl enable multipath-tools.service
sudo service multipath-tools restart

# Ensure that open-iscsi and multipath-tools are enabled and running
sudo systemctl status multipath-tools
sudo systemctl enable open-iscsi.service
sudo service open-iscsi start
sudo systemctl status open-iscsi

Is there anything I missed?

With regards to the logs from the node pod, I am having a problem with that as kubectl does not run on the worker nodes. I get a The connection to the server localhost:8080 was refused - did you specify the right host or port? error.  Once I find how to get the logs I will let you know.

Thanks

**Comment by travisghansen** [comment]
You don’t need to run kubectl from the worker node, just use it like you normally would but get the logs from the specific pod on the relevant node.

**Comment by MarkLFT** [comment]
Driver logs attached, I hope this is the correct one.

[driverlog.txt](https://github.com/democratic-csi/democratic-csi/files/6355121/driverlog.txt)

**Comment by travisghansen** [comment]
Indeed. Now you'll need to scour the `/var/log/messages` on the TrueNAS box and see if you can figure out why it's rejecting the connections I guess.

**Comment by MarkLFT** [comment]
I have checked the messages file as suggested, the results seem to indicate the luns assigned to the target and pg1 not assigned to the target.

no LUNs defined for target iqn.2005.........
portal-group "pg1" not assigned to any target

But if I use the TrueNAS GUI, The ISCSI targets, extents,, associated targets etc. all look as I would expect.

I have searched the internet for these messages, and they occur quite often, but none give a definitive solution, or even a clue of where to look.

I feel I am so close to getting this working, but am getting so frustrated by it also. 

I did notice you had this message while ago, which seemed to be related to a corrupted conf file in turn caused by creating too many pvc's at one time.  But I have no other PVC's or links to this ISCSI server.  And I have checked the formatting of the conf file, and again, it looks pretty ok.

Just as a test, I tried to connect to the dynamically created volume from a Windows system.  I am much more familiar with iscsi using the Windows iSCSI Server and Initiator, and I could connect and mount the drive with no error at all.  

Any ideas?

**Comment by travisghansen** [comment]
Yeah I think you’re super close as well.

Can you send over the cleansed values file for iscsi and screenshots of the various iscsi screens in TrueNAS?

Can you send the exact log messages from the server?

Is it possible the pg is doing ip based blocking?

**Comment by MarkLFT** [comment]
Please find below, the values file, and attached all the screenshots from the NAS.  I have included all iSCSI screens, and the pool screen.

With regards to IP blocking, there is no blocking setup.

A screenshot of the messages file is attached also.

Many thanks

`csiDriver:
  name: "org.democratic-csi.iscsi"

storageClasses:
- name: freenas-iscsi-csi
  defaultClass: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

volumeSnapshotClasses: []

driver:
  config:
    driver: freenas-iscsi
    instance_id: 8a991eaf-6465-4e0c-aa30-204ef5e8ea50
    httpConnection:
      protocol: http
      host: 192.168.1.10
      port: 80
      apiKey: keygoeshere
      allowInsecure: true
      apiVersion: 2
    sshConnection:
      host: 192.168.1.10
      port: 22
      username: k8s
      password: "password"
    zfs:
      cli:
        sudoEnabled: true
      datasetParentName: k8s/csi/iscsi/v
      detachedSnapshotsDatasetParentName: k8s/csi/iscsi/s
      zvolCompression:
      zvolDedup:
      zvolEnableReservation: false
      zvolBlocksize:
    iscsi:
      targetPortal: "192.168.1.10:3261"
      targetPortals: []
      interface:

      namePrefix: csi-
      nameSuffix: "-clustera"
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
          targetGroupAuthGroup:

      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 4096
      extentRpm: "7200"
      extentAvailThreshold: 0
`

![iscsi7](https://user-images.githubusercontent.com/5136699/115944063-41e6a500-a4e6-11eb-8d92-4db824a50ec4.PNG)
![iscsi8](https://user-images.githubusercontent.com/5136699/115944066-4317d200-a4e6-11eb-8488-79c42fe0f748.PNG)
![iscsi9](https://user-images.githubusercontent.com/5136699/115944067-43b06880-a4e6-11eb-9ec1-4b9ede616e7a.PNG)
![iscsi10](https://user-images.githubusercontent.com/5136699/115944069-4448ff00-a4e6-11eb-81dc-e40635c3736a.PNG)
![iscsi11](https://user-images.githubusercontent.com/5136699/115944070-4448ff00-a4e6-11eb-8208-14b108a7d13c.PNG)
![log1](https://user-images.githubusercontent.com/5136699/115944072-44e19580-a4e6-11eb-8226-588da59841e1.PNG)
![pool1](https://user-images.githubusercontent.com/5136699/115944073-457a2c00-a4e6-11eb-8ee2-13c41edb52ad.PNG)
![pool2](https://user-images.githubusercontent.com/5136699/115944074-457a2c00-a4e6-11eb-94b9-99d4b3f6e31d.PNG)
![iscsi1](https://user-images.githubusercontent.com/5136699/115944075-4612c280-a4e6-11eb-93dd-87e272615b79.PNG)
![iscsi2](https://user-images.githubusercontent.com/5136699/115944076-46ab5900-a4e6-11eb-9054-dc9cc89d04a4.PNG)
![iscsi3](https://user-images.githubusercontent.com/5136699/115944077-4743ef80-a4e6-11eb-82e2-6c3030bbd25d.PNG)
![iscsi4](https://user-images.githubusercontent.com/5136699/115944078-4743ef80-a4e6-11eb-9d0c-4780286a19a8.PNG)
![iscsi5](https://user-images.githubusercontent.com/5136699/115944079-47dc8600-a4e6-11eb-805d-086678ab6a6d.PNG)
![iscsi6](https://user-images.githubusercontent.com/5136699/115944080-48751c80-a4e6-11eb-8afe-99ad3c60fa13.PNG)

**Comment by travisghansen** [comment]
You put the wrong port in the yaml :) it should be `3260` instead of `3261`. Easiest thing to do is erase the pv/pvc, redeploy with updated yaml and then run the test with a new pv/pvc.

**Comment by MarkLFT** [comment]
Really, something so simple.  I have been going through everything checking all the GUID names, account names, passwords  etc.  but missed the port number.  I am really sorry for wasting your time.
