### ISSUE TITLE
FreeNAS-iscsi provisioner successfuly provisions storage, but pod cannot write to it

### ISSUE THREAD

**Issue by frobobbo** [democratic-csi/democratic-csi#78]
I have gone through all the documentation I can find on this, and verified my configuration so many times.  I have successfully deployed the FreeNAS-NFS provisioner and have been able to deploy workloads using it.

However, with FreeNAS-iSCSI provisioner, everything works right until the point the container starts, and the container spits out:
[Trace] DiskProviderBase: Directory '/config' isn't writable.

I am able to write to the provisioned iSCSI disk on the node, but have confirmed that if I kubectl exec into the pod, I can not write to the storage.

Anyone else seeing similar issues?

**Comment by travisghansen** [comment]
Welcome to the project! I’ve not heard of this before but this sounds like the container is running as non root and doesn’t have the proper setting to make if fly. Would you mind sending over the pod definition for me to review?

**Comment by frobobbo** [comment]
Thanks for you prompt reply - you were exactly right, the Image I was deploying did not run as root by default, and therefore did not have permissions to the Mounted Drive.
I need to specify the podSecurityContext, and all is good.
Thanks for putting together such an amazing project !

**Comment by travisghansen** [comment]
Awesome! Glad it’s working out well.
