### ISSUE TITLE
Using a non-root user fails with "permission denied"

### ISSUE THREAD

**Issue by larsks** [democratic-csi/democratic-csi#79]
I'm using the democratic-csi driver with OpenShift on one side and TrueNAS 12 on the other. I've configured democratic-csi to connect with a non-root user:

```
sshConnection:
  host: 10.253.0.10
  port: 22
  privateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----
  username: csi
```

The driver is able to successfully connect to the TrueNAS server:

```
May  6 05:25:59 truenas 1 2021-05-06T05:25:59.051679-07:00
truenas.local sshd 27884 - - Accepted publickey for csi from
10.253.0.100 port 43858 ssh2: RSA
SHA256:Ne6nAkT7H1W0LHw2fdqwLb4+ZJFajHZhS411GiF2Q3g
```

The user has wide-open `sudo` privileges:

```
csi ALL=(ALL) NOPASSWD: ALL
```

And I've verified that works:

```
csi@truenas:~ $ id
uid=1001(csi) gid=1001(csi) groups=1001(csi)
csi@truenas:~ $ sudo mkdir /mnt/pool0/vols/demo/testdirectory
```

But democratic-csi fails to create volumes:

```
failed to provision volume with StorageClass "nfs-csi": rpc error:
code = Internal desc = Error: cannot create
'pool0/vols/demo/pvc-8127647a-5a9d-4f60-b9ec-0fd12be089f0': permission
denied 
```

This all works just fine if I configure the driver to connect as
`root` instead.

Is the above configuration expected to work?

**Comment by travisghansen** [comment]
In your driver config add the following..

```
zfs:
  # can be used to override defaults if necessary
  # the example below is useful for TrueNAS 12
  cli:
    sudoEnabled: true
```

- https://github.com/democratic-csi/democratic-csi/blob/master/examples/freenas-iscsi.yaml#L31

**Comment by larsks** [comment]
Is that worth an update to the README (e.g., https://github.com/democratic-csi/democratic-csi#freenas-freenas-nfs-freenas-iscsi-freenas-smb)?

**Comment by travisghansen** [comment]
Yep! Didn't realize I missed that. I'll leave this open until that has been documented along with the proper commands to persist `NOPASSWD` in the latest versions of TrueNAS.
