### ISSUE TITLE
Cleanup of orphaned datasets

### ISSUE THREAD

**Issue by linedpaper** [democratic-csi/democratic-csi#81]
Is there a way to quickly/easily find and cleanup orphaned PVCs?  I had an issue recently and had to restore from backup, however in my TrueNas gui it appears that all of the old PVC were not actually deleted.  Finding/running through the gui to manually delete is quite cumbersome.  Is there another way to see which are not currently in use and purge them?

**Comment by travisghansen** [comment]
Welcome! Yes this is possible but would require a fair amount of custom code. A script could probably be added to the project to help however.

The basic idea is to use a grpc client to utilize the `ListVolumes` method of the csi controller service. After you have that response kubectl (or any k8s client) could check for existence of the `PV` in the api, if not present invoke the `DeleteVolume` method of the csi controller service which would delete the volume along with all other assets associated with it.

The easiest way to approach this would likely be to create a little script right into the project that could be invoked after exec’ing into the controller pod.

**Comment by ahgraber** [comment]
I threw together the below cleanup process to reclaim space.  The process is brute force and hacky, but it did appear to work without removing datasets in use.  This is very _not_ production-ready as It involves a manual copy/paste to copy the current PV name array from my local admin machine with kubectl and the kubeconfig file and paste into the TrueNas GUI shell or ssh session.  
Hopefully this is helpful in the short term (or, if not, maybe I'll learn something if I get called out for my hack job)

1. run on administrator machine with kubectl installed and kubeconfig

```sh
# get current PV names from cluster
PVs=($(kubectl get pv -A | awk '{print $1}' | grep "pvc"))
echo ${PVs[*]}
```

2. Copy/paste `PVs` array in Truenas shell

```sh
PVs=(<PASTE LIST HERE>)
```

3. Run the following code to compare the currently-used PVs to the list of datasets from TrueNas.  You'll want to update the `PREFIX` paths for ISCSi and NFS per the path specified in your `democratic-csi` config 

```sh
###   ISCSI   ###
PREFIX="ssdpool/csi/ixi/v/"
# get list of current iscsi zvols
ISCSIs=($(zfs list | grep "${PREFIX}" | awk '{print $1}' | sed "s|${PREFIX}||"))

# get differences
OLD=($(echo ${ISCSIs[@]} ${PVs[@]} | tr ' ' '\n' | sort | uniq -u))

for dat in ${OLD[@]}; do
  echo "Removing ${PREFIX}${dat}"
  zfs destroy -rf "${PREFIX}${dat}"
done


###   NFS   ###
PREFIX="ssdpool/csi/nfs/v/"
# get list of current nfs zvols
NFSs=($(zfs list | grep "${PREFIX}" | awk '{print $1}' | sed "s|${PREFIX}||"))

# get differences
OLD=($(echo ${NFSs[@]} ${PVs[@]} | tr ' ' '\n' | sort | uniq -u))

for dat in ${OLD[@]}; do
  echo "Removing ${PREFIX}${dat}"
  zfs destroy -rf "${PREFIX}${dat}"
done
```

**Comment by travisghansen** [comment]
This is available now in the most recent builds.

https://github.com/democratic-csi/democratic-csi/blob/master/bin/k8s-csi-cleaner

Essentially deploy an image with the tool, exec into the appropriate controller pod, and execute the script. See the comments at the top of the script regarding ENV vars etc.
