### ISSUE TITLE
help: what is the correct way to setup without breaking on FreeNas Upgrades

### ISSUE THREAD

**Issue by alexanderniebuhr** [democratic-csi/democratic-csi#82]
hey there.
Thanks for this amazing csi.

I have setup it with an 3 Node Kubernetes and 1 FreeNas Core box.
However if I need to update my FreeNas Core box, all Pods crash (which is expected since the storage is going away), but if the FreeNas Box is restarted, the pods do not recover..

So should I use NFS over ISCSI. What is the correct way to config this, so the pods get back the storage once it is available again. Restarting all Pods manually is not good.

If there is a way to have 2 FreeNas boxes, and then migrate over one, if the other one is updating.. I am more than happy to get this setup explained too.

**Comment by travisghansen** [comment]
Thanks! It is expected that pods will crash or generally have problems if the storage is lost during an upgrade. nfs generally does better at recovering than iscsi in this scenario as iscsi can/will go read only and there’s not currently a good way to detect that and automatically kick the pods. There are some features being built into k8s that should help detect problem situations and restart pods however. That is still being spec’d out though so may be a bit before it lands.

If you’re truly after HA mission critical stuff then you should probably reach out to iXsystems and get a license (for truenas enterprise). With that setup in HA mode you effectively have 2 servers attached to the storage array. When 1 server is updated the other takes over the array so you should be able to update with 0 downtime. I don’t have a lot of experience with it so probably best to get more details from them.

**Comment by alexanderniebuhr** [comment]
thanks for your great answer. I guess I will try to check NFS over ISCSI.
Do you have any direct link to the k8s features for detecting storage issues and triggering pod restart?

good hint with the HA solution..

**Comment by travisghansen** [comment]
This is the beginnings of it (I’ve implemented basic support already if you turn on csi version 1.3).

k8s doesn’t *do* anything yet when problems are detected.

- https://kubernetes-csi.github.io/docs/external-health-monitor-agent.html
- https://github.com/kubernetes-csi/external-health-monitor/issues/58

**Comment by alexanderniebuhr** [comment]
cool thanks.
Doesn't depend the csi version on k8s version installed? Never thought that there might be a way to update csi version without cluster upgrade?

**Comment by travisghansen** [comment]
There is a piece witch requires support of k8s itself. I’m not sure where the matrix is though :( If I find it I’ll attach here. I’m guessing for 1.3 you’ll need 1.20 or 1.21.

**Comment by alexanderniebuhr** [comment]
going to close this for now. All my questions are answered and I think I can make it work
