### ISSUE TITLE
Add support for CIFS creds per PVC

### ISSUE THREAD

**Issue by xhejtman** [democratic-csi/democratic-csi#83]
It would be nice to add support so that user can provide CIFS creds per particular PVC, not only global.

**Comment by travisghansen** [comment]
I’ve realized this is already available.

- https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html#per-volume-secrets

You set it using the dynamic style mentioned in the doc for the stage operation. Simply create a key in the secret called `mount_flags` where the syntax would be `-o foo=bar -o bar=baz ...` and you should be good (this feature works for all drivers fyi, not just smb). I’ve not tested this thoroughly but I think you need to make sure the secret exists before the pvc (at a minimum before it is used/mounted).

**Comment by xhejtman** [comment]
It won't work if you need pre/post command, will it? Or are these mount_flags passed to the postStart command needed it the driver?
