### ISSUE TITLE
iscsi install failure on nodes

### ISSUE THREAD

**Issue by deefdragon** [democratic-csi/democratic-csi#86]
I am attempting to get everything installed on my nodes so that I can connect it, but I am running into some issues. 

when I run `sudo systemctl enable multipath-tools.service` I get 
```
Synchronizing state of multipath-tools.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable multipath-tools
Failed to enable unit: Refusing to operate on linked unit file multipath-tools.service
```
tho `sudo systemctl status multipath-tools` shows it as active

and when I check `sudo systemctl status open-iscsi` I get 
```
● open-iscsi.service - Login to default iSCSI targets
   Loaded: loaded (/lib/systemd/system/open-iscsi.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Thu 2021-05-13 03:52:17 UTC; 17ms ago
           ├─ ConditionDirectoryNotEmpty=|/etc/iscsi/nodes was not met
           └─ ConditionDirectoryNotEmpty=|/sys/class/iscsi_session was not met
     Docs: man:iscsiadm(8)
           man:iscsid(8)
```

Im on Ubuntu 18.04, and this is /lib/systemd/system/open-iscsi.service
```
[Unit]
Description=Login to default iSCSI targets
Documentation=man:iscsiadm(8) man:iscsid(8)
Wants=network-online.target remote-fs-pre.target
After=network-online.target iscsid.service
Before=remote-fs-pre.target
DefaultDependencies=no
Conflicts=shutdown.target
Before=shutdown.target
# Must have some pre-defined targets to login to
ConditionDirectoryNotEmpty=|/etc/iscsi/nodes
# or have a session to use via iscsid
ConditionDirectoryNotEmpty=|/sys/class/iscsi_session

[Service]
Type=oneshot
RemainAfterExit=true
# iscsiadm --login will return 21 if no nodes are configured,
# and 15 if a session is alread logged in (which we do not
# consider an error)
SuccessExitStatus=15 21
# Note: iscsid will be socket activated by iscsiadm
ExecStart=/sbin/iscsiadm -m node --loginall=automatic
ExecStart=/lib/open-iscsi/activate-storage.sh
ExecStop=/lib/open-iscsi/umountiscsi.sh
ExecStop=/bin/sync
ExecStop=/lib/open-iscsi/logout-all.sh

[Install]
WantedBy=sysinit.target
Alias=iscsi.service
```

from what I can tell, its implied here that those two directories cant be empty, but I though that all the connection stuff would be handled by this container?

**Comment by travisghansen** [comment]
That's a good question! For a start I would suggest:

- `modprobe iscsi_tcp`
- `mkdir -p /etc/iscsi/nodes`

After doing that see if the services start successfully.

The reason these services need to be managed outside the container is due to how the iscsi daemon interfaces with the kernel...you can't really have 2 daemons (ie: host level vs containers) trying to control the kernel simultaneously. What happens behind the scenes by the container is that is actually runs the iscsiadm binary from the host in a chroot environment (also because of potential version mismatches from 'host' stuff versus container stuff).

**Comment by deefdragon** [comment]
unfortunately that didn't do it. Still getting `ConditionDirectoryNotEmpty`s

**Comment by travisghansen** [comment]
Is the `iscsid` service running? That's all the really matters..

**Comment by deefdragon** [comment]
It is now. Unfortunately when I try to deploy and add a test pod, I still get `InvalidArgument desc = invalid access_mode, MULTI_NODE_MULTI_WRITER` I've attached the full provisioner log if that helps anything.

[zfs-iscsi-democratic-csi-controller-58d5898f48-hgj9r.log](https://github.com/democratic-csi/democratic-csi/files/6474085/zfs-iscsi-democratic-csi-controller-58d5898f48-hgj9r.log)

**Comment by travisghansen** [comment]
You can do RWX (ReadWriteMany) with iscsi...that's expected. Can try 1 with ReadWriteOnce.

**Comment by deefdragon** [comment]
Switched to RWO. that did indeed allow the PV to be created. After a number of other errors that I eventually figured out, I managed to get it working. Thanks for the assistance.

One of those problems BTW was that I had the wrong port set. https://github.com/democratic-csi/democratic-csi/blob/master/examples/freenas-iscsi.yaml line 63 has the port set as 3261, while the default is 3260. Didn't think to check that as I assumed it used the defaults.

Second, iscsi.targetPortals could use a comment that it should be included even if empty. That was something I hit my head against when misinterpreting the errors I was receiving in the logs (I commented it out and started getting join/undefined errors).

**Comment by travisghansen** [comment]
Oh man thanks for pointing those out! I had no idea I had the wrong port in there. I'll fix that ASAP. I'll check out the code about the `targetPortals` as well.

**Comment by deefdragon** [comment]
I also threw together a quick thing on how to migrate _data_ over if you find it worth adding. I found the other two guides on creating and migrating **very** useful, but nothing went over migrating any data that I already had. And not much on that anywhere else on the internet for that matter. I had someone else give it a read-through already, but if you have anything else to add or change let me know.

https://gist.github.com/deefdragon/d58a4210622ff64088bd62a5d8a4e8cc

**Comment by travisghansen** [comment]
Oh yeah that’s a great howto. I’ll add it to the doc! One note about deleting the pvc, it’s less scary if you suggest the user set the reclaim policy to Retain on the PV beforehand...that will prevent a provisioner from deleting the PV.

**Comment by travisghansen** [comment]
I should also say, if you're using `velero` I've had it reported that the csi snapshot functionality works just great with this project.

**Comment by travisghansen** [comment]
OK, doc has been updated (adding your gist as a community guide) and code has been altered to better cope with the missing value of the `targetPortals`.

https://github.com/democratic-csi/democratic-csi/commit/8765da65c45e37fff54fb259d0f4b28cb7f6ccb0
