### ISSUE TITLE
request for info on implementing zfs-local-ephemeral-inline

### ISSUE THREAD

**Issue by dlbewley** [democratic-csi/democratic-csi#9]
Sorry if I'm dense, I'm trying to test zfs-local-ephemeral-inline with my OpenShift cluster and a FreeNAS server. 

I expected the k8s nodes to reach out to the FreeNAS device and provision the ephemeral volumes, but there is no mention of the FreeNAS server in https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/examples/zfs-local-ephemeral-inline.yaml

Do we just add an ssh config like this https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/examples/freenas-nfs.yaml#L55-L64 ? I'm wondering if httpConnection is an option. 

Can you confirm my understanding that this driver will work with a remote FreeNAS server and link to the documentation for the driver config parameters?

**Comment by travisghansen** [comment]
@dlbewley thanks for the interest in the project! That driver is actually meant to be used with zfs on the node..locally (ie: a zfs pool on each node directly). hypothetically that could be an iscsi mount to FreeNAS but you would still need support for zfs on the node directly.

Having said that, there is currently a proposal with k8s floating around that may be alpha/beta in 1.19 which would allow any provisioner (csi or not) to be used as ephemeral storage (think of it as an ephemeral PVC...which is actually how it works).

Does that help explain the difference (and why there's no ssh/http connection details in the example)?

**Comment by dlbewley** [comment]
Thanks for the response. I guess I didn't want to understand that to be the use case. :) Fair enough. Keep up the great work.

And I think this is what you are referring to https://github.com/kubernetes/enhancements/issues/1698

**Comment by travisghansen** [comment]
Indeed that is the kep. If you think of any other use-cases (zfs related or not) let me know. The heavy lifting is done so new stuff is quite easy. Even this request could be done quite easily but since there’s a proper kep we’ll wait for that.
