### ISSUE TITLE
TrueNAS 12.0-U3 and nopasswd sudo

### ISSUE THREAD

**Issue by infra-monkey** [democratic-csi/democratic-csi#92]
Hello,

According to the TrueNAS release note, they made it possible to call sudo without password ( https://jira.ixsystems.com/browse/NAS-107219 )
@travisghansen I see you commented on that issue.

However, I fail to see how to configure an account with pubkey only and sudo permissions... TrueNAS UI hides the option.

Do you have more information on how to integrate democratic-csi with truenas using a passwordless non root account?

Currently, the only proper way to go is using the root account, which is a solution I don't like.

Maybe this question should be asked to ixsystems?

I'll be happy to make a PR for documentation if needed afterwards

Thanks

**Comment by travisghansen** [comment]
That’s a good question. I think you may be correct but I’ll check when back at my desk.

I also have instructions on how to set the value with the cli tools if you haven’t seen examples of that.

**Comment by infra-monkey** [comment]
If you mean modifying manually the sudo rules, I have seen it.
The problem being that any rule you set will be resetted at the next reboot or upgrade. Doesn't look like a sustainable solution.
Good for testing though.

No rush for a resolution here, it works fine with root.

**Comment by travisghansen** [comment]
No, it is now possible to make it persist reboots.

https://github.com/democratic-csi/democratic-csi/issues/34#issuecomment-822861979

**Comment by infra-monkey** [comment]
Damn I missed that one !
I'll check it out. 
Thank you very much

**Comment by travisghansen** [comment]
I have it queued up to get that documented as well but haven’t snapped a new release yet.

**Comment by travisghansen** [comment]
OK yeah, we should probably open a ticket with iX to allow disable password in conjunction with permit sudo. Given the history here I understand why they made that decision but the current realities don't reflect the past.

**Comment by travisghansen** [comment]
An alternative may be to actually enable sudo (with nopasswd) on the group for now as an FYI.

**Comment by infra-monkey** [comment]
Well actually I think it would be ideal to be able to run the zfs commands through the api instead of ssh. That would make a single truenas configuration dependency instead of 2.
But I understand it wouldn't be consistent with the other integrations of democratic-csi.

Anyway, the configuration of the user looks fine with the cli tool.
However, I'm having trouble downloading the container to test it:
`Failed to pull image "democraticcsi/democratic-csi:latest": rpc error: code = Unknown desc = Error reading manifest latest in quay.io/democraticcsi/democratic-csi: unauthorized: access to the requested resource is not authorized`

I'll keep you posted.

**Comment by travisghansen** [comment]
Yeah, a strictly api-based variant/driver is in the works. I have yet to start the coding as I've been busy but it will happen. There are some gaps in the api that need created before I can fully complete it.

I'm not sure where that image came from above...the project is on docker hub only atm, not on quay.

- https://jira.ixsystems.com/browse/NAS-110637

**Comment by infra-monkey** [comment]
For the quay thing, it must be the default registry of my cluster. I must have had a connectivity issue with dockerhub.
Strange indeed, but in the end it passed with a lot of patience.

Test is ok, works fine !
Thanks for the help.

A full api driver would be nice ! And thank you for the great works already :)
I appreciate it, and i'm sure a lot of others do too.

Do you want me to make a PR for the documentation of the user configuration, or you'd rather do it yourself?

**Comment by travisghansen** [comment]
I already have it queued up but thanks! I'll update the image references in the chart to include registry so folks don't find themselves in that situation. Let's leave this open until that has been taken care of.

**Comment by travisghansen** [comment]
To close the loop on all this...

For reference I created this:

- https://jira.ixsystems.com/browse/NAS-112087

If you want to disable the password on an account you may use the following:

```
account user update id=<id> password_disabled=true
```

A strictly api-based driver has been released (experimental) but it (currently) only works with SCALE 21.08+. See the current README.md with details and other links etc.

Images are now also being published to ghcr but I have not changed the defaults around in the chart. I likely will at some point.
