### ISSUE TITLE
Deployment Per Truenas Pool?

### ISSUE THREAD

**Issue by al-jodytooley** [democratic-csi/democratic-csi#99]
I have 2 storage pools in my TrueNAS server:  a pool of SSDs and a pool of HDDs.  I would like to make them both available via the truenas nfs driver.  Do I need to have 2 separate deployments of democratic-csi?  If I want to introduce the truenas iscsi driver at some point and make each of the pools available via iscsi, will I end up with 4 deployments?

**Comment by travisghansen** [comment]
Yes that would currently require 4 deployments that’s correct.

Of similar note you can have multiple storage classes per deployment however. For example 2 different classes for iscsi 1 with ext4 and the other with xfs. Or different mount options specified…things like that.
